p2p-org/p2p-wallet-ios

p2p_wallet/Scenes/Main/MainViewController.swift
https://p2pvalidator.atlassian.net/browse/P2PW-1066
=> fix: pincode over alert buggie alert layout

p2p_wallet/Scenes/Main/Buy/SolanaBuyToken/SolanaBuyToken.SceneModel.swift, p2p_wallet/Scenes/Main/DApps/DAppContainer/DAppContainer.RootView.swift, p2p_wallet/Scenes/Main/DApps/DAppContainer/DAppContainer.ViewModel.swift, p2p_wallet/Services/DAppChannel.swift, p2p_wallet/UIKit/Views/WLNavigationBar.swift
[Link](https://p2pvalidator.atlassian.net/browse/P2PW-1191)
=> Fix warnings

p2p_wallet/Scenes/Main/ReceiveToken/NetworkSelection/NetworkSelection.BitcoinConfirm.ViewController.swift, p2p_wallet/Scenes/Main/ReceiveToken/ReceiveToken.ViewBuilders.swift, p2p_wallet/en.lproj/Localizable.strings
[Link](https://p2pvalidator.atlassian.net/browse/P2PW-1174)
=> Improve confirmation screen

p2p_wallet/Scenes/Main/ReceiveToken/Bitcoin/ReceiveToken.ReceiveBitcoinView.swift, p2p_wallet/en.lproj/Localizable.strings, p2p_wallet/fr.lproj/Localizable.strings, p2p_wallet/ru.lproj/Localizable.strings, p2p_wallet/vi.lproj/Localizable.strings
[Link](https://p2pvalidator.atlassian.net/browse/P2PW-1174)
=> [P2PW-1174]: Improve receive bitcoin screen

p2p_wallet/Scenes/Main/ReceiveToken/Bitcoin/ReceiveToken.ReceiveBitcoinView.swift, p2p_wallet/Scenes/Main/ReceiveToken/NetworkSelection/NetworkSelection.BitcoinConfirm.ViewController.swift, p2p_wallet/Scenes/Main/ReceiveToken/NetworkSelection/NetworkSelection.ViewController.swift, p2p_wallet/Scenes/Main/ReceiveToken/Views/ReceiveToken.QrCodeCard.swift, p2p_wallet/Scenes/Main/ReceiveToken/Views/ReceiveToken.QrCodeView.swift, p2p_wallet/Scenes/Main/ReceiveToken/Views/ReceiveToken.ViewBuilders.swift, p2p_wallet/Scenes/Main/Settings/Settings.ViewModel.swift, p2p_wallet/Scenes/Main/Settings/Subscenes/Settings.UsernameViewController.swift, p2p_wallet/en.lproj/Localizable.strings
[1174](https://p2pvalidator.atlassian.net/browse/P2PW-1174)
[1162](https://p2pvalidator.atlassian.net/browse/P2PW-1162)
[1173](https://p2pvalidator.atlassian.net/browse/P2PW-1173)
=> Fix receive screen

p2p_wallet/Scenes/Main/SwapToken/OrcaSwapV2/OrcaSwapV2.ViewModel/OrcaSwapV2.ViewModel.swift
https://p2pvalidator.atlassian.net/jira/software/projects/P2PW/boards/20?selectedIssue=P2PW-1133
-
=> feat: orca swap account creation fee

p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/EnterSeedViewController/EnterSeed.NavigationBar.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/EnterSeedViewController/EnterSeed.RootView.swift
https://p2pvalidator.atlassian.net/browse/P2PW-1163
=> [P2PW-1163] Security screen

p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/DerivableAccounts/DerivablePaths/DerivablePaths.ViewController.swift
https://p2pvalidator.atlassian.net/browse/P2PW-1086
=> [P2PW-1086] Fix DerivableAccounts

p2p_wallet/Scenes/Main/ReceiveToken/Bitcoin/ReceiveToken.ReceiveBitcoinView.swift, p2p_wallet/Scenes/Main/ReceiveToken/Bitcoin/ReceiveToken.ReceiveBitcoinViewModel.swift
https://p2pvalidator.atlassian.net/browse/P2PW-1171
=> [P2PW-1171] Receive screen - bitcoin

p2p_wallet/Scenes/Main/Settings/Settings.ViewModel.swift
https://p2pvalidator.atlassian.net/browse/P2PW-1067
=> [P2PW-1067] Device pin code

p2p_wallet/UIKit/Views/WLNavigationBar.swift
https://p2pvalidator.atlassian.net/jira/software/projects/P2PW/boards/20?selectedIssue=P2PW-1218
I considered some options, but haven't found a better way to fix this. I think that in the case of two or more lines, it still won't work as expected.
=> fix: linebreak of title in navigation bar

p2p_wallet/Scenes/Main/SwapToken/OrcaSwapV2/OrcaSwapV2.ViewController.swift
https://p2pvalidator.atlassian.net/browse/P2PW-1219
=> Unwanted animation on swap

p2p_wallet/Models/PayingFee.swift, p2p_wallet/Scenes/Main/SwapToken/OrcaSwapV2/OrcaSwapV2.ViewModel/OrcaSwapV2.ViewModel.swift, p2p_wallet/Services/SwapProvider/SerumSwap+SwapProviderType.swift
https://p2pvalidator.atlassian.net/browse/P2PW-1133
Make update if tokens changes in swap and add token to account creation label
=> fix(swap): account creation fee without token and not updatable

p2p_wallet/Scenes/Main/ReceiveToken/Bitcoin/ReceiveToken.ReceiveBitcoinView.swift, p2p_wallet/Scenes/Main/ReceiveToken/Bitcoin/ReceiveToken.ReceiveBitcoinViewModel.swift, p2p_wallet/Scenes/Main/ReceiveToken/ReceiveToken.SceneModel.swift, p2p_wallet/Scenes/Main/ReceiveToken/Solana/ReceiveToken.ReceiveSolanaView.swift, p2p_wallet/Scenes/Main/ReceiveToken/Solana/ReceiveToken.ReceiveSolanaViewModel.swift
https://p2pvalidator.atlassian.net/jira/software/projects/P2PW/boards/20?label=iOS&selectedIssue=P2PW-1094
=> receive in token testing fixes

p2p_wallet/Scenes/Main/Buy/SolanaBuyToken/SolanaBuyToken.Scene.swift
https://p2pvalidator.atlassian.net/jira/software/projects/P2PW/boards/20?selectedIssue=P2PW-1229
=> Buy token keyboard appearing

p2p_wallet/Scenes/Main/ReceiveToken/ReceiveToken.SceneModel.swift, p2p_wallet/Scenes/Main/ReceiveToken/ReceiveToken.ViewController.swift
https://p2pvalidator.atlassian.net/jira/software/projects/P2PW/boards/20?selectedIssue=P2PW-1094
=> fix(receive in token): renBTC screen options

p2p_wallet/Scenes/Main/ReceiveToken/ReceiveToken.ViewController.swift
https://p2pvalidator.atlassian.net/jira/software/projects/P2PW/boards/20?selectedIssue=P2PW-1222
=> fix(receive screen): change network style

p2p_wallet/en.lproj/Localizable.strings, p2p_wallet/fr.lproj/Localizable.strings, p2p_wallet/ru.lproj/Localizable.strings, p2p_wallet/vi.lproj/Localizable.strings
https://p2pvalidator.atlassian.net/browse/P2PW-1172
=> Fix setting

p2p_wallet/Scenes/Main/Settings/Settings.ViewController.swift
https://p2pvalidator.atlassian.net/browse/P2PW-1278
=> Fix settings

p2p_wallet.xcodeproj/project.pbxproj, p2p_wallet/AppDelegate+Injection.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/CreateSecurityKeys/CreateSecurityKeys.RootView.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/CreateSecurityKeys/CreateSecurityKeys.ViewController.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/CreateSecurityKeys/CreateSecurityKeys.ViewModel.swift, p2p_wallet/Scenes/Main/ReceiveToken/Bitcoin/ReceiveToken.ReceiveBitcoinViewModel.swift, p2p_wallet/Scenes/Main/ReceiveToken/ReceiveToken.ViewController.swift, p2p_wallet/Scenes/Main/ReceiveToken/ReceiveToken.swift, p2p_wallet/Scenes/Main/ReceiveToken/Solana/ReceiveToken.ReceiveSolanaViewModel.swift, p2p_wallet/Services/ImageSaver.swift, p2p_wallet/UIKit/Views/PhotoLibraryAlertPresenter.swift, p2p_wallet/en.lproj/Localizable.strings, p2p_wallet/fr.lproj/Localizable.strings, p2p_wallet/ru.lproj/Localizable.strings, p2p_wallet/vi.lproj/Localizable.strings
https://p2pvalidator.atlassian.net/jira/software/projects/P2PW/boards/20?selectedIssue=P2PW-1271
-
=> feat(receive): handle denied access to save photos

p2p_wallet/Scenes/Main/Settings/Settings.ViewController.swift, p2p_wallet/Scenes/Main/Settings/Settings.ViewModel.swift, p2p_wallet/Scenes/Main/Settings/Settings.swift, p2p_wallet/Scenes/Main/Settings/Subscenes/Settings.UsernameViewController.swift
https://p2pvalidator.atlassian.net/browse/P2PW-1257
-
=> Fix handling the error when access to photo is denied on the setting screen

p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/EnterSeedViewController/EnterSeed.RootView.swift
https://p2pvalidator.atlassian.net/browse/P2PW-1250
-
=> Fix the location of the buttons relative to the keyboard

p2p_wallet/Scenes/CreateOrRestoreWallet/ReserveName/ReserveName.ViewModel.swift, p2p_wallet/Scenes/Main/Home/Home.ViewController.swift, p2p_wallet/Scenes/Main/Home/Home.ViewModel.swift, p2p_wallet/Scenes/Main/Settings/Settings.ViewModel.swift, p2p_wallet/Scenes/Main/Settings/Settings.swift, p2p_wallet/Scenes/Main/TabBarVC/TabBarVC.swift
https://p2pvalidator.atlassian.net/browse/P2PW-1265
-
=> Fix notification when user reverses username

p2p_wallet/AppDelegate+Injection.swift, p2p_wallet/Scenes/Main/Buy/SolanaBuyToken/SolanaBuyToken.Scene.swift, p2p_wallet/Scenes/Main/SwapToken/OrcaSwapV2/OrcaSwapV2.RootView.swift
https://p2pvalidator.atlassian.net/browse/P2PW-1282
https://p2pvalidator.atlassian.net/browse/P2PW-1250
https://p2pvalidator.atlassian.net/browse/P2PW-1367
-
=> Improve design

p2p_wallet/Scenes/Main/Home/Home.RootView.swift, p2p_wallet/Scenes/Main/Home/Home.ViewController.swift, p2p_wallet/Scenes/Main/Home/Home.swift, p2p_wallet/Scenes/Main/Home/Subviews/Home.EmptyView.swift, p2p_wallet/Scenes/Main/Home/Subviews/Home.Header.swift
https://p2pvalidator.atlassian.net/browse/P2PW-1368
-
=> Fix buy screen navigation from Home Screen

p2p_wallet/AppDelegate+Injection.swift
https://p2pvalidator.atlassian.net/browse/P2PW-1409
-
=> Fix banner 

p2p_wallet/Scenes/Main/Home/Home.RootView.swift, p2p_wallet/Scenes/Main/Home/Home.ViewController.swift, p2p_wallet/Scenes/Main/Home/Subviews/Banner/Home.BannerSection.swift, p2p_wallet/Scenes/Main/Settings/Subscenes/Backup/Settings.BackupViewController.swift, p2p_wallet/Services/Banner/BannerServiceImpl.swift, p2p_wallet/Services/Banner/Handler/BackupBannerHandler.swift, p2p_wallet/Services/Storage.swift
https://p2pvalidator.atlassian.net/browse/P2PW-1410
-
=> Open backup screen from Home Screen

p2p_wallet/Scenes/Main/SwapToken/Settings/SwapTokenSettings.ViewModel.swift, p2p_wallet/en.lproj/Localizable.strings, p2p_wallet/fr.lproj/Localizable.strings, p2p_wallet/ru.lproj/Localizable.strings, p2p_wallet/vi.lproj/Localizable.strings
https://p2pvalidator.atlassian.net/browse/P2PW-1296
-
=> Add notification when user change swap value

p2p_wallet/Scenes/Main/Buy/SolanaBuyToken/SolanaBuyToken.Scene.swift, p2p_wallet/Scenes/Main/Buy/SolanaBuyToken/SolanaBuyToken.SceneModel.swift, p2p_wallet/Services/Buy/Exchange/BuyExchangeServiceType.swift, p2p_wallet/Services/Buy/Exchange/Moonpay/MoonpayExchangeService.swift, p2p_wallet/Services/Buy/Exchange/Moonpay/Provider/Moonpay.Model.swift, p2p_wallet/Services/Buy/Exchange/Moonpay/Provider/Moonpay.Provider.swift, p2p_wallet/en.lproj/Localizable.strings, p2p_wallet/fr.lproj/Localizable.strings, p2p_wallet/ru.lproj/Localizable.strings, p2p_wallet/vi.lproj/Localizable.strings
=> Fix padding in buy screen

p2p_wallet/UIKit/Views/WalletsCollectionView/BaseHiddenWalletSection.swift
https://p2pvalidator.atlassian.net/browse/P2PW-1461
-
=> Fix hidden section displaying

p2p_wallet/Base.lproj/LaunchScreen.storyboard, p2p_wallet/Extensions/UIView+Extensions.swift, p2p_wallet/Scenes/Main/Home/Subviews/Home.BalanceView.swift, p2p_wallet/Scenes/Main/Home/Subviews/Home.EmptyView.swift, p2p_wallet/UIKit/Views/WalletCells/BaseWalletCell.swift
https://p2pvalidator.atlassian.net/browse/P2PW-1264
-
=> Improve Home Screen

p2p_wallet/Scenes/Main/Home/Home.RootView.swift, p2p_wallet/Scenes/Main/Home/Subviews/Home.EmptyView.swift
https://p2pvalidator.atlassian.net/browse/P2PW-1468
=> feat(home): improve

p2p_wallet/Scenes/Main/Buy/Preparing/BuyPreparing.Scene.swift, p2p_wallet/Services/Buy/Buy.swift
https://p2pvalidator.atlassian.net/browse/P2PW-1477
-
=> Improve buy screen

p2p_wallet/Extensions/NSMutableAttributedString+Extensions.swift, p2p_wallet/Models/PayingFee.swift, p2p_wallet/Scenes/Main/SendToken/Subscenes/Confirm/SendToken.ConfirmViewController.swift, p2p_wallet/Scenes/Main/SwapToken/OrcaSwapV2/ConfirmSwapping/OrcaSwapV2.ConfirmSwapping.RootView.swift, p2p_wallet/Scenes/Main/SwapToken/OrcaSwapV2/ConfirmSwapping/OrcaSwapV2.ConfirmSwapping.ViewModel.swift, p2p_wallet/Scenes/Main/SwapToken/OrcaSwapV2/ConfirmSwapping/OrcaSwapV2ConfirmSwappingViewModelType.swift, p2p_wallet/Scenes/Main/SwapToken/OrcaSwapV2/OrcaSwapV2.ViewController.swift, p2p_wallet/Scenes/Main/SwapToken/OrcaSwapV2/OrcaSwapV2.ViewModel/OrcaSwapV2.ViewModel+Extensions.swift, p2p_wallet/Scenes/Main/SwapToken/OrcaSwapV2/OrcaSwapV2.ViewModel/OrcaSwapV2.ViewModel.swift, p2p_wallet/Scenes/Main/SwapToken/OrcaSwapV2/OrcaSwapV2.ViewModel/OrcaSwapV2ViewModelType.swift, p2p_wallet/Scenes/Main/SwapToken/OrcaSwapV2/Subviews/OrcaSwapV2.DetailFeesView.swift, p2p_wallet/Scenes/Main/SwapToken/OrcaSwapV2/Subviews/OrcaSwapV2.DetailsView.swift
https://p2pvalidator.atlassian.net/browse/PWN-1557
-
=> feat: update fee amounts with equity value in fiat

p2p_wallet/Scenes/Main/SendToken/SendToken.ViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-1619
-
=> fix: wallet observable

p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/RestoreWallet.ViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-3120
-
=> feat: save to icloud after restoring

p2p_wallet/Scenes/Main/TransactionDetail/Subviews/TransactionDetail.AmountSection.swift, p2p_wallet/Scenes/Main/TransactionDetail/TransactionDetail.ViewModel.swift, p2p_wallet/Services/NameService/NameServiceCache.swift
https://p2pvalidator.atlassian.net/browse/PWN-1592
-
=> fix(wallet-detail): ui

p2p_wallet/Scenes/Main/Home/Home.ViewController.swift
https://p2pvalidator.atlassian.net/browse/PWN-3183
-
=> hotfix: navbar disappear

p2p_wallet/Scenes/Main/SendToken/SendToken.ViewModel.swift, p2p_wallet/Scenes/Main/SendToken/Subscenes/ChooseRecipientAndNetwork/SelectAddress/SendToken.ChooseRecipientAndNetwork.SelectAddress.RootView.swift
https://p2pvalidator.atlassian.net/browse/PWN-3177
-
=> fix: handle case when paying wallet is the same as source wallet

p2p_wallet/Scenes/Main/SendToken/SendToken.ViewModel.swift, p2p_wallet/Scenes/Main/SendToken/Subscenes/ChooseRecipientAndNetwork/SendToken.ChooseRecipientAndNetwork.ViewModel.swift, p2p_wallet/Scenes/Main/SwapToken/OrcaSwapV2/OrcaSwapV2.RootView.swift, p2p_wallet/Scenes/Main/SwapToken/OrcaSwapV2/OrcaSwapV2.ViewModel/OrcaSwapV2.Helper.swift, p2p_wallet/Scenes/Main/SwapToken/OrcaSwapV2/OrcaSwapV2.ViewModel/OrcaSwapV2.ViewModel.swift, p2p_wallet/Services/Swap/Swap.swift
https://p2pvalidator.atlassian.net/browse/PWN-3099
- Auto select fee token
=> Auto select fee token

p2p_wallet/Scenes/Main/SendToken/SendToken.ViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-3215
- Fix crash
=> Application crashes when sending with compensation in sending token immediately after confirming transaction with pin/touchID/FaceID 

.github/workflows/pull_request.yml
- Send task to Review tab when a feature PR is created
=> feat: add pull request created event

Podfile, Podfile.lock
- Update project to support swift concurrency
=> Swift concurrency support

Podfile.lock, p2p_wallet.xcodeproj/project.pbxproj, p2p_wallet.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings, p2p_wallet/Extensions/Array+Extensions.swift, p2p_wallet/Scenes/Main/History/History.Scene.swift, p2p_wallet/Scenes/Main/History/History.SceneModel.swift, p2p_wallet/Scenes/Main/History/History.SourceStream.swift, p2p_wallet/Scenes/Main/History/HistoryCell.swift, p2p_wallet/Scenes/Main/WalletDetail/History/TransactionCollectionView/Subviews/TransactionCell.swift, p2p_wallet/Services/AnalyticsManager/AnalyticsEvent.swift
https://p2pvalidator.atlassian.net/browse/PWN-
-
=> PWN-3256: iOS. 2: Add transaction screen skeleton

p2p_wallet/Scenes/Main/Home/Home.RootView.swift
https://p2pvalidator.atlassian.net/browse/PWN-3233
-
=> feat(blank-screen): combineLatest instead of zip

p2p_wallet/UIKit/Views/WalletCells/BaseWalletCell.swift
https://p2pvalidator.atlassian.net/browse/PWN-3137
-
=> [iOS] Update main screen icons

README.md
=> fix: changed documentation config filename

p2p_wallet/Scenes/Main/TabBarVC/NewTabBar.swift, p2p_wallet/Scenes/Main/TabBarVC/TabBar.swift, p2p_wallet/Scenes/Main/TabBarVC/TabBarVC.swift
=> iOS. 1: History icon in bottom tabbar

p2p_wallet/Scenes/Main/History/Transaction/ViewModel/TransactionViewModel.swift, p2p_wallet/Scenes/Main/TabBarVC/NewTabBar.swift, p2p_wallet/Scenes/Main/TabBarVC/TabBarVC.swift, p2p_wallet/Scenes/Main/WalletDetail/History/TransactionCollectionView/Subviews/TransactionCell.swift
=> PWN-1578: bug fixing

p2p_wallet/Scenes/Main/History/HistoryCell.swift, p2p_wallet/Scenes/Main/WalletDetail/History/TransactionCollectionView/Subviews/TransactionCell.swift
https://p2pvalidator.atlassian.net/browse/PWN-3428
-
=> [PWN-3428] Transaction history screen design

p2p_wallet/Scenes/Main/History/History.SceneModel.swift, p2p_wallet/Scenes/Main/History/Output/History.ProcessingTransactionsOutput.swift, p2p_wallet/Scenes/Main/WalletDetail/History/TransactionCollectionView/Subviews/TransactionImageView.swift
https://p2pvalidator.atlassian.net/browse/PWN-3429
-
=> [PWN-3429] fix(history): update transaction

p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/DerivableAccounts/DerivableAccounts.Cell.swift, p2p_wallet/Scenes/Main/SendToken/SendToken.FeeView.swift, p2p_wallet/Scenes/Main/SendToken/Subscenes/ChooseTokenAndAmount/SendToken.ChooseTokenAndAmount.RootView.swift, p2p_wallet/Scenes/Main/SendToken/Subscenes/Confirm/SendToken.ConfirmViewController.swift, p2p_wallet/Scenes/Main/SwapToken/SerumSwap(Unstable)/SwapToken.WalletView.swift, p2p_wallet/Scenes/Main/TransactionDetail/Subviews/TransactionDetail.AmountSection.swift, p2p_wallet/Scenes/Main/WalletDetail/History/TransactionCollectionView/Subviews/TransactionCell.swift
https://p2pvalidator.atlassian.net/browse/PWN-3519
-
=> [PWN-3519] USD Formatting

p2p_wallet/Services/AuthenticationHandler.swift
https://p2pvalidator.atlassian.net/browse/PWN-3556
-
=> [PWN-3556] PWN-3556: Lock Screen

p2p_wallet/Scenes/Main/SendToken/Subscenes/ChooseTokenAndAmount/SendToken.ChooseTokenAndAmount.RootView.swift
https://p2pvalidator.atlassian.net/browse/PWN-3558
-
=> [PWN-3558] Don't round up the available token amounts

p2p_wallet/Scenes/Main/SendToken/Subscenes/ChooseTokenAndAmount/SendToken.ChooseTokenAndAmount.RootView.swift
=> Don't round up the available token amounts

p2p_wallet/Scenes/Main/SwapToken/Settings/Subviews/SwapTokenSettings.CustomSlippageField.swift, p2p_wallet/Scenes/Main/SwapToken/Settings/Subviews/SwapTokenSettings.SlippageView.swift
https://p2pvalidator.atlassian.net/browse/PWN-1591
-
=> [PWN-1591] feat(swap-setting): change keyboard type and refactor view

p2p_wallet/Scenes/Main/History/History.SceneModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-3607
-
=> [PWN-3607] Fix history transactions

p2p_wallet/Scenes/Main/TabBarVC/TabBarVC.swift
https://p2pvalidator.atlassian.net/browse/PWN-3642
-
=> [PWN-3642] Fix crash on send screen

p2p_wallet.xcodeproj/project.pbxproj, p2p_wallet/Scenes/ReserveName/ReserveName.ViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-3227
-
=> [PWN-3227] feat: catch error code 500

p2p_wallet/Scenes/Main/SendToken/Subscenes/ChooseRecipientAndNetwork/SelectAddress/SendToken.ChooseRecipientAndNetwork.SelectAddress.ViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-3645
-
=> [PWN-3645] feat: patch

.githooks/post-checkout, .githooks/pre-commit, .github/workflows/beta.yml, .github/workflows/pull_request_review.yml, .github/workflows/release.yml, README.md, Scripts/install.sh, Scripts/postxcodegen.sh, fastlane/Fastfile, project.yml
- The code in postxcodegen is one-time-called, so there is no need to call these function each time after xcodegen
=> Fix: CI broken after xcodegen

p2p_wallet/Models/PendingTransaction.swift, p2p_wallet/Scenes/Main/History/Transaction/ViewModel/TransactionViewModel.swift, p2p_wallet/Scenes/Main/TransactionDetail/Subviews/TransactionDetail.SummaryView.swift
https://p2pvalidator.atlassian.net/browse/PWN-3864
-
=> [PWN-3864] feat(transfer): fix displaying amount

p2p_wallet/Services/Buy/Exchange/Moonpay/MoonpayExchangeService.swift, p2p_wallet/Services/Buy/Exchange/Moonpay/Provider/Moonpay.Provider.swift
https://p2pvalidator.atlassian.net/browse/PWN-3919
-
=> [PWN-3919] Processing fee fix

p2p_wallet/Scenes/Main/Buy/Preparing/Subview/BuyProcessing.InputCryptoView.swift, p2p_wallet/Scenes/Main/Buy/Preparing/Subview/BuyProcessing.InputFiatView.swift, p2p_wallet/Scenes/Main/Buy/TokenSelection/TokenSelection.Scene.swift, p2p_wallet/Services/Buy/Buy.swift
https://p2pvalidator.atlassian.net/browse/PWN-3923
-
=> [PWN-3923] Fix usdc icon

p2p_wallet/Scenes/Main/Home/Home.ViewController.swift, p2p_wallet/UIKit/Views/WalletCells/VisibleWalletCell.swift
https://p2pvalidator.atlassian.net/browse/PWN-3956
-
=> [PWN-3956] Feature/pwn 3956

p2p_wallet/AppDelegate.swift, p2p_wallet/Resources/Assets.xcassets/navigation-back.imageset/Contents.json, p2p_wallet/Scenes/Main/ReceiveToken/ReceiveToken.ViewController.swift, p2p_wallet/Scenes/Main/SendToken/Subscenes/ChooseTokenAndAmount/SendToken.ChooseTokenAndAmount.ViewController.swift, p2p_wallet/Scenes/Main/Settings/Subscenes/Backup/BackupManually/BackupPasteSeedPhrasesVC.swift, p2p_wallet/Scenes/Main/SwapToken/OrcaSwapV2/OrcaSwapV2.ViewController.swift, p2p_wallet/Scenes/Onboarding/Onboarding.EnableNotificationsVC.swift, p2p_wallet/Scenes/ReserveName/ReserveName.ViewController.swift, p2p_wallet/UIKit/Views/WLNavigationBar.swift
https://p2pvalidator.atlassian.net/browse/PWN-3878
-
=> [PWN-3878] Add Navigation Bar to Application Library

p2p_wallet/Scenes/Main/SendToken/Subscenes/ChooseTokenAndAmount/SendToken.ChooseTokenAndAmount.RootView.swift, p2p_wallet/Scenes/Main/SendToken/Subscenes/ChooseTokenAndAmount/SendToken.ChooseTokenAndAmount.ViewController.swift
https://p2pvalidator.atlassian.net/browse/PWN-3961
-
=> [PWN-3961] Action button not showing on the send screen

.githooks/post-checkout, .gitignore, project.yml
https://p2pvalidator.atlassian.net/browse/PWN-4055
-
=> [PWN-4055] Xcodegen fix [No QA]

p2p_wallet/AppDelegate+Injection.swift, p2p_wallet/Services/FeatureFlags/Features.swift
=> Feature toggle for coin gecko

p2p_wallet/Scenes/Main/Home/Home.ViewController.swift
https://p2pvalidator.atlassian.net/browse/PWN-4106
-
=> [PWN-4106] Choose recepient button fix

p2p_wallet/Services/Networking/Endpoint.swift
https://p2pvalidator.atlassian.net/browse/PWN-4037
PRODUCTION - variable was not set. As whole project uses #DEBUG - check so I changed it on this one too
=> [PWN-4037] Fix wrong environment request

p2p_wallet/Scenes/Main/SendToken/Subscenes/ChooseRecipientAndNetwork/SelectAddress/SendToken.ChooseRecipientAndNetwork.SelectAddress.RootView.swift
https://p2pvalidator.atlassian.net/browse/PWN-4126
-
=> [PWN-4126] Feature/pwn 4126

p2p_wallet/AppDelegate+Injection.swift, p2p_wallet/AppDelegate.swift, p2p_wallet/Services/Defaults.swift
=> Featuretoggle support

fastlane/Fastfile
https://p2pvalidator.atlassian.net/browse/PWN-4036
-
=> [PWN-4036] feat: add configuration option to create_release_build

Podfile.lock, p2p_wallet/Scenes/Main/Buy/TokenSelection/TokenSelection.Scene.swift
https://p2pvalidator.atlassian.net/browse/PWN-3959
- Make nicer skeleton
From this:
To this:
=> [PWN-3959] Bugfix/pwn 3959 patch 1

p2p_wallet/AppDelegate.swift, p2p_wallet/Resources/Colors.xcassets/h0b1f35.colorset/Contents.json, p2p_wallet/Resources/Colors.xcassets/h6f7d8d.colorset/Contents.json, p2p_wallet/Scenes/Main/Home/Home.RootView.swift, p2p_wallet/Scenes/TabBar/TabBarController.swift
https://p2pvalidator.atlassian.net/browse/PWN-4233
- blur effect
- tab bar item appearance
- bepurelayout commit will be pushed later as I don't have rights
=> [PWN-4233] Tabbar does not match the design

p2p_wallet/Scenes/Main/Settings/Settings.ViewModel.swift, p2p_wallet/Scenes/Main/Settings/Subscenes/Settings.ConfigureSecurityViewController.swift
https://p2pvalidator.atlassian.net/browse/PWN-3659
-
=> [PWN-3659] Suppress faceid error alert on settings screen

p2p_wallet/Scenes/Main/SendToken/SendToken.ViewModel.swift, p2p_wallet/Scenes/Main/SendToken/Subscenes/ChooseTokenAndAmount/SendToken.ChooseTokenAndAmount.ViewController.swift, p2p_wallet/Scenes/Main/SendToken/Subscenes/ChooseTokenAndAmount/SendToken.ChooseTokenAndAmount.ViewModel.swift, p2p_wallet/Scenes/Main/TabBarVC/TabBarVC.swift
https://p2pvalidator.atlassian.net/browse/PWN-4136
-
=> [PWN-4136] Fix/pwn 4136 form clear fix

p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/EnterSeedViewController/EnterSeed.RootView.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/EnterSeedViewController/EnterSeed.ViewModel.swift, p2p_wallet/UIKit/Views/ExpandableTextView.swift
https://p2pvalidator.atlassian.net/browse/PWN-3857
-
=> [PWN-3857] Limit the input of seed phrase words up to 24

p2p_wallet/UIKit/Views/WalletCells/VisibleWalletCell.swift
https://p2pvalidator.atlassian.net/browse/PWN-4119
-
=> [PWN-4119] fix(home): disable swipe action during loading

Podfile.lock
https://p2pvalidator.atlassian.net/browse/PWN-3957
-
=> [PWN-3957] fix: socket parsing

p2p_wallet/UIKit/ViewModels/WalletsViewModel/WalletsViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-4288
-
=> [PWN-4288] Feature/pwn 4288

p2p_wallet/Scenes/Onboarding/Onboarding.ViewModel.swift, p2p_wallet/Services/AppEventHandler/AppEventHandler.swift
https://p2pvalidator.atlassian.net/browse/PWN-4087
-
=> [PWN-4087] fixed repeated requests for push token registering

p2p_wallet/Scenes/Main/Settings/Settings.ViewController.swift, p2p_wallet/Services/Auth/SocialService/AppleSocialService.swift, p2p_wallet/Services/Auth/SocialService/SocialService.swift
https://p2pvalidator.atlassian.net/browse/PWN-4244
-
=> [PWN-4244] Feature/pwn 4244 Add ability to connect with apple auth and divide to device share + auth share

p2p_wallet/Resources/Base.lproj/Localizable.strings, p2p_wallet/Resources/en.lproj/Localizable.strings, p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/ChoosePhoneCode/ChoosePhoneCodeCoordinator.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/ChoosePhoneCode/ChoosePhoneCodeViewController.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/ChoosePhoneCode/ChoosePhoneCodeViewModel.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/ChoosePhoneCode/SelectableCountry.swift
https://p2pvalidator.atlassian.net/browse/PWN-4248
- empty state
- sort logic
- viewmodel input structure
- mic will be moved to another task
=> [PWN-4248] Add some sort logic and empty cell

Podfile.lock, p2p_wallet/AppCoordinator/AppCoordinator.swift, p2p_wallet/Scenes/StartOnboarding/Continue/ContinueCoordinator.swift, p2p_wallet/Scenes/StartOnboarding/Start/StartCoordinator.swift
https://p2pvalidator.atlassian.net/browse/PWN-4242
- smooth transition
- animation fix in https://github.com/p2p-org/KeyAppUI/pull/33
- remove redundant code
- podfile.lock
=> [PWN-4242] SplashView transition

p2p_wallet/Scenes/StartOnboarding/Start/StartView.swift
- Animation added on onboarding starting page as it was described in figma
https://user-images.githubusercontent.com/6975538/182286519-bb43a430-52ce-4f34-a689-f8ec74d3e9ee.mov
=> feat: Onboarding start animation

Podfile.lock, p2p_wallet/AppCoordinator/AppCoordinator.swift, p2p_wallet/AppDelegate.swift, p2p_wallet/Resources/AppDelegate/AppDelegate+Injection.swift, p2p_wallet/Services/FeatureFlags/DefaultFlags.swift, p2p_wallet/Services/FeatureFlags/Features.swift, p2p_wallet/Services/WarmupService/RemoteConfigWarmup.swift, p2p_wallet/Services/WarmupService/WarmupManager.swift
- Add warm up process. During this time the splash animation will be played.
=> Warm up processing

p2p_wallet/Scenes/StartOnboarding/Start/StartView.swift
=> fix: startview animation

Podfile.lock, p2p_wallet/Scenes/StartOnboarding/Continue/ContinueCoordinator.swift, p2p_wallet/Scenes/StartOnboarding/Start/StartCoordinator.swift, p2p_wallet/Scenes/StartOnboarding/Start/StartView.swift, p2p_wallet/Scenes/StartOnboarding/Start/StartViewModel.swift, p2p_wallet/Scenes/StartOnboarding/StartOnboardingNavigationProvider.swift
https://p2pvalidator.atlassian.net/browse/PWN-4242
- https://p2pvalidator.atlassian.net/browse/PWN-4421
- https://p2pvalidator.atlassian.net/browse/PWN-4424
- https://p2pvalidator.atlassian.net/browse/PWN-4242
Can't be merged without update of Podfile with https://github.com/p2p-org/KeyAppUI/pull/36
=> [PWN-4242] [PWN-4424] [PWN-4421] Start and Continue screens bags

Podfile, Podfile.lock, p2p_wallet/SwiftUI/CoinLogoView.swift, p2p_wallet/UIKit/SwiftUI/TokenCellView.swift, p2p_wallet/UIKit/SwiftUI/TokenImageView.swift
=> Added CoinLogoView

Podfile.lock, p2p_wallet/Extensions/Double+Extensions.swift, p2p_wallet/Scenes/Main/NewHome/Empty/ViewModel/HomeEmptyViewModel.swift, p2p_wallet/Services/PriceAPIs/PricesService.swift
=> [PWN-4463] Fixed Prices cache

Podfile.lock
https://p2pvalidator.atlassian.net/browse/PWN-4451
-
=> [PWN-4451] feat: update color for lime

Podfile.lock
https://p2pvalidator.atlassian.net/browse/PWN-4436
-
=> [PWN-4436] Snackbar update

Podfile.lock, p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/ChoosePhoneCode/ChoosePhoneCodeViewController.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/EnterPhoneNumberViewModel.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/SocialSignIn/SocialSelection/SocialSignInViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-4533
- Podfile.lock needs to be updated after https://github.com/bigearsenal/BEPureLayout/pull/12/files
- other files updated because of swiftlint
=> [PWN-4533] When the country selection screen opens, the search must be active

Podfile.lock, p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/ChoosePhoneCode/ChoosePhoneCodeViewController.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/EnterPhoneNumberViewModel.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/SocialSignIn/SocialSelection/SocialSignInViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-4532
- https://p2pvalidator.atlassian.net/browse/PWN-4532
- Watch after https://github.com/p2p-org/p2p-wallet-ios/pull/390
=> [PWN-4532] There is no OK button on the country selection screen

Podfile.lock, p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/BindingPhoneNumberDelegatedCoordinator.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/ChoosePhoneCode/ChoosePhoneCodeViewController.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/ChoosePhoneCode/ChoosePhoneCodeViewModel.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/EnterPhoneNumberViewModel.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/SocialSignIn/SocialSelection/SocialSignInViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-4530
- https://p2pvalidator.atlassian.net/browse/PWN-4530
- https://p2pvalidator.atlassian.net/browse/PWN-4531
- After https://github.com/bigearsenal/BEPureLayout/pull/12 and https://github.com/p2p-org/p2p-wallet-ios/pull/391
=> [PWN-4530] [PWN-4531] The currently selected country should be displayed at the top of the list

p2p_wallet/Scenes/Main/NewHome/HomeWithTokens/View/HomeWithTokensView.swift
https://p2pvalidator.atlassian.net/browse/PWN-4364
-
=> [PWN-4364] Feature/pwn 4364 hide token animation

p2p_wallet/Scenes/Main/SendToken/Subscenes/ChooseRecipientAndNetwork/SelectAddress/SendToken.ChooseRecipientAndNetwork.SelectAddress.ViewModel.swift, p2p_wallet/Scenes/Main/SendToken/Subscenes/ChooseRecipientAndNetwork/SelectAddress/Subviews/RecipientsCollectionView/SendToken.ChooseRecipientAndNetwork.SelectAddress.RecipientsListViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-4316
-
=> [PWN-4316] Do not search for a name with direct address

p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/CreateWallet.ExplanationVC.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/CreateWallet.ViewModel.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/CreateWallet.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/RestoreWallet.ViewController.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/RestoreWallet.ViewModel.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/RestoreWallet.swift
https://p2pvalidator.atlassian.net/browse/PWN-4367
-
=> [PWN-4367] Skip the step of creating a username (old flow)

p2p_wallet/AppCoordinator/AppCoordinator.swift
=> Removed global reachability check

p2p_wallet/Resources/Base.lproj/Localizable.strings, p2p_wallet/Resources/en.lproj/Localizable.strings, p2p_wallet/Scenes/Main/Home/Subviews/Home.EmptyView.swift, p2p_wallet/Scenes/Main/NewHome/Empty/View/HomeEmptyView.swift, p2p_wallet/Scenes/Main/NewHome/HomeWithTokens/View/TokenDetailActionView.swift, p2p_wallet/Scenes/Main/Settings/Subscenes/Settings.UsernameViewController.swift
https://p2pvalidator.atlassian.net/browse/PWN-4547
-
=> [PWN-4547] Main screen changing the text on the screen

p2p_wallet/Resources/Base.lproj/LaunchScreen.storyboard, p2p_wallet/UIKit/SwiftUI/BottomActionContainerStyle.swift
https://p2pvalidator.atlassian.net/browse/PWN-4550
- The bottom panel on the start screen does not match the design https://p2pvalidator.atlassian.net/browse/PWN-4556
- When the app is first started, the yellow screen is displayed first https://p2pvalidator.atlassian.net/browse/PWN-4550
=> [PWN-4550] [PWN-4556] 

Podfile.lock, p2p_wallet/AppCoordinator/AppCoordinator.swift
=> [NO-TASK] Use new splash API for stop animation

p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/EnterSMSCode/EnterSMSCodeViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-4552
-
=> [PWN-4552] Button appear interval

p2p_wallet/Scenes/Main/NewHome/Empty/View/HomeEmptyView.swift
https://p2pvalidator.atlassian.net/browse/PWN-4547
-
=> [PWN-4547] Fix fixed label width

p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/ChoosePhoneCode/ChoosePhoneCodeViewController.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/ChoosePhoneCode/ChoosePhoneCodeViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-4530
-
=> [PWN-4530] On the country selection screen, the currently selected country should be displayed at the top of the list

Podfile.lock, p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/EnterSMSCode/EnterSMSCodeViewModel.swift
=> UI Fixes for OTP

p2p_wallet/Scenes/CreateOrRestoreWallet/Common/Pincode/Pincode/PincodeSnackbar.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/Common/Pincode/Pincode/PincodeViewController.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/Common/Pincode/Pincode/PincodeViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-4642
- Podfile.lock needs to be updated after https://github.com/p2p-org/KeyAppUI/pull/41
=> [PWN-4642] Reset pincode after failure

Podfile.lock, p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/ChoosePhoneCode/ChoosePhoneCodeViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-4609
- https://p2pvalidator.atlassian.net/browse/PWN-4609
=> [PWN-4609] On the country selection screen, after using the search, the selected country doesn't display at the top of the list

Podfile.lock, p2p_wallet/Resources/Base.lproj/Localizable.strings, p2p_wallet/Resources/en.lproj/Localizable.strings, p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/RestoreWalletCoordinator.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/ChooseRestoreOption/ChooseRestoreOptionParameters.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/ChooseRestoreOption/ChooseRestoreOptionView.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/ChooseRestoreOption/ChooseRestoreOptionViewModel.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/RestoreCustom/RestoreCustomDelegateCoordinator.swift
https://p2pvalidator.atlassian.net/browse/PWN-4371
=> [PWN-4371] OTP not delivered error

p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/BindingPhoneNumberDelegatedCoordinator.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/ChoosePhoneCode/ChoosePhoneCodeCoordinator.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/ChoosePhoneCode/ChoosePhoneCodeViewController.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/ChoosePhoneCode/ChoosePhoneCodeViewModel.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/EnterPhoneNumberViewModel.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/RestoreCustom/RestoreCustomDelegateCoordinator.swift
https://p2pvalidator.atlassian.net/browse/PWN-4737
-
=> [PWN-4743]: The country selected by default does not have a check mark and does not be the first in the list

p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/EnterPhoneNumberViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-4741
-
=> [PWN-4741]: The error "Sorry, we don’t know a such country " is displayed after restarting the app on the phone number screen

Podfile.lock, p2p_wallet/Scenes/CreateOrRestoreWallet/Common/Pincode/Pincode/PincodeViewController.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/BaseOTPViewController.swift, p2p_wallet/Services/NotificationsService/NotificationService.swift
https://p2pvalidator.atlassian.net/browse/PWN-4706
-
=> [PWN-4706] fix: SnackBar

p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/EnterPhoneNumberViewController.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/EnterSMSCode/EnterSMSCodeViewController.swift
https://p2pvalidator.atlassian.net/browse/PWN-4766
=> [PWN-4766] PWN-4766: The “Continue“ button does not appear correctly via going to the code entry screen/returning back

p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/EnterPhoneNumberViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-4777
-
=> [PWN-4777] PWN-4777: After selecting a country the flag of another country with the same code is displayed on the number entry screen

p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/ChoosePhoneCode/SelectableCountry.swift
https://p2pvalidator.atlassian.net/browse/PWN-4772
-
=> [PWN-4772] PWN-4772: Countries should be sorted alphabetically, not in order of country codes when searching

p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/ChoosePhoneCode/ChoosePhoneCodeViewController.swift
https://p2pvalidator.atlassian.net/browse/PWN-4758
-
=> [PWN-4758] PWN-4758: The countries at the end of the list are hidden behind the keyboard on the search country screen

p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/ChoosePhoneCode/ChoosePhoneCodeViewController.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/ChoosePhoneCode/ChoosePhoneCodeViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-4773
The screen jumps via selecting countries with the keyboard open and closed
-
=> [PWN-4773] PWN-4773: The screen jumps via selecting countries

p2p_wallet/Scenes/CreateOrRestoreWallet/Common/Pincode/Pincode/PincodeViewController.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/EnterPhoneNumberViewController.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/EnterSMSCode/EnterSMSCodeViewController.swift
https://p2pvalidator.atlassian.net/browse/PWN-4612
-
=> [PWN-4612] Left and right margins to the "?" button and the “back” arrow are different on all screens

p2p_wallet/Coordinators/AppCoordinator/AppCoordinator.swift
https://p2pvalidator.atlassian.net/browse/PWN-4750
-
=> [PWN-4750] Need to remove the old pin code entry screen from the creation wallet scenario 

p2p_wallet/Scenes/CreateOrRestoreWallet/Common/StateMachineProvider/OnboardingStateMachineProvider.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/CreateWalletViewModel.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/RestoreWalletViewModel.swift
=> [NO-TASK] OnboardingStateMachineProvider to create tKeyFacade and apiGatewayClient

p2p_wallet/Scenes/CreateOrRestoreWallet/Common/SocialSelection/SocialSignInViewModel.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/RestoreWalletCoordinator.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/ChooseRestoreOption/ChooseRestoreOptionView.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/ChooseRestoreOption/ChooseRestoreOptionViewModel.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/RestoreCustom/RestoreCustomDelegateCoordinator.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/RestoreSocial/RestoreSocialDelegatedCoordinator.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/RestoreSocialOption/RestoreSocialOptionViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-4889
- https://p2pvalidator.atlassian.net/browse/PWN-4889
- https://p2pvalidator.atlassian.net/browse/PWN-4891
After https://github.com/p2p-org/KeyAppUI/pull/42 podfile should be updated
=> [PWN-4889] [PWN-4891] 

p2p_wallet/Scenes/CreateOrRestoreWallet/Common/Pincode/Pincode/PincodeViewController.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/EnterPhoneNumberViewController.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/EnterSMSCode/EnterSMSCodeViewController.swift
https://p2pvalidator.atlassian.net/browse/PWN-4912
https://p2pvalidator.atlassian.net/browse/PWN-4879
-
=> [PWN-4912][PWN-4879] Toasts are too low in PincodeViewController, Keyboard animation fix

p2p_wallet/Scenes/Main/Settings/Subscenes/RecoveryKit/RecoveryKitView.swift
https://p2pvalidator.atlassian.net/browse/PWN-4898
-
=> [PWN-4898] Wallet protection screen ui bugs

p2p_wallet/Scenes/CreateOrRestoreWallet/OnboardingConfig.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/RestoreWalletViewModel.swift, p2p_wallet/Scenes/DebugMenu/View/DebugMenuView.swift, p2p_wallet/Scenes/DebugMenu/ViewModel/DebugMenuViewModel.swift
=> [NO-TASK] Add device share to debug menu

p2p_wallet/Models/AuthenticationPresentationStyle.swift, p2p_wallet/Scenes/Main/Main.ViewController.swift, p2p_wallet/Scenes/Main/Settings/Subscenes/PincodeChange/PincodeChangeStartView.swift, p2p_wallet/Scenes/Main/Settings/Subscenes/SeedPhraseDetail/SeedPhraseDetailView.swift, p2p_wallet/Scenes/Main/Settings/Subscenes/SeedPhraseDetail/SeedPhraseDetailViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-4901
- depends on https://github.com/p2p-org/KeyAppUI/pull/43
=> [PWN-4901] Slider "Show my seed phrase" bugs

Podfile, Podfile.lock, p2p_wallet/Scenes/Main/Settings/Subscenes/PincodeChange/PincodeVerifyView.swift
https://p2pvalidator.atlassian.net/browse/PWN-4947
-
=> [PWN-4947] feat: add delay and reset pincode after failure

p2p_wallet/Scenes/Main/Settings/Subscenes/SeedPhraseDetail/SeedPhraseDetailViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-4899
-
=> [PWN-4899] Seed phrase details screen ui bugs

p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/CreateWalletCoordinator.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/RestoreWalletCoordinator.swift, p2p_wallet/Scenes/StartOnboarding/Start/StartCoordinator.swift
https://p2pvalidator.atlassian.net/browse/PWN-4911
- https://p2pvalidator.atlassian.net/browse/PWN-4911
=> [PWN-4911] Crash while going from creation to restore

Podfile, Podfile.lock, p2p_wallet/AppDelegate.swift, p2p_wallet/Coordinators/TabBar/ActionsCoordinator.swift, p2p_wallet/Coordinators/TabBar/HomeCoordinator.swift, p2p_wallet/Coordinators/TransactionDetailsCoordinator.swift, p2p_wallet/Scenes/Main/Buy/BuyCoordinator.swift, p2p_wallet/Scenes/Main/Buy/BuyViewModel.swift, p2p_wallet/Services/Logger/LogManagerProvider.swift
https://p2pvalidator.atlassian.net/browse/PWN-4788
-
=> [PWN-4788] && [PWN-4959]

p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/RestoreCustom/RestoreCustomDelegateCoordinator.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/RestoreSocial/RestoreSocialDelegatedCoordinator.swift
https://p2pvalidator.atlassian.net/browse/PWN-4980
https://p2pvalidator.atlassian.net/browse/PWN-4981
https://p2pvalidator.atlassian.net/browse/PWN-4969
-
=> [PWN-4980] [PWN-4981] [PWN-4969] States when shares don't match or exist

p2p_wallet/Scenes/Main/Buy/BuyViewModel.swift
=> Clear form

p2p_wallet/Scenes/CreateOrRestoreWallet/Common/SocialSelection/SocialSignInView.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/ChooseRestoreOption/ChooseRestoreOptionView.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/RestoreSocialOption/RestoreSocialOptionView.swift
https://p2pvalidator.atlassian.net/browse/PWN-4962
-
=> [PWN-4962] Remove disable state from onboarding screens

p2p_wallet/Scenes/CreateOrRestoreWallet/Common/Pincode/Pincode/PincodeViewController.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/CreateWalletCoordinator.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/BindingPhoneNumberDelegatedCoordinator.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/EnterPhoneNumberViewController.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/EnterSMSCode/EnterSMSCodeViewController.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/RestoreWalletCoordinator.swift
https://p2pvalidator.atlassian.net/browse/PWN-4974
-
=> [PWN-4974] Restore flow titles

p2p_wallet/Scenes/Main/Settings/Subscenes/SeedPhraseDetail/SeedPhraseDetailView.swift
https://p2pvalidator.atlassian.net/browse/PWN-4899
-
=> [PWN-4899] PWN-4899 && PWN-4900

Podfile.lock, p2p_wallet/Info.plist, p2p_wallet/Scenes/CreateOrRestoreWallet/Common/StateMachineProvider/OnboardingStateMachineProvider.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/OnboardingConfig.swift, p2p_wallet/Scenes/DebugMenu/View/DebugMenuView.swift
https://p2pvalidator.atlassian.net/browse/PWN-4911
-
=> [PWN-4911] Apply new tKey API

p2p_wallet/Coordinators/AppCoordinator/AppCoordinator.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/CreateWalletCoordinator.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/RestoreWalletCoordinator.swift
https://p2pvalidator.atlassian.net/browse/PWN-4989
-
=> [PWN-4989] Start screen is blinking while opening the main screen

p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/BaseOTPViewController.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/OnboardingService.swift
https://p2pvalidator.atlassian.net/browse/PWN-4955
- https://p2pvalidator.atlassian.net/browse/PWN-4955
=> [PWN-4955] Validate create wallet lastState

p2p_wallet/Scenes/CreateOrRestoreWallet/Common/Pincode/BiometricsAuthProvider.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/Common/Pincode/Pincode/PincodeViewController.swift, p2p_wallet/Scenes/Main/Settings/Settings.ViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-5154
- https://p2pvalidator.atlassian.net/browse/PWN-5154
- https://p2pvalidator.atlassian.net/browse/PWN-5155
=> [PWN-5154] [PWN-5155] Remove fallback button for biometrics check

p2p_wallet/Scenes/CreateOrRestoreWallet/Common/Pincode/BiometricsAuthProvider.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/Common/Pincode/Pincode/PincodeViewModel.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/ICloudRestore/ICloudRestore/ICloudRestoreScreen.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/ICloudRestore/ICloudRestore/ICloudRestoreViewModel.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/ICloudRestore/RestoreICloudDelegatedCoordinator.swift
https://p2pvalidator.atlassian.net/browse/PWN-5150
https://p2pvalidator.atlassian.net/browse/PWN-5150
=> [PWN-5150] Add biometry check on iCloud restore. Refactoring of coordinatorIO

p2p_wallet/Scenes/CreateOrRestoreWallet/Common/ICloud/BaseICloudRestoreViewModel.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/RestoreWalletCoordinator.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/ChooseRestoreOption/ChooseRestoreOptionViewModel.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/ICloudRestore/ICloudRestore/ICloudRestoreViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-4841
- https://github.com/p2p-org/key-app-kit-swift/pull/38
- https://p2pvalidator.atlassian.net/browse/PWN-4841
=> [PWN-4841] Change logic of iCloud restore if only one account is stored

p2p_wallet/Coordinators/AppCoordinator/AppCoordinator.swift, p2p_wallet/Resources/Base.lproj/LaunchScreen.storyboard
https://p2pvalidator.atlassian.net/browse/PWN-5110
-
=> [PWN-5110] Change start animation screen

p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/ChoosePhoneCode/ChoosePhoneCodeViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-5158
- filtered result in case of empty phrase
=> [PWN-5158] feat: filteredAndSorted

Podfile.lock, p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/BindingPhoneNumberDelegatedCoordinator.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/ChoosePhoneCode/ChoosePhoneCodeCoordinator.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/ChoosePhoneCode/ChoosePhoneCodeViewController.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/ChoosePhoneCode/ChoosePhoneCodeViewModel.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/ChoosePhoneCode/SelectableCountry.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/EnterPhoneNumberViewModel.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/RestoreCustom/RestoreCustomDelegateCoordinator.swift
=> [PWN-5185] Phone fixes

p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/EnterSMSCode/EnterSMSCodeViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-5123
- https://p2pvalidator.atlassian.net/browse/PWN-5123
=> [PWN-5123] Fire timer immediately

p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/ChooseRestoreOption/ChooseRestoreOptionViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-4841
-
=> [PWN-4841] Fix infinite loader if biometry is failed

Podfile.lock, p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/EnterPhoneNumberViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-5239
-
=> [PWN-5239] Fix/pwn 5239

p2p_wallet/Scenes/CreateOrRestoreWallet/Common/Pincode/SecuritySetupDelegatedCoordinator.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/EnterPhoneNumberViewController.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/EnterPhoneNumberViewModel.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/SocialSignIn/SocialSignInDelegatedCoordiantor.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/RestoreWalletCoordinator.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/ICloudRestore/RestoreICloudDelegatedCoordinator.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/RestoreCustom/RestoreCustomDelegateCoordinator.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/RestoreSocial/RestoreSocialDelegatedCoordinator.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/SeedPhraseRestore/RestoreSeedPhraseDelegatedCoordinator.swift
https://p2pvalidator.atlassian.net/browse/PWN-4640
-
=> [PWN-4640] Add intercom in the flow of creating and restoring

p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/CreateWalletCoordinator.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/SeedPhraseRestore/SeedPhraseRestore/SeedPhraseRestoreWalletView.swift, p2p_wallet/Scenes/StartOnboarding/Continue/ContinueCoordinator.swift, p2p_wallet/Scenes/StartOnboarding/Start/StartCoordinator.swift
https://p2pvalidator.atlassian.net/browse/PWN-5246
- https://p2pvalidator.atlassian.net/browse/PWN-5246
- https://p2pvalidator.atlassian.net/browse/PWN-5247
=> [PWN-5246] [PWN-5247] Navigation and UI fixes

p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/BindingPhoneNumberDelegatedCoordinator.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/RestoreCustom/RestoreCustomDelegateCoordinator.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/Screen/OnboardingBlockScreen.swift
https://p2pvalidator.atlassian.net/browse/PWN-5250
- https://p2pvalidator.atlassian.net/browse/PWN-5250
=> [PWN-5250] Info button on OnboardingBlockScreen

p2p_wallet/Scenes/CreateOrRestoreWallet/Common/Pincode/SecuritySetupDelegatedCoordinator.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/BindingPhoneNumberDelegatedCoordinator.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/RestoreCustom/RestoreCustomDelegateCoordinator.swift, p2p_wallet/Scenes/Main/Main.ViewController.swift, p2p_wallet/Scenes/Main/Settings/Subscenes/PincodeChange/PincodeChangeCoordinator.swift, p2p_wallet/Scenes/Main/Settings/Subscenes/PincodeChange/PincodeVerifyView.swift
https://p2pvalidator.atlassian.net/browse/PWN-4640
-
=> [PWN-4640] Added Intercom

p2p_wallet/Scenes/Main/InvestSolend/InvestSolendView.swift, p2p_wallet/Scenes/Main/InvestSolend/InvestSolendViewModel.swift, p2p_wallet/Scenes/Main/InvestSolend/Tutorial/SolendTutorialView.swift, p2p_wallet/Scenes/TabBar/TabBarController.swift
=> feat: show SolendTutorial on TabBar

p2p_wallet/Analytics/AmplitudeEvent/AmplitudeEvent.swift, p2p_wallet/Analytics/AmplitudeEvent/AmplitudeIdentifier.swift, p2p_wallet/Scenes/Main/NewHome/Home/ViewModel/HomeViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-4809
-
=> [PWN-4809] Positive balance mark

p2p_wallet/Analytics/AmplitudeEvent/AmplitudeEvent.swift, p2p_wallet/Coordinators/AppCoordinator/AppCoordinator.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/ChooseRestoreOption/ChooseRestoreOptionViewModel.swift, p2p_wallet/Scenes/StartOnboarding/Start/StartViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-5222
-
=> [PWN-5222] Onboarding analytics

p2p_wallet/Scenes/CreateOrRestoreWallet/Common/Pincode/Pincode/PincodeViewController.swift, p2p_wallet/Scenes/Main/Settings/Subscenes/PincodeChange/ForgetPinView.swift
https://p2pvalidator.atlassian.net/browse/PWN-5230
-
=> [PWN-5230] feat: fix Panel's height

p2p_wallet/Scenes/CreateOrRestoreWallet/Common/Pincode/Pincode/PincodeViewController.swift
https://p2pvalidator.atlassian.net/browse/PWN-5255
-
=> [PWN-5255] Changed x to < on PIN screen

p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/EnterSMSCode/EnterSMSCodeViewController.swift
https://p2pvalidator.atlassian.net/browse/PWN-5269
- https://p2pvalidator.atlassian.net/browse/PWN-5269
=> [PWN-5269] Open keyboard if OTP code is incorrect

Podfile, Podfile.lock, p2p_wallet/Resources/AppDelegate/AppDelegate+Injection.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/Common/SocialAuthService/AuthServiceBridge.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/Common/SocialAuthService/JWTTokenValidator.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/CreateWalletViewModel.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/ChoosePhoneCode/ChoosePhoneCodeViewModel.swift, p2p_wallet/Services/Auth/SocialService/AppleSocialService.swift, p2p_wallet/Services/GlobalWebView.swift
=> Remove JWT lib

p2p_wallet/Scenes/CreateOrRestoreWallet/OnboardingConfig.swift, p2p_wallet/Services/Auth/SocialService/SocialService.swift, p2p_wallet/Services/Environment.swift
=> Consider test environment as release, not debug

p2p_wallet/Scenes/DebugMenu/ViewModel/DebugMenuViewModel.swift, p2p_wallet/Scenes/TabBar/TabBarController.swift, p2p_wallet/Services/FeatureFlags/Features.swift
https://p2pvalidator.atlassian.net/browse/PWN-5015
-
=> [PWN-5015] Добавление feature-toggle

p2p_wallet/Resources/Colors.xcassets/lightSea.colorset/Contents.json, p2p_wallet/Scenes/Main/InvestSolend/SolendTransactionDetails/SolendTransactionDetailsView.swift, p2p_wallet/SwiftUI/Spinner/Spinner.swift
=> spinner appended

p2p_wallet/Scenes/Main/InvestSolend/DepositWithdraw/DepositSolendView.swift
=> Deposit animation

p2p_wallet/Resources/Base.lproj/Localizable.strings, p2p_wallet/Resources/en.lproj/Localizable.strings, p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/ChooseRestoreOption/ChooseRestoreOptionView.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/RestoreCustom/RestoreCustomDelegateCoordinator.swift
https://p2pvalidator.atlassian.net/browse/PWN-5407
-
=> [PWN-5407] Onboarding texts

p2p_wallet/Services/Storage/KeychainStorage.swift
https://p2pvalidator.atlassian.net/browse/PWN-5409
-
=> [PWN-5409] feat: safely migrate from iCloud keychain to localKeychain

p2p_wallet/Scenes/Main/InvestSolend/DepositWithdraw/DepositSolendViewModel.swift
=> Solend fee fix

p2p_wallet/Scenes/StartOnboarding/Start/StartCoordinator.swift
- I once caught a problem which Alena was talking about. I think it was because of strong self when we have last state from StartCoordinator. I don't know the exact steps but it might help to fix it. I have not caught it since and Alena will check it on Monday
=> [PWN-5456] Onboarding. Fix of start coordinator

Podfile.lock, p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/EnterSMSCode/EnterSMSCodeViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-5459
-
=> [PWN-5459] Ceil date to display the correct timeout

p2p_wallet/Analytics/AmplitudeEvent/AmplitudeEvent.swift, p2p_wallet/Scenes/Main/Buy/Buy.PaymentType.swift, p2p_wallet/Scenes/Main/Buy/BuyCoordinator.swift, p2p_wallet/Scenes/Main/Buy/BuyViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-5043
-
=> [PWN-5043] Несоответствие передаваемых метрик и параметров экрана Buy с документацией

p2p_wallet/Scenes/Main/SendToken/SendTokenCoordinator.swift
https://p2pvalidator.atlassian.net/browse/PWN-3962
-
=> [PWN-3962] fix(send-coordinator): pop old view controllers

.githooks/pre-commit, Podfile.lock, p2p_wallet/Coordinators/SolendDepositsCoordinator.swift, p2p_wallet/Coordinators/TabBar/SolendCoordinator.swift, p2p_wallet/Extensions/Double+Extensions.swift, p2p_wallet/Resources/Base.lproj/Localizable.strings, p2p_wallet/Resources/en.lproj/Localizable.strings, p2p_wallet/Resources/fr.lproj/Localizable.strings, p2p_wallet/Resources/ru.lproj/Localizable.strings, p2p_wallet/Resources/vi.lproj/Localizable.strings, p2p_wallet/Scenes/Main/InvestSolend/Banner/View/Banners/SolendErrorBannerView.swift, p2p_wallet/Scenes/Main/InvestSolend/Banner/ViewModel/InvestSolendBannerViewModel.swift, p2p_wallet/Scenes/Main/InvestSolend/DepositWithdraw/DepositSolendViewModel.swift, p2p_wallet/Scenes/Main/InvestSolend/InvestSolendViewModel.swift, p2p_wallet/Scenes/Main/InvestSolend/SelectToken/TokenToDeposit/TokenToDepositView.swift, p2p_wallet/Scenes/Main/InvestSolend/SelectToken/TokenToWithdraw/TokenToWithdrawView.swift, p2p_wallet/Scenes/Main/InvestSolend/TopUpForContinue/CurrentVersion/SolendTopUpForContinueView.swift, p2p_wallet/Scenes/Main/InvestSolend/TopUpForContinue/ViewModel/SolendTopUpForContinueViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-5412
PWN-5452: Не отображаются значения APY у пользователей без депозитов
-
=> [PWN-5412] PWN-5412: Нету токена в шторке без депозитов

p2p_wallet/Extensions/String+Extensions.swift, p2p_wallet/Scenes/Main/InvestSolend/DepositWithdraw/DepositSolendViewModel.swift, p2p_wallet/Scenes/Main/InvestSolend/Deposits/SolendDepositsViewModel.swift, p2p_wallet/Scenes/Main/InvestSolend/InvestSolendCell.swift
https://p2pvalidator.atlassian.net/browse/PWN-5485
-
=> [PWN-5485] APY format fix

p2p_wallet/SwiftUI/CoinLogoView.swift
=> Coin logo fix

p2p_wallet/Scenes/Main/InvestSolend/DepositWithdraw/DepositSolendViewModel.swift, p2p_wallet/Scenes/Main/InvestSolend/DepositWithdraw/Views/DepositWithdrawInputView.swift
https://p2pvalidator.atlassian.net/browse/PWN-5484
-
=> [PWN-5484] Fix/pwn 5484

p2p_wallet/Scenes/Main/NewHome/HomeWithTokens/ViewModel/HomeWithTokensViewModel.swift
=> crash fixed

project.yml
=> release: bump version to 1.13.0

p2p_wallet/Coordinators/AppCoordinator/AppCoordinator.swift
=> [PWN-5429] Fix actor isolated method call

p2p_wallet/Coordinators/AppCoordinator/AppCoordinator.swift, p2p_wallet/Scenes/Main/Settings/Settings.ViewController.swift, p2p_wallet/Scenes/Username/CreateUsername/CreateUsernameCoordinator.swift, p2p_wallet/Scenes/Username/CreateUsername/CreateUsernameView.swift, p2p_wallet/Scenes/Username/CreateUsername/CreateUsernameViewModel.swift, p2p_wallet/Services/CreateName/CreateNameService.swift
https://p2pvalidator.atlassian.net/browse/PWN-5601
-
=> [PWN-5601] Apply validation to username and fix logic of create name requests

p2p_wallet/Services/AppEventHandler/AppEventHandler.swift
https://p2pvalidator.atlassian.net/browse/PWN-5429
-
=> [PWN-5429] Fix environment issue

Podfile.lock, p2p_wallet/Coordinators/TabBar/SolendCoordinator.swift, p2p_wallet/Scenes/Main/InvestSolend/DepositWithdraw/DepositSolendViewModel.swift, p2p_wallet/Scenes/Main/InvestSolend/Placeholder/SolendPlaceholderView.swift, p2p_wallet/Scenes/TabBar/TabBarController.swift
=> [PWN-5598] Fixes

p2p_wallet/Scenes/DebugMenu/ViewModel/DebugMenuViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-5429
-
=> [PWN-5429] Add FT to debug menu

p2p_wallet/Coordinators/AppCoordinator/AppCoordinator.swift, p2p_wallet/Scenes/Main/NewHome/Home/ViewModel/HomeViewModel.swift, p2p_wallet/Scenes/Main/NewSettings/Settings/ViewModel/SettingsViewModel.swift, p2p_wallet/Services/CreateName/CreateNameService.swift
https://p2pvalidator.atlassian.net/browse/PWN-5429
-
=> [PWN-5429] [PWN-5554] Update username on main screen if it was initiated from settings

Podfile, Podfile.lock, p2p_wallet/AppDelegate.swift, p2p_wallet/Info.plist, p2p_wallet/Scenes/Main/Buy/BuyViewModel.swift, p2p_wallet/p2p_wallet.entitlements
https://p2pvalidator.atlassian.net/browse/PWN-5466
-
=> [PWN-5466] Apps Flyer integration

p2p_wallet/Scenes/Main/History/History.SceneModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-5596
-
=> [PWN-5596] fix(history): wrong trxInfo mapping

p2p_wallet/Scenes/Main/NewHome/HomeWithTokens/View/HomeWithTokensView.swift
https://p2pvalidator.atlassian.net/browse/PWN-5625
-
=> [PWN-5625] Убрать баннеры

p2p_wallet/Scenes/StartOnboarding/Start/StartViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-5662
- Resources are not deleted in case of their need later
=> [PWN-5662] Remove solend page from onboarding

p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/EnterPhoneNumberViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-5652
I took PhoneNumberKit.defaultRegionCode() method and rewrote it to filter empty mobileNetworkCode values from serviceSubscriberCellularProviders. It returned some empty values I did not understand where are they from. But now they are filtered by https://developer.apple.com/documentation/coretelephony/ctcarrier/1620324-mobilenetworkcode
but in ios 16 this method is deprecated, need to be reconsidered after release I guess
=> [PWN-5652] Get sim card mobile region code

p2p_wallet/Services/Storage/UserWalletManager.swift
=> fix(notification): register device after onboarding

p2p_wallet/Analytics/AmplitudeEvent/AmplitudeEvent.swift, p2p_wallet/Analytics/AmplitudeEvent/AmplitudeIdentifier.swift, p2p_wallet/Coordinators/AppCoordinator/AppCoordinator.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/BindingPhoneNumberDelegatedCoordinator.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/SocialSignIn/SocialSignInDelegatedCoordiantor.swift, p2p_wallet/Scenes/StartOnboarding/StartOnboardingNavigationProvider.swift, p2p_wallet/Scenes/Username/CreateUsername/CreateUsernameCoordinator.swift, p2p_wallet/Scenes/Username/CreateUsername/CreateUsernameView.swift, p2p_wallet/Scenes/Username/CreateUsername/CreateUsernameViewModel.swift, p2p_wallet/Scenes/Username/CreateUsername/Models/CreateUsernameParameters.swift
https://p2pvalidator.atlassian.net/browse/PWN-5660
-
=> [PWN-5660] Fix skip button disappearance and Add Metrics to Amplitude (Onboarding)

p2p_wallet/Scenes/Main/SendToken/Subscenes/ChooseRecipientAndNetwork/SelectAddress/Subviews/RecipientsCollectionView/SendToken.ChooseRecipientAndNetwork.SelectAddress.RecipientsListViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-5674
-
=> [PWN-5674] fix(send): no fund problem

p2p_wallet/Coordinators/AppCoordinator/AppCoordinator.swift
https://p2pvalidator.atlassian.net/browse/PWN-5690
-
=> [PWN-5690] Turn off create wallet flag after opening create name screen

Podfile.lock
https://p2pvalidator.atlassian.net/browse/PWN-5697
-
=> [PWN-5697] Fix history

p2p_wallet/Scenes/Main/Main.ViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-5728
-
=> [PWN-5728] feat(name-service): update everytime when app was loaded

p2p_wallet/Scenes/Main/NewHome/Home/ViewModel/HomeViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-5716
-
=> [PWN-5716] Add .key when copy name on main screen

p2p_wallet/Coordinators/AppCoordinator/AppCoordinator.swift, p2p_wallet/Scenes/Main/NewSettings/Settings/ViewModel/SettingsViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-5718
-
=> [PWN-5718] Fix inconsistent state of biometry toggle

p2p_wallet/Scenes/Main/Buy/BuyViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-5731
-
=> [PWN-5731] Fix/pwn 5731 Default payment method

Podfile.lock, p2p_wallet/Scenes/Main/ReceiveToken/Bitcoin/ReceiveToken.ReceiveBitcoinView.swift, p2p_wallet/Scenes/Main/ReceiveToken/Bitcoin/ReceiveToken.ReceiveBitcoinViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-5723
-
=> [PWN-5723] feat: dynamic minimum transaction amount on receiving btc

Podfile, Podfile.lock
https://p2pvalidator.atlassian.net/browse/PWN-5727
-
=> [PWN-5727] feat: support legacy bitcoin address

p2p_wallet/Scenes/Main/History/Transaction/ViewModel/TransactionViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-5748
-
=> [PWN-5748] Username with postfix

p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/SeedPhraseRestore/SeedPhraseRestore/SeedPhraseRestoreWalletViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-5763
-
=> [PWN-5763] feat(onboarding): trim seed phrase

Podfile, Podfile.lock, p2p_wallet/Scenes/DebugMenu/View/DebugMenuView.swift, p2p_wallet/Scenes/Main/History/History.SceneModel.swift, p2p_wallet/Scenes/Main/History/SourceStream/History.AccountStreamSource.swift, p2p_wallet/Scenes/Main/History/SourceStream/History.MultipleStreamsSource.swift, p2p_wallet/Services/GlobalAppState.swift, p2p_wallet/Services/Storage/KeychainStorage+AccountStorageType.swift
https://p2pvalidator.atlassian.net/browse/PWN-5762
-
=> [PWN-5762] Feature/pwn 5762

p2p_wallet/Scenes/Main/Main.ViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-5728
-
=> [PWN-5728] fix(name-service): remove old name

p2p_wallet/Scenes/Main/Buy/BuyInputOutputView.swift
https://p2pvalidator.atlassian.net/browse/PWN-5759
-
=> [PWN-5759] Added moonpay crypto format

p2p_wallet/Extensions/SolanaSDK.Wallet+Extensions.swift, p2p_wallet/Scenes/Main/NewHome/HomeWithTokens/View/HomeWithTokensView.swift
https://p2pvalidator.atlassian.net/browse/PWN-5760
-
=> [PWN-5760] Hide SOL on main screen

p2p_wallet/Scenes/Main/History/History.ErrorView.swift, p2p_wallet/Scenes/Main/History/Transaction/View/TransactionView.swift, p2p_wallet/Scenes/Main/ProcessTransaction/Status/ProcessTransaction.Status.ViewController.swift, p2p_wallet/Scenes/Main/ReceiveToken/NetworkSelection/ConfirmReceivingBitcoin/ConfirmReceivingBitcoin.ViewController+CreateRenBTC.swift, p2p_wallet/Scenes/Main/ReceiveToken/NetworkSelection/ConfirmReceivingBitcoin/ConfirmReceivingBitcoin.ViewController+CreateRenBTCFree.swift, p2p_wallet/Scenes/Main/ReceiveToken/NetworkSelection/ConfirmReceivingBitcoin/ConfirmReceivingBitcoin.ViewController+TopUp.swift, p2p_wallet/Scenes/Main/SendToken/Subscenes/ChooseRecipientAndNetwork/SelectAddress/SendToken.ChooseRecipientAndNetwork.SelectAddress.RootView.swift, p2p_wallet/Scenes/Main/SendToken/Subscenes/ChooseRecipientAndNetwork/SelectAddress/Subviews/SendToken.ChooseRecipientAndNetwork.SelectAddress.RecipientView.swift, p2p_wallet/Scenes/Main/SendToken/Subscenes/ChooseTokenAndAmount/SendToken.ChooseTokenAndAmount.RootView.swift, p2p_wallet/Scenes/Main/SendToken/Subscenes/Confirm/SendToken.ConfirmViewController.swift, p2p_wallet/Scenes/Main/SwapToken/OrcaSwapV2/ConfirmSwapping/OrcaSwapV2.ConfirmSwapping.RootView.swift, p2p_wallet/Scenes/Main/SwapToken/OrcaSwapV2/OrcaSwapV2.RootView.swift
https://p2pvalidator.atlassian.net/browse/PWN-5784
- https://p2pvalidator.atlassian.net/browse/PWN-5784
=> [PWN-5784] Use onPressed with button design component

p2p_wallet/Extensions/SwiftUI/Refreshable/RefreshableModifier.swift
https://p2pvalidator.atlassian.net/browse/PWN-5658
-
=> [PWN-5658] fix: refreshable for ios 15

p2p_wallet/Scenes/Main/SwapToken/OrcaSwapV2/Subviews/OrcaSwapV2.WalletView.swift
https://p2pvalidator.atlassian.net/browse/PWN-5789
- https://p2pvalidator.atlassian.net/browse/PWN-5789
=> [PWN-5789] Update question mark tint color

p2p_wallet/Scenes/Main/SendToken/Subscenes/ChooseRecipientAndNetwork/SelectAddress/SendToken.ChooseRecipientAndNetwork.SelectAddress.RootView.swift, p2p_wallet/Scenes/Main/SendToken/Subscenes/ChooseTokenAndAmount/SendToken.ChooseTokenAndAmount.RootView.swift, p2p_wallet/Scenes/Main/SwapToken/OrcaSwapV2/OrcaSwapV2.RootView.swift
https://p2pvalidator.atlassian.net/browse/PWN-5793
-
=> [PWN-5793] Button fixes

p2p_wallet/Scenes/Main/Buy/BuyInputOutputView.swift, p2p_wallet/Scenes/Main/InvestSolend/DepositWithdraw/Views/DepositWithdrawInputView.swift, p2p_wallet/Scenes/Main/SendToken/Subscenes/ChooseTokenAndAmount/SendToken.ChooseTokenAndAmount.RootView.swift, p2p_wallet/Scenes/Main/SwapToken/OrcaSwapV2/Subviews/OrcaSwapV2.WalletView.swift, p2p_wallet/UIKit/Views/TokenAmountTextField.swift
https://p2pvalidator.atlassian.net/browse/PWN-5776
-
=> [PWN-5776] Placeholders + cursor position

p2p_wallet/Services/Networking/Endpoint.swift
https://p2pvalidator.atlassian.net/browse/PWN-5787
-
=> [PWN-5787] Change test environment notification service endpoint

Podfile, Podfile.lock
https://p2pvalidator.atlassian.net/browse/PWN-5878
-
=> [PWN-5878] pod

Podfile.lock, p2p_wallet/Scenes/Main/SwapToken/OrcaSwapV2/OrcaSwapV2.RootView.swift, p2p_wallet/Scenes/Main/SwapToken/OrcaSwapV2/Subviews/OrcaSwapV2.MainSwapView.swift, p2p_wallet/Scenes/Main/SwapToken/OrcaSwapV2/Subviews/OrcaSwapV2.WalletView.swift
https://p2pvalidator.atlassian.net/browse/PWN-5909
-
=> [PWN-5909] Swap keyboard fix

p2p_wallet/Scenes/Main/Main.ViewController.swift
https://p2pvalidator.atlassian.net/browse/PWN-5787
- https://p2pvalidator.atlassian.net/browse/PWN-5787
=> [PWN-5787] Open history from push without opening intercom

Podfile, Podfile.lock, p2p_wallet/Analytics/AmplitudeEvent/AmplitudeEvent.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/Common/StateMachineProvider/OnboardingStateMachineProvider.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/BindingPhoneNumberDelegatedCoordinator.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/EnterPhoneNumberViewController.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/EnterPhoneNumberViewModel.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/EnterSMSCode/EnterSMSCodeViewController.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/EnterSMSCode/EnterSMSCodeViewModel.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/RestoreCustom/RestoreCustomDelegateCoordinator.swift
https://p2pvalidator.atlassian.net/browse/PWN-5829
-
=> [PWN-5829] Add Torus response time metric

project.yml
=> release: bump version to 2.0.3

Podfile.lock, p2p_wallet/Scenes/Main/ReceiveToken/Bitcoin/RenBTCReceivingStatuses/RenBTCReceivingStatuses.TxDetailViewController.swift, p2p_wallet/Scenes/Main/ReceiveToken/Bitcoin/RenBTCReceivingStatuses/RenBTCReceivingStatuses.ViewController.swift, p2p_wallet/Scenes/Main/ReceiveToken/ReceiveToken.ViewController.swift, p2p_wallet/Services/RenVM/RenVMSolanaChainProvider.swift
https://p2pvalidator.atlassian.net/browse/PWN-5877
-
=> [PWN-5877] Feature/pwn 5877

.github/workflows/auto-deploy.yml, .github/workflows/manual-feature-high-priority-test.yml, .github/workflows/manual-feature-homelab-test.yml, .github/workflows/manual-feature-test.yml, .github/workflows/pull_request_review.yml, p2p_wallet/Info.plist
https://p2pvalidator.atlassian.net/browse/PWN-5937
-
=> [PWN-5937] Feature/pwn 5937

p2p_wallet/Extensions/Combine/BaseViewModel.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/Common/ICloud/BaseICloudRestoreViewModel.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/Common/Pincode/Pincode/PincodeViewModel.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/Common/SocialSelection/SocialSignInViewModel.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/CreateWalletViewModel.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/BaseOTPViewModel.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/SocialSignIn/SocialSignInAccountHasBeenUsed/SocialSignInAccountHasBeenUsedViewModel.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/SocialSignIn/SocialSignInWait/SocialSignInWaitViewModel.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/RestoreWalletViewModel.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/ChooseRestoreOption/ChooseRestoreOptionViewModel.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/ICloudRestore/ICloudRestore/ICloudRestoreViewModel.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/RestoreSocialOption/RestoreSocialOptionViewModel.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/SeedPhraseRestore/SeedPhraseRestore/SeedPhraseRestoreWalletViewModel.swift, p2p_wallet/Scenes/DebugMenu/ViewModel/DebugMenuViewModel.swift, p2p_wallet/Scenes/Main/InvestSolend/Tutorial/SolendTutorialViewModel.swift, p2p_wallet/Scenes/Main/NewSettings/Settings/ViewModel/SettingsViewModel.swift, p2p_wallet/Scenes/Main/Settings/Subscenes/SeedPhraseDetail/SeedPhraseDetailViewModel.swift, p2p_wallet/Scenes/StartOnboarding/Continue/ContinueViewModel.swift, p2p_wallet/Scenes/StartOnboarding/Start/StartViewModel.swift, p2p_wallet/Scenes/Username/CreateUsername/CreateUsernameViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-5959
Now it works under 14.5 if ObservableObject is not inherited
-
=> [PWN-5959] Fix iOS 14 SwiftUI issues with observable object

p2p_wallet/Services/Networking/Dto/JsonRpcResponseDto.swift, p2p_wallet/Services/Networking/HttpClient.swift, p2p_wallet/Services/NotificationsService/NotificationService.swift, p2p_wallet/Services/NotificationsService/Repository/NotificationRepository.swift, p2p_wallet/Services/Storage/UserWalletManager.swift
https://p2pvalidator.atlassian.net/browse/PWN-5891
-
=> [PWN-5891] Feature/pwn 5891

p2p_wallet/Extensions/Combine/BaseViewModel.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/Common/Pincode/Pincode/PincodeViewModel.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/Common/SocialSelection/SocialSignInViewModel.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/CreateWalletViewModel.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/BaseOTPViewModel.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/SocialSignIn/SocialSignInAccountHasBeenUsed/SocialSignInAccountHasBeenUsedViewModel.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/SocialSignIn/SocialSignInWait/SocialSignInWaitViewModel.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/RestoreWalletViewModel.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/ChooseRestoreOption/ChooseRestoreOptionViewModel.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/ICloudRestore/ICloudRestore/ICloudRestoreViewModel.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/RestoreSocialOption/RestoreSocialOptionViewModel.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/SeedPhraseRestore/SeedPhraseRestore/SeedPhraseRestoreWalletViewModel.swift, p2p_wallet/Scenes/DebugMenu/ViewModel/DebugMenuViewModel.swift, p2p_wallet/Scenes/Main/InvestSolend/Tutorial/SolendTutorialViewModel.swift, p2p_wallet/Scenes/Main/Main.ViewModel.swift, p2p_wallet/Scenes/Main/NewSettings/Settings/ViewModel/SettingsViewModel.swift, p2p_wallet/Scenes/Main/Settings/Subscenes/SeedPhraseDetail/SeedPhraseDetailViewModel.swift, p2p_wallet/Scenes/StartOnboarding/Continue/ContinueViewModel.swift, p2p_wallet/Scenes/StartOnboarding/Start/StartViewModel.swift, p2p_wallet/Scenes/Username/CreateUsername/CreateUsernameViewModel.swift, p2p_wallet/Services/Socket.swift
https://p2pvalidator.atlassian.net/browse/PWN-5958
- https://p2pvalidator.atlassian.net/browse/PWN-5958
=> [PWN-5958] Connect to socket only from iOS 15

p2p_wallet/AppDelegate.swift
https://p2pvalidator.atlassian.net/browse/PWN-5965
- https://p2pvalidator.atlassian.net/browse/PWN-5965
=> [PWN-5965] Migrate to default currency if it is not USD

p2p_wallet/Scenes/Main/Settings/Subscenes/SeedPhraseDetail/SeedPhraseView.swift
https://p2pvalidator.atlassian.net/browse/PWN-5842
- https://p2pvalidator.atlassian.net/browse/PWN-5842
=> [PWN-5842] Hide seed phrase by default

p2p_wallet/Analytics/AmplitudeEvent/AmplitudeEvent.swift, p2p_wallet/Scenes/Main/Settings/Subscenes/RecoveryKit/RecoveryKitCoordinator.swift, p2p_wallet/Scenes/Main/Settings/Subscenes/RecoveryKit/RecoveryKitViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-5843
-
=> [PWN-5843] Add new Analytics metrics to Amplitude

p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/SeedPhraseRestore/SeedPhraseRestore/SeedPhraseRestoreWalletView.swift
https://p2pvalidator.atlassian.net/browse/PWN-5852
- https://p2pvalidator.atlassian.net/browse/PWN-5852
=> [PWN-5852] Update insets for action button on restore with seed phrase screen

p2p_wallet/Coordinators/TabBar/SettingsCoordinator.swift, p2p_wallet/Scenes/Username/CreateUsername/CreateUsernameCoordinator.swift, p2p_wallet/Scenes/Username/CreateUsername/CreateUsernameView.swift, p2p_wallet/Scenes/Username/CreateUsername/CreateUsernameViewModel.swift, p2p_wallet/Scenes/Username/CreateUsername/Models/CreateUsernameParameters.swift
https://p2pvalidator.atlassian.net/browse/PWN-5853
- https://p2pvalidator.atlassian.net/browse/PWN-5853
=> [PWN-5853] Change button appearance on Create Username screen

Podfile, Podfile.lock, p2p_wallet/Models/PendingTransaction.swift, p2p_wallet/Resources/Base.lproj/Localizable.strings, p2p_wallet/Resources/en.lproj/Localizable.strings, p2p_wallet/Resources/fr.lproj/Localizable.strings, p2p_wallet/Resources/ru.lproj/Localizable.strings, p2p_wallet/Resources/vi.lproj/Localizable.strings, p2p_wallet/Scenes/Main/ProcessTransaction/Status/ProcessTransaction.Status.ViewController.swift, p2p_wallet/Services/RenVM/RenVMSolanaChainProvider.swift, p2p_wallet/Services/SendService/SendService.swift
https://p2pvalidator.atlassian.net/browse/PWN-5952
-
=> [PWN-5952] send renBTC to Bitcoin network

p2p_wallet/Scenes/Main/ReceiveToken/ReceiveToken.SceneModel.swift, p2p_wallet/Scenes/Main/ReceiveToken/ReceiveToken.ViewController.swift, p2p_wallet/Services/FeatureFlags/Features.swift, project.yml
https://p2pvalidator.atlassian.net/browse/PWN-6067
-
=> [PWN-6067] Убрать сценарий получения renBTC

p2p_wallet/Analytics/AmplitudeEvent/AmplitudeEvent.swift, p2p_wallet/Coordinators/TabBar/ActionsCoordinator.swift, p2p_wallet/Coordinators/TabBar/HomeCoordinator.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/SeedPhraseRestore/DerivableAccounts/DerivableAccounts.ViewController.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/SeedPhraseRestore/NewDerivableAccounts/NewDerivableAccounts.ViewController.swift, p2p_wallet/Scenes/Main/NewHome/HomeWithTokens/View/HomeWithTokensView.swift, p2p_wallet/Scenes/Main/NewSettings/Settings/ViewModel/SettingsViewModel.swift, p2p_wallet/Scenes/Main/ProcessTransaction/ProcessTransaction.ViewModel.swift, p2p_wallet/Scenes/Main/ReceiveToken/Bitcoin/ReceiveToken.ReceiveBitcoinViewModel.swift, p2p_wallet/Scenes/Main/SendToken/Subscenes/ChooseRecipientAndNetwork/SelectAddress/SendToken.ChooseRecipientAndNetwork.SelectAddress.ViewController.swift, p2p_wallet/Scenes/Main/Settings/Settings.ViewModel.swift, p2p_wallet/Scenes/Main/SwapToken/OrcaSwapV2/Subviews/OrcaSwapV2.WalletView.swift, p2p_wallet/Scenes/TabBar/TabBarController.swift, p2p_wallet/UIKit/ViewControllers/QrCodeScannerVC.swift
https://p2pvalidator.atlassian.net/browse/PWN-6040
-
=> [PWN-6040] Удалить мусорные события из Амлитуды

project.yml
=> release: bump version to 2.1.1

p2p_wallet/Scenes/Main/Send/RecipentSearch/Subviews/RecipientCell.swift, p2p_wallet/Scenes/TabBar/TabBarController.swift
https://p2pvalidator.atlassian.net/browse/PWN-6170
-
=> [PWN-6170] Fix/pwn 6170

p2p_wallet/Scenes/Main/Send/SendСoordinator.swift
=> OpenSendInput refactor

p2p_wallet/Scenes/Main/Send/Input/SendInputView.swift, p2p_wallet/Scenes/Main/Send/RecipentSearch/RecipientSearchView.swift
https://p2pvalidator.atlassian.net/browse/PWN-6169
-
=> [PWN-6169] Hide keyboard on tap background views

Podfile, Podfile.lock, p2p_wallet/Resources/AppDelegate/AppDelegate+Injection.swift, p2p_wallet/Services/SendService/SendService+RewardMethod.swift
https://p2pvalidator.atlassian.net/browse/PWN-6108
-
=> [PWN-6108]Added Environment

p2p_wallet/Scenes/Main/NewHome/HomeWithTokens/ViewModel/HomeWithTokensViewModel.swift, p2p_wallet/Scenes/Main/Send/ChooseWalletToken/ChooseWalletTokenService.swift, p2p_wallet/Scenes/Main/Send/ChooseWalletToken/ChooseWalletTokenView.swift, p2p_wallet/Scenes/Main/Send/ChooseWalletToken/ChooseWalletTokenViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-6233
-
=> [PWN-6233] Filter empty and nft tokens, fix list on iOS 14

p2p_wallet/Coordinators/AppCoordinator/AppCoordinator.swift, p2p_wallet/Coordinators/SendCoordinator.swift, p2p_wallet/Coordinators/TabBar/HomeCoordinator.swift, p2p_wallet/Coordinators/TabBar/TabBarCoordinator.swift, p2p_wallet/Coordinators/WalletDetailCoordinator.swift, p2p_wallet/Scenes/TabBar/TabBarController.swift
https://p2pvalidator.atlassian.net/browse/PWN-5957
-
=> [PWN-5957] Feature/pwn 5957 2

p2p_wallet/Scenes/Main/Send/Input/SendInputCoordinator.swift, p2p_wallet/Scenes/Main/Send/Input/SendInputViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-6023
- The state was inconsistent
=> [PWN-6023] Update feeToken as it is in the state

Podfile.lock, p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/SeedPhraseRestore/SeedPhraseRestore/SeedPhraseRestoreWalletViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-6289
-
=> [PWN-6289] fix: pasteboard format seed phrase

p2p_wallet/Scenes/Main/Send/Models/AutoSelectFirstResultMode.swift, p2p_wallet/Scenes/Main/Send/RecipentSearch/RecipientSearchViewModel.swift, p2p_wallet/Scenes/Main/Send/SendСoordinator.swift
https://p2pvalidator.atlassian.net/browse/PWN-6303
-
=> [PWN-6303] feat: auto select the only one result

p2p_wallet/Scenes/Main/Send/Input/Subviews/AmountView/SendInputAmountField.swift, p2p_wallet/Scenes/Main/Send/Input/Subviews/AmountView/SendInputAmountView.swift, p2p_wallet/Scenes/Main/Send/Input/Subviews/AmountView/SendInputAmountViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-6307
- https://p2pvalidator.atlassian.net/browse/PWN-6307
=> [PWN-6307] [Do not merge] Format SendInputAmountField with current type - fiat or token

p2p_wallet/AppDelegate.swift
=> feat: disable Sentry on debug mode

p2p_wallet/Analytics/AmplitudeEvent/AmplitudeEvent.swift, p2p_wallet/Coordinators/SendEmptyCoordinator.swift, p2p_wallet/Scenes/Main/Send/Input/SendInputCoordinator.swift, p2p_wallet/Scenes/Main/Send/Input/SendInputView.swift, p2p_wallet/Scenes/Main/Send/Input/SendInputViewModel.swift, p2p_wallet/Scenes/Main/Send/Input/Subviews/AmountView/SendInputAmountViewModel.swift, p2p_wallet/Scenes/Main/Send/RecipentSearch/RecipientSearchView.swift, p2p_wallet/Scenes/Main/Send/RecipentSearch/RecipientSearchViewModel.swift, p2p_wallet/Scenes/Main/Send/SendСoordinator.swift
https://p2pvalidator.atlassian.net/browse/PWN-6208
-
=> [PWN-6208] Send analytics

p2p_wallet/Scenes/Main/Send/ChooseWalletToken/ChooseWalletTokenCoordinator.swift, p2p_wallet/Scenes/Main/Send/ChooseWalletToken/ChooseWalletTokenService.swift, p2p_wallet/Scenes/Main/Send/Input/Details/FeePrompt/SendInputFeePromptCoordinator.swift, p2p_wallet/Scenes/Main/Send/Input/Details/FeePrompt/SendInputFeePromptView.swift, p2p_wallet/Scenes/Main/Send/Input/Details/FeePrompt/SendInputFeePromptViewModel.swift, p2p_wallet/Scenes/Main/Send/Input/Details/SendTransactionDetails/SendTokenDetailsCoordinator.swift, p2p_wallet/Scenes/Main/Send/Input/Details/SendTransactionDetails/SendTransactionDetailView.swift, p2p_wallet/Scenes/Main/Send/Input/Details/SendTransactionDetails/SendTransactionDetailViewModel.swift, p2p_wallet/Scenes/Main/Send/Input/SendInputCoordinator.swift
https://p2pvalidator.atlassian.net/browse/PWN-6293
-
=> [PWN-6293] Make available fee tokens request in transaction details

p2p_wallet/Scenes/Main/Send/Input/SendInputViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-6023
-
=> [PWN-6023] Token order for choosing send wallet

p2p_wallet/Scenes/Main/ReceiveToken/ReceiveToken.SceneModel.swift, p2p_wallet/Scenes/Main/ReceiveToken/ReceiveToken.ViewController.swift
https://p2pvalidator.atlassian.net/browse/PWN-6098
-
=> [PWN-6098] Некорректное отображение экрана Receive для renBTC

p2p_wallet/Scenes/Main/NewHome/HomeWithTokens/ViewModel/HomeWithTokensViewModel.swift, p2p_wallet/Scenes/Main/Send/Input/SendInputViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-6390
-
=> [PWN-6390] feat: isSendable

p2p_wallet/Scenes/Main/NewHome/HomeWithTokens/ViewModel/HomeWithTokensViewModel.swift, p2p_wallet/Scenes/Main/Send/Input/SendInputViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-6390
-
=> [PWN-6390] Filter NFT tokens from send screen

p2p_wallet/Scenes/DebugMenu/View/DebugMenuView.swift, p2p_wallet/Scenes/DebugMenu/ViewModel/DebugMenuViewModel.swift, p2p_wallet/Services/Defaults.swift, p2p_wallet/Services/FeeRelayer/FeeRelayerEndpoint.swift, p2p_wallet/Services/GlobalAppState.swift
https://p2pvalidator.atlassian.net/browse/PWN-6358
-
=> [PWN-6358] Store forced fee relayer endpoint if it is set in debug menu

p2p_wallet/Scenes/Main/Send/Input/Subviews/AmountView/SendInputAmountViewModel.swift, p2p_wallet/Scenes/Main/Send/TransactionStatus/SendTransactionStatusViewModel.swift
=> [PWN-6023] Update max amount while fiat is main input. Show unknown error in status details

p2p_wallet/Resources/AppDelegate/AppDelegate+Injection.swift, p2p_wallet/Scenes/Main/Main.ViewModel.swift, p2p_wallet/Scenes/Main/Send/Input/SendInputViewModel.swift, p2p_wallet/Scenes/Main/SwapToken/OrcaSwapV2/OrcaSwapV2.ViewModel/OrcaSwapV2.ViewModel+Extensions.swift, p2p_wallet/Scenes/Main/SwapToken/OrcaSwapV2/OrcaSwapV2.ViewModel/OrcaSwapV2.ViewModel.swift, p2p_wallet/Services/Swap/SwapServiceType.swift, p2p_wallet/Services/Swap/SwapServiceWithRelayImpl.swift
=> feat: pre-load swap service on opening Main scene

p2p_wallet/Scenes/Main/Send/Input/SendInputViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-6403
-
=> [PWN-6403] Pick the most amount in current fiat token . Send flow

Podfile.lock
https://p2pvalidator.atlassian.net/browse/PWN-6424
-
=> [PWN-6424] Update Podfile.lock

p2p_wallet/Scenes/Main/Send/SendСoordinator.swift
https://p2pvalidator.atlassian.net/browse/PWN-6024
-
=> [PWN-6024] feat(send): prewarm fee relay context

p2p_wallet/Scenes/DebugMenu/View/DebugMenuView.swift, p2p_wallet/Scenes/DebugMenu/ViewModel/DebugMenuViewModel.swift, p2p_wallet/Scenes/Sell/Service/SellDataServiceImpl.swift, p2p_wallet/Services/Buy/Exchange/Moonpay/Provider/Moonpay.API.swift, p2p_wallet/Services/Defaults.swift
https://p2pvalidator.atlassian.net/browse/PWN-6349
-
=> [PWN-6349] В дебаг меню добавлено переключение moonpay на sandbox

p2p_wallet/Scenes/Main/Send/RecipentSearch/RecipientSearchViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-6413
-
=> [PWN-6413] Lowercase input in recipients search

p2p_wallet/Scenes/Main/Send/Input/Subviews/AmountView/SendInputAmountViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-6419
-
=> [PWN-6419] Update countAfterDecimalPoint param after token update

p2p_wallet/Scenes/Main/Send/ChooseWalletToken/ChooseWalletTokenView.swift
https://p2pvalidator.atlassian.net/browse/PWN-6410
- https://p2pvalidator.atlassian.net/browse/PWN-6410
=> [PWN-6410] Update logic of clear button on ChooseWalletToken screen

p2p_wallet/Scenes/Main/Send/Input/Subviews/AmountView/SendInputAmountField.swift
https://p2pvalidator.atlassian.net/browse/PWN-6420
-
=> [PWN-6420] Unify round mode of a number between send flow

p2p_wallet/Scenes/Main/Send/TransactionStatus/SendTransactionStatusView.swift
https://p2pvalidator.atlassian.net/browse/PWN-6421
-
=> [PWN-6421] Slow down animation on send transaction status

p2p_wallet/Scenes/Main/Send/Input/Details/FeePrompt/SendInputFeePromptCoordinator.swift, p2p_wallet/Scenes/Main/Send/Input/Details/FeePrompt/SendInputFeePromptView.swift, p2p_wallet/Scenes/Main/Send/Input/Details/FeePrompt/SendInputFeePromptViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-6295
-
=> [PWN-6295] Do not close fee prompt screen after choosing token

p2p_wallet/Scenes/Main/History/History.Coordinator.swift, p2p_wallet/Scenes/Main/Send/Input/SendInputViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-6439
-
=> [PWN-6439] Feature/pwn 6439

p2p_wallet/Scenes/Main/History/Output/History.SellTransactionsOutput.swift, p2p_wallet/Scenes/Main/History/TransactionCell/Subviews/TransactionCell.swift, p2p_wallet/Scenes/Main/History/TransactionCell/Subviews/TransactionImageView.swift
https://p2pvalidator.atlassian.net/browse/PWN-6254
-
=> [PWN-6254] feat(history): improve sell transaction displaying

p2p_wallet/Scenes/Main/Send/TransactionStatus/SendTransactionStatusView.swift, p2p_wallet/Scenes/Main/Send/TransactionStatus/SendTransactionStatusViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-6426
-
=> [PWN-6426] Change close button title

p2p_wallet/Scenes/Main/Send/Input/Subviews/AmountView/SendInputAmountViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-6480
-
=> [PWN-6480] Cut decimals if token is switched

p2p_wallet/Scenes/Main/Send/RecipentSearch/RecipientSearchViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-6450
-
=> [PWN-6450] fix(send): ignore pasting empty clipboard

p2p_wallet/Scenes/Main/Send/Input/Details/FeePrompt/SendInputFeePromptCoordinator.swift
https://p2pvalidator.atlassian.net/browse/PWN-6295
-
=> [PWN-6295] Close prompt screen if fee token was changed

p2p_wallet/Scenes/Main/Send/ChooseWalletToken/ChooseWalletTokenView.swift, p2p_wallet/Scenes/Main/Send/RecipentSearch/RecipientSearchView.swift, p2p_wallet/Scenes/Main/Send/Views/SendtNotFoundView.swift
https://p2pvalidator.atlassian.net/browse/PWN-6418
-
=> [PWN-6418] Use common empty view for send flow

p2p_wallet/Extensions/Date+Extensions.swift, p2p_wallet/Extensions/Locale+Extensions.swift, p2p_wallet/Scenes/Main/Send/TransactionStatus/SendTransactionStatusViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-6423
- https://discord.com/channels/767761912167006292/1055024546283012166
=> [PWN-6423] Remove 'a' from date format. Send transaction details. Force locale

p2p_wallet/Scenes/Main/Send/RecipentSearch/Subviews/RecipientSearchField.swift
https://p2pvalidator.atlassian.net/browse/PWN-6448
-
=> [PWN-6448] Make recipient search field content to be unique

p2p_wallet/Scenes/Main/Send/Input/Details/SendTransactionDetails/SendTransactionDetailView.swift, p2p_wallet/Scenes/Main/Send/Input/Details/SendTransactionDetails/SendTransactionDetailViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-6428
-
=> [PWN-6428] faet(send): fix send transaction

p2p_wallet/Scenes/Main/Send/ChooseWalletToken/ChooseWalletTokenViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-6435
-
=> [PWN-6435] Change filter and sort logic on ChooseWalletToken screen

p2p_wallet/Scenes/Main/Send/Input/Details/SendTransactionDetails/SendTokenDetailsCoordinator.swift, p2p_wallet/Scenes/Main/Send/Input/Details/SendTransactionDetails/SendTransactionDetailView.swift, p2p_wallet/Scenes/Main/Send/Input/Details/SendTransactionDetails/SendTransactionDetailViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-6379
-
=> [PWN-6379] Copy address from transaction detail screen

Podfile, Podfile.lock
https://p2pvalidator.atlassian.net/browse/PWN-6516
-
=> [PWN-6516] Send SOL bug

p2p_wallet/Scenes/Main/NewHome/Home/ViewModel/HomeViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-6507
-
=> [PWN-6507] feat(home): only copy address to clipboard

p2p_wallet/Analytics/AmplitudeEvent/AmplitudeEvent.swift, p2p_wallet/Coordinators/TabBar/ActionsCoordinator.swift, p2p_wallet/Scenes/Main/NewHome/HomeWithTokens/View/HomeWithTokensView.swift, p2p_wallet/Scenes/Main/NewHome/HomeWithTokens/ViewModel/HomeWithTokensViewModel.swift, p2p_wallet/Scenes/Sell/Pending/SellPendingView.swift, p2p_wallet/Scenes/Sell/Pending/SellPendingViewModel.swift, p2p_wallet/Scenes/Sell/SellCoordinator.swift, p2p_wallet/Scenes/Sell/SellInputView/SellInputView.swift, p2p_wallet/Scenes/Sell/SellViewModel.swift, p2p_wallet/Scenes/Sell/TransactionDetails/NotSuccessTransactionDetails/SellTransactionDetailsViewModel.swift, p2p_wallet/Scenes/TabBar/TabBarController.swift
https://p2pvalidator.atlassian.net/browse/PWN-6316
-
=> [PWN-6316] Разметка Off-ramp Flow в Amplitude

p2p_wallet/Scenes/Main/Send/ChooseWalletToken/ChooseWalletTokenView.swift
https://p2pvalidator.atlassian.net/browse/PWN-6295
-
=> [PWN-6295] Change tap event for already selected token

p2p_wallet/Scenes/Main/Send/Input/Subviews/AmountView/SendInputAmountViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-6496
-
=> [PWN-6496] Subscribe to currentValueSubject instead of publisher

p2p_wallet/Scenes/Main/Send/ChooseWalletToken/ChooseWalletTokenViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-6435
-
=> [PWN-6435] Sort wallets from the scratch

p2p_wallet/Scenes/Main/Send/Input/SendInputViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-6470
-
=> [PWN-6470] Update logic for MAX button

p2p_wallet/Scenes/Main/Send/RecipentSearch/RecipientSearchView.swift
https://p2pvalidator.atlassian.net/browse/PWN-6416
-
=> [PWN-6416] Remove double spaces

p2p_wallet/Scenes/Main/Send/Input/SendInputView.swift, p2p_wallet/Scenes/Main/Send/Input/SendInputViewModel.swift, p2p_wallet/UIKit/ViewControllers/KeyboardAvoidingViewController.swift
https://p2pvalidator.atlassian.net/browse/PWN-6511
-
=> [PWN-6511] Open keyboard after view loading and fix spacer

p2p_wallet/Resources/Base.lproj/Localizable.strings, p2p_wallet/Resources/en.lproj/Localizable.strings, p2p_wallet/Resources/fr.lproj/Localizable.strings, p2p_wallet/Resources/ru.lproj/Localizable.strings, p2p_wallet/Resources/vi.lproj/Localizable.strings, p2p_wallet/Scenes/Main/Sell/Error/SellErrorView.swift, p2p_wallet/Scenes/Main/Sell/SellCoordinator.swift, p2p_wallet/Scenes/Main/Sell/SellView.swift, p2p_wallet/Scenes/Main/Sell/SellViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-6571
…ан Cash Out
-
=> [PWN-6571] Экран при получении ошибки от Moon Pay при переходе

p2p_wallet/Scenes/DebugMenu/ViewModel/DebugMenuViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-6632
-
=> [PWN-6632] Добавить в дебаг меню переключение off ramp

p2p_wallet/Scenes/Main/Send/Input/SendInputViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-6575
- LOGIC here https://github.com/p2p-org/key-app-kit-swift/pull/84
=> [PWN-6575] Error text for insufficient funds state

p2p_wallet/Scenes/Main/Send/ChooseWalletToken/ChooseWalletTokenCoordinator.swift, p2p_wallet/Scenes/Main/Send/ChooseWalletToken/ChooseWalletTokenView.swift, p2p_wallet/Scenes/Main/Send/Input/SendInputViewModel.swift, p2p_wallet/UIKit/ViewControllers/KeyboardAvoidingViewController.swift
https://p2pvalidator.atlassian.net/browse/PWN-6418
- https://p2pvalidator.atlassian.net/browse/PWN-6418
=> [PWN-6418]  Customize KeyboardAvoiding vc for choose wallet screen

p2p_wallet/Scenes/Main/Send/Input/Details/SendTransactionDetails/SendTransactionDetailViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-6594
-
=> [PWN-6594] Sum account and transaction fees in transaction details

p2p_wallet/UIKit/ViewControllers/KeyboardAvoidingViewController.swift
https://p2pvalidator.atlassian.net/browse/PWN-6468
-
=> [PWN-6468] Fix background/foreground keyboard state

p2p_wallet/Services/Storage/UserWalletManager.swift
https://p2pvalidator.atlassian.net/browse/PWN-6673
- 
[PWN-6673]: https://p2pvalidator.atlassian.net/browse/PWN-6673?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PWN-6673] changed derivation path for moonpay

p2p_wallet/Scenes/Main/Send/TransactionStatus/Details/SendTransactionStatusDetailsCoordinator.swift, p2p_wallet/Scenes/Main/Send/TransactionStatus/Details/SendTransactionStatusDetailsParameters.swift, p2p_wallet/Scenes/Main/Send/TransactionStatus/Details/SendTransactionStatusDetailsView.swift, p2p_wallet/Scenes/Main/Send/TransactionStatus/SendTransactionStatusViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-6465
- 
[PWN-6465]: https://p2pvalidator.atlassian.net/browse/PWN-6465?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PWN-6465] Handle FeeRelayerError.topUpSuccessButTransactionThrows

Podfile.lock, p2p_wallet/Scenes/Main/Send/Input/Details/FreeTransactionsDetail/SendInputFreeTransactionsDetailCoordinator.swift, p2p_wallet/Scenes/Main/Send/Input/Details/FreeTransactionsDetail/SendInputFreeTransactionsDetailView.swift, p2p_wallet/Scenes/Main/Send/Input/Details/SendTransactionDetails/SendTokenDetailsCoordinator.swift, p2p_wallet/Scenes/Main/Send/Input/Details/SendTransactionDetails/SendTransactionDetailView.swift, p2p_wallet/Scenes/Main/Send/SendСoordinator.swift, p2p_wallet/SwiftUI/Modifiers/SheetHeaderModifier.swift, p2p_wallet/SwiftUI/UIBottomSheetHostingController.swift
https://p2pvalidator.atlassian.net/browse/PWN-6430
-
=> [PWN-6430] Feature/pwn 6430

Podfile.lock, p2p_wallet/Scenes/Main/Send/RecipentSearch/RecipientSearchViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-6446
- 
[PWN-6446]: https://p2pvalidator.atlassian.net/browse/PWN-6446?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PWN-6446] feat: remove duplicate

p2p_wallet/Scenes/Main/Sell/Pending/SellPendingCoordinator.swift, p2p_wallet/Scenes/Main/Sell/Pending/SellPendingHostingController.swift, p2p_wallet/Scenes/Main/Sell/Pending/SellPendingView.swift
https://p2pvalidator.atlassian.net/browse/PWN-6263
-
=> [PWN-6263] feat: return navigation bar, replace back button

p2p_wallet/Scenes/Main/Sell/SellViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-6708
-
=> [PWN-6708] feat: fix fee loading status

p2p_wallet/Scenes/Main/Sell/Pending/SellPendingView.swift
https://p2pvalidator.atlassian.net/browse/PWN-6696
-
=> [PWN-6696] bugfix

p2p_wallet/Scenes/Main/Send/ChooseWalletToken/ChooseWalletTokenService.swift, p2p_wallet/Scenes/Main/Send/Input/Details/SendTransactionDetails/SendTransactionDetailViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-6452
-
=> [PWN-6452] Pass new param to SendChooseFeeService

p2p_wallet/Scenes/Main/Sell/Pending/SellPendingCoordinator.swift, p2p_wallet/Scenes/Main/Sell/Pending/SellPendingView.swift
=> feat: fix navigation title

p2p_wallet/Scenes/Main/Sell/Pending/SellPendingCoordinator.swift, p2p_wallet/Scenes/Main/Sell/Pending/SellPendingView.swift, p2p_wallet/Scenes/Main/Sell/Pending/SellPendingViewModel.swift, p2p_wallet/Scenes/Main/Sell/SellCoordinator.swift
=> [PWN-6711] [PWN-6713] Off ramp fixes2

p2p_wallet/Coordinators/TabBar/HomeCoordinator.swift, p2p_wallet/Coordinators/TabBar/TabBarCoordinator.swift, p2p_wallet/Scenes/Main/Sell/Pending/SellPendingCoordinator.swift, p2p_wallet/Scenes/Main/Sell/Pending/SellPendingHostingController.swift, p2p_wallet/Scenes/Main/Sell/SellCoordinator.swift
=> [PWN-6712] [PWN-6772] Bugfixes

.github/workflows/auto-deploy-high-priority.yml, .github/workflows/auto-deploy.yml, .github/workflows/manual-feature-high-priority-test.yml, .github/workflows/manual-feature-test.yml, .github/workflows/pull_request_review.yml, .github/workflows/release.yml
https://p2pvalidator.atlassian.net/browse/PWN-6515
-
=> [PWN-6515] feat: add SENTRY_TOKEN secret

p2p_wallet/Scenes/Main/Send/Input/SendInputViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-6647
-
=> [PWN-6647] Check max button in insufficientFunds state

p2p_wallet/Scenes/Main/Send/RecipentSearch/RecipientSearchViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-6753
-
=> [PWN-6753] Open keyboard when the data is loaded

p2p_wallet/Scenes/Main/Send/RecipentSearch/RecipientSearchViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-6762
- after https://github.com/p2p-org/p2p-wallet-ios/pull/883
=> [PWN-6762] Open QR scanner value in case it was opened previously

p2p_wallet/Scenes/Main/Send/Input/SendInputView.swift
https://p2pvalidator.atlassian.net/browse/PWN-6468
-
=> [PWN-6468] Display debug info only when keyboard is off

p2p_wallet/AppDelegate.swift, p2p_wallet/Extensions/Double+Extensions.swift, p2p_wallet/Scenes/Main/Buy/BuySelect/BuySelectView.swift, p2p_wallet/Scenes/Main/Buy/BuyViewModel.swift, p2p_wallet/Scenes/Main/BuyTransactionDetails/BuyTransactionDetailsView.swift, p2p_wallet/Scenes/Main/History/Transaction/ViewModel/TransactionViewModel.swift, p2p_wallet/Scenes/Main/InvestSolend/DepositWithdraw/DepositSolendViewModel.swift, p2p_wallet/Scenes/Main/InvestSolend/Deposits/SolendDepositsViewModel.swift, p2p_wallet/Scenes/Main/InvestSolend/SelectToken/TokenToDeposit/TokenToDepositView.swift, p2p_wallet/Scenes/Main/InvestSolend/SelectToken/TokenToWithdraw/TokenToWithdrawView.swift, p2p_wallet/Scenes/Main/InvestSolend/SolendTransactionDetails/SolendTransactionDetailsView.swift, p2p_wallet/Scenes/Main/Old/Buy/TokenSelection/TokenSelection.Scene.swift, p2p_wallet/Scenes/Main/ReceiveToken/NetworkSelection/ConfirmReceivingBitcoin/ConfirmReceivingBitcoin.ViewController+CreateRenBTC.swift, p2p_wallet/Scenes/Main/Send/ChooseWalletToken/ChooseWalletTokenItemView.swift, p2p_wallet/Scenes/Main/Send/Input/Details/SendTransactionDetails/SendTransactionDetailViewModel.swift, p2p_wallet/Scenes/Main/Send/Input/SendInputViewModel.swift, p2p_wallet/Scenes/Main/Send/Input/Subviews/TokenView/SendInputTokenViewModel.swift, p2p_wallet/Scenes/Main/Send/TransactionStatus/SendTransactionStatusViewModel.swift, p2p_wallet/Scenes/Main/SwapToken/OrcaSwapV2/ConfirmSwapping/OrcaSwapV2ConfirmSwappingViewModelType.swift, p2p_wallet/Scenes/Main/SwapToken/OrcaSwapV2/Subviews/OrcaSwapV2.RatesStackView.swift, p2p_wallet/Scenes/Main/SwapToken/Settings/Subviews/SwapTokenSettings.FeeCell.swift, p2p_wallet/Scenes/Main/TransactionDetail/Subviews/TransactionDetail.AmountSection.swift, p2p_wallet/Scenes/Main/TransactionDetail/Subviews/TransactionDetail.SummaryView.swift, p2p_wallet/Scenes/Main/WalletDetail/WalletDetail.ViewController.swift, p2p_wallet/UIKit/SwiftUI/Cells/TokenCellView.swift, p2p_wallet/UIKit/Views/WalletCells/BaseWalletCell.swift, p2p_wallet/UIKit/Views/WalletCells/WalletCell.swift
https://p2pvalidator.atlassian.net/browse/PWN-6536
- 
[PWN-6536]: https://p2pvalidator.atlassian.net/browse/PWN-6536?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PWN-6536] Feature/pwn 6536

p2p_wallet/Resources/Colors.xcassets/ffdce9.colorset/Contents.json, p2p_wallet/Resources/Colors.xcassets/h04D004.colorset/Contents.json, p2p_wallet/Scenes/Main/Send/TransactionStatus/SendTransactionStatusView.swift, p2p_wallet/Scenes/Main/Send/TransactionStatus/SendTransactionStatusViewAppearance.swift
https://p2pvalidator.atlassian.net/browse/PWN-6815
-
=> [PWN-6815] Update send status transaction view colors

p2p_wallet/Scenes/Main/Sell/SellCoordinator.swift, p2p_wallet/Scenes/Main/Sell/SellView.swift, p2p_wallet/Scenes/Main/Sell/SellViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-6822
-
=> [PWN-6822] Blocking keyboard on opening moonpay

p2p_wallet/Scenes/Main/Sell/SellCoordinator.swift, p2p_wallet/Scenes/Main/Sell/SellViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-6826
-
=> [PWN-6826] navigate to sell with param

p2p_wallet/Scenes/Main/Sell/TransactionDetails/NotSuccessTransactionDetails/SellTransactionDetailsView.swift
https://p2pvalidator.atlassian.net/browse/PWN-6831
-
=> [PWN-6831] Fix/pwn 6831

Podfile.lock, p2p_wallet/Info.plist, p2p_wallet/Services/Buy/BuyProccessing/MoonpayBuyProcessing.swift, p2p_wallet/Services/Networking/Endpoint.swift
https://p2pvalidator.atlassian.net/browse/PWN-6700
-
=> [PWN-6700] feat(env): update endpoints

p2p_wallet/UIKit/ViewControllers/QrCodeScannerVC.swift
https://p2pvalidator.atlassian.net/browse/PWN-6864
-
=> [PWN-6864] Handle optional captureSession object

p2p_wallet/Scenes/Main/Send/Input/Details/FeePrompt/SendInputFeePromptCoordinator.swift, p2p_wallet/Scenes/Main/Send/Input/Details/FeePrompt/SendInputFeePromptView.swift, p2p_wallet/Scenes/Main/Send/Input/Details/FeePrompt/SendInputFeePromptViewModel.swift, p2p_wallet/Scenes/Main/Send/Input/SendInputCoordinator.swift
https://p2pvalidator.atlassian.net/browse/PWN-6868
-
=> [PWN-6868] Calculate fee in the same token around several send screens

p2p_wallet/Scenes/Main/Send/Input/Subviews/AmountView/SendInputAmountViewModel.swift, p2p_wallet/Services/Defaults.swift, p2p_wallet/Services/Storage/UserWalletManager.swift
https://p2pvalidator.atlassian.net/browse/PWN-6517
-
=> [PWN-6517] Remember send input type choice and reset it on logout

Podfile.lock, p2p_wallet/Scenes/Main/SwapToken/OrcaSwapV2/OrcaSwapV2.RootView.swift
=> [PWN-6462] [PWN-6781]Fixes

p2p_wallet/Scenes/Main/Sell/Pending/SellPendingView.swift
https://p2pvalidator.atlassian.net/browse/PWN-6881
-
=> [PWN-6881] Do not include token symbol in sell button on SellPendingView

p2p_wallet/Coordinators/SellTransactionDetailsCoordinator.swift, p2p_wallet/Resources/Base.lproj/Localizable.strings, p2p_wallet/Resources/en.lproj/Localizable.strings, p2p_wallet/Resources/fr.lproj/Localizable.strings, p2p_wallet/Resources/ru.lproj/Localizable.strings, p2p_wallet/Resources/vi.lproj/Localizable.strings, p2p_wallet/Scenes/Main/Sell/TransactionDetails/NotSuccessTransactionDetails/SellTransactionDetailsView.swift, p2p_wallet/Scenes/Main/Sell/TransactionDetails/NotSuccessTransactionDetails/SellTransactionDetailsViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-6827
- https://github.com/p2p-org/p2p-wallet-ios-secret/pull/22
=> [PWN-6827] Add navigation to moonhelp support centre

p2p_wallet/AppDelegate.swift, p2p_wallet/Firebase/Dev/GoogleService-Info.plist, p2p_wallet/Firebase/Prod/GoogleService-Info.plist, project.yml
https://p2pvalidator.atlassian.net/browse/PWN-6720
-
=> [PWN-6720] dSYM missing for firebase

p2p_wallet/Scenes/Main/Send/Input/Details/SendTransactionDetails/SendTransactionDetailViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-6617
-
=> [PWN-6617] Fix transaction fee fiat display and free condition

p2p_wallet/Resources/Base.lproj/Localizable.strings, p2p_wallet/Resources/en.lproj/Localizable.strings, p2p_wallet/Resources/fr.lproj/Localizable.strings, p2p_wallet/Resources/ru.lproj/Localizable.strings, p2p_wallet/Resources/vi.lproj/Localizable.strings, p2p_wallet/Scenes/Main/Sell/info/MoonpayInfoView.swift
=> [PWN-6854] Localisation for MoonpayInfoView

p2p_wallet/Resources/Base.lproj/Localizable.strings, p2p_wallet/Resources/en.lproj/Localizable.strings, p2p_wallet/Resources/fr.lproj/Localizable.strings, p2p_wallet/Resources/ru.lproj/Localizable.strings, p2p_wallet/Resources/vi.lproj/Localizable.strings, p2p_wallet/Scenes/Main/Sell/SellCoordinator.swift, p2p_wallet/Scenes/Main/Sell/SellInputView/SellInputView.swift, p2p_wallet/Scenes/Main/Sell/SellView.swift, p2p_wallet/Scenes/Main/Sell/SellViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-6853
-
=> [PWN-6853] Form redesign

p2p_wallet/Analytics/AmplitudeEvent/AmplitudeEvent.swift, p2p_wallet/Resources/Base.lproj/Localizable.strings, p2p_wallet/Resources/en.lproj/Localizable.strings, p2p_wallet/Resources/fr.lproj/Localizable.strings, p2p_wallet/Resources/ru.lproj/Localizable.strings, p2p_wallet/Resources/vi.lproj/Localizable.strings, p2p_wallet/Scenes/Main/Sell/Sell+Models.swift, p2p_wallet/Scenes/Main/Sell/SellCoordinator.swift, p2p_wallet/Scenes/Main/Sell/SellSOLInfoSheet/SellSOLInfoCoordinator.swift, p2p_wallet/Scenes/Main/Sell/SellView.swift, p2p_wallet/Scenes/Main/Sell/SellViewModel.swift
=> [PWN-6956-6955] Fix minimum sol amount state and wrong keyboard appearance

p2p_wallet/Scenes/Main/Sell/SellView.swift, p2p_wallet/Scenes/Main/Sell/SellViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-6852
-
=> [PWN-6852] Change presentInfo logic call

p2p_wallet/Extensions/Double+Extensions.swift, p2p_wallet/Scenes/Main/Sell/Pending/SellPendingViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-6819
-
=> [PWN-6819] Currency code instead of symbol

p2p_wallet/Scenes/Main/Sell/SellViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-6975
-
=> [PWN-6975] dont show keyboard on moonpay info screen

p2p_wallet/Scenes/Main/Sell/Pending/SellPendingCoordinator.swift, p2p_wallet/Scenes/Main/Sell/Pending/SellPendingView.swift, p2p_wallet/Scenes/Main/Sell/Pending/SellPendingViewModel.swift, p2p_wallet/Scenes/Main/Sell/SellCoordinator.swift
https://p2pvalidator.atlassian.net/browse/PWN-6881
-
=> [PWN-6881] Hide token symbol if came from webview. SellPendingView

p2p_wallet/Scenes/Main/Sell/SellInputView/SellInputView.swift, p2p_wallet/Scenes/Main/Sell/SellViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-7002
-
=> [PWN-7002] new calc

p2p_wallet/AppDelegate.swift
https://p2pvalidator.atlassian.net/browse/PWN-6818
-
=> [PWN-6818] Добавить события для маркетинга в Firebase

Podfile.lock, p2p_wallet/Scenes/Main/Sell/TransactionDetails/NotSuccessTransactionDetails/SellTransactionDetailsInfoView.swift, p2p_wallet/Scenes/Main/Sell/TransactionDetails/NotSuccessTransactionDetails/SellTransactionDetailsView.swift, p2p_wallet/Scenes/TabBar/TabBarController.swift, p2p_wallet/SwiftUI/Modifiers/SheetHeaderModifier.swift, project.yml
=> release: bump version to 2.3

Podfile.lock, fastlane/Fastfile, p2p_wallet/Scenes/Main/Sell/TransactionDetails/NotSuccessTransactionDetails/SellTransactionDetailsInfoView.swift, p2p_wallet/Scenes/Main/Sell/TransactionDetails/NotSuccessTransactionDetails/SellTransactionDetailsView.swift, p2p_wallet/Scenes/TabBar/TabBarController.swift, p2p_wallet/SwiftUI/Modifiers/SheetHeaderModifier.swift, project.yml
https://p2pvalidator.atlassian.net/browse/PWN-7050
-
=> [PWN-7050] Feature/pwn 7050

p2p_wallet/Scenes/Main/Send/Input/SendInputViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-6786
- https://github.com/p2p-org/key-app-kit-swift/pull/96
=> [PWN-6786] Change initialize action in SendInputState

p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/SeedPhraseRestore/SeedPhraseRestore/SeedPhraseRestoreWalletViewModel.swift
=> [NO_TASK] Remove seed phrase from the code

p2p_wallet/AppDelegate.swift, p2p_wallet/Info.plist, p2p_wallet/Resources/AppDelegate/AppDelegate+Injection.swift
https://p2pvalidator.atlassian.net/browse/PWN-6856
-
=> [PWN-6856] Разделить отправку тестовой и продовской аналитики

p2p_wallet/Analytics/KeyAppAnalyticsEvent.swift, p2p_wallet/Scenes/Main/Sell/SellCoordinator.swift, p2p_wallet/Scenes/Main/Sell/SellSOLInfoSheet/SellSOLInfoCoordinator.swift
https://p2pvalidator.atlassian.net/browse/PWN-6965
-
=> [PWN-6965] Feature/pwn 6965

p2p_wallet/Analytics/KeyAppAnalyticsEvent.swift, p2p_wallet/Services/NotificationsService/NotificationService.swift
https://p2pvalidator.atlassian.net/browse/PWN-6920
-
=> [PWN-6920] feat(analytics): listen notification grant

p2p_wallet/Services/Storage/KeychainStorage+Extensions.swift, p2p_wallet/Services/Storage/KeychainStorage+ICloudStorageType.swift, p2p_wallet/Services/Storage/KeychainStorage.swift, p2p_wallet/Services/Storage/Storage.swift
- StorageValueOnChange is nowhere to be used. Delete it
=> feat: remove StorageValueOnChange

p2p_wallet/Scenes/Main/Send/Input/SendInputView.swift, p2p_wallet/Scenes/Main/Send/Input/SendInputViewModel.swift, p2p_wallet/Scenes/Main/Send/Input/Subviews/AmountView/SendInputAmountView.swift, p2p_wallet/Scenes/Main/Send/RecipentSearch/Subviews/RecipientSearchField.swift
https://p2pvalidator.atlassian.net/browse/PWN-7052
-
=> [PWN-7052] feat(send): add accessibilityIdentifier

Podfile, Podfile.lock
https://p2pvalidator.atlassian.net/browse/PWN-7044
-
=> [PWN-7044] Move relay account creation fee to `accountBalances`

p2p_wallet/Scenes/Main/Buy/BuyViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-6914
-
=> [PWN-6914] Change defaultMinAmount on Buy screen

p2p_wallet/AppDelegate.swift, p2p_wallet/Coordinators/AppCoordinator/AppCoordinator+AppEventHandlerDelegate.swift, p2p_wallet/Resources/AppDelegate/AppDelegateProxyService.swift, p2p_wallet/Resources/AppDelegate/DeeplinkAppDelegateService.swift, p2p_wallet/Services/AppEventHandler/AppEventHandlerDelegate.swift, p2p_wallet/Services/PinService.swift
https://p2pvalidator.atlassian.net/browse/PWN-7054
-
=> [PWN-7054] Feature/pwn 7054

p2p_wallet/Resources/Base.lproj/Localizable.strings, p2p_wallet/Resources/en.lproj/Localizable.strings, p2p_wallet/Resources/fr.lproj/Localizable.strings, p2p_wallet/Resources/ru.lproj/Localizable.strings, p2p_wallet/Resources/vi.lproj/Localizable.strings, p2p_wallet/Scenes/Main/Buy/BuyCoordinator.swift, p2p_wallet/Scenes/Main/Buy/BuyInputOutputView.swift, p2p_wallet/Scenes/Main/Buy/BuyView.swift, p2p_wallet/Scenes/Main/Buy/BuyViewModel.swift, p2p_wallet/Scenes/Main/Sell/SellCoordinator.swift, p2p_wallet/Scenes/Main/Sell/SellInputView/SellInputView.swift, p2p_wallet/Scenes/Main/Sell/SellView.swift, p2p_wallet/Scenes/Main/Sell/SellViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-7221
-
=> [PWN-7221] Moonpay license

p2p_wallet/Scenes/Main/TransactionDetailView/Model/RendableDetailTransaction+HistoryTransaction.swift, p2p_wallet/Scenes/Main/TransactionDetailView/Model/RendableDetailTransaction+Mock.swift, p2p_wallet/Scenes/Main/TransactionDetailView/Model/RendableDetailTransaction+ParsedTransaction.swift, p2p_wallet/Scenes/Main/TransactionDetailView/Model/RendableDetailTransaction+PendingTransaction.swift, p2p_wallet/Scenes/Main/TransactionDetailView/Model/RendableDetailTransaction.swift, p2p_wallet/Scenes/Main/TransactionDetailView/Subview/TransactionDetailIconView.swift, p2p_wallet/Scenes/Main/TransactionDetailView/Subview/TransactionDetailStatusView.swift, p2p_wallet/Scenes/Main/TransactionDetailView/TransactionDetailCoordinator.swift, p2p_wallet/Scenes/Main/TransactionDetailView/TransactionDetailView.swift, p2p_wallet/Scenes/Main/TransactionDetailView/TransactionDetailViewModel.swift
=> Transaction Detail View

Podfile.lock, p2p_wallet/Resources/Base.lproj/Localizable.strings, p2p_wallet/Resources/en.lproj/Localizable.strings, p2p_wallet/Resources/fr.lproj/Localizable.strings, p2p_wallet/Resources/ru.lproj/Localizable.strings, p2p_wallet/Resources/vi.lproj/Localizable.strings, p2p_wallet/Scenes/Main/Sell/SellView.swift, p2p_wallet/Scenes/Main/Send/Input/SendInputView.swift, p2p_wallet/Scenes/Main/Send/Input/SendInputViewModel.swift, p2p_wallet/Scenes/Main/Swap/State/BusinessLogic/Actions/JupiterSwapBusinessLogic+ChangeAmount.swift, p2p_wallet/Scenes/Main/Swap/State/BusinessLogic/Helpers/JupiterSwapBusinessLogic+Calculate.swift, p2p_wallet/Scenes/Main/Swap/State/BusinessLogic/Helpers/JupiterSwapBusinessLogic+PriceInfo.swift, p2p_wallet/Scenes/Main/Swap/State/BusinessLogic/JupiterSwapBusinessLogic.swift, p2p_wallet/Scenes/Main/Swap/State/JupiterSwapState.swift, p2p_wallet/Scenes/Main/Swap/State/JupiterSwapStateMachine.swift, p2p_wallet/Scenes/Main/Swap/Swap/NewSwapCoordinator.swift, p2p_wallet/Scenes/Main/Swap/Swap/Subviews/Input/SwapInputViewModel.swift, p2p_wallet/Scenes/Main/Swap/Swap/SwapView.swift, p2p_wallet/Scenes/Main/Swap/Swap/SwapViewModel.swift, p2p_wallet/SwiftUI/Buttons/SliderButton/SliderActionButton.swift
https://p2pvalidator.atlassian.net/browse/PWN-7099
-
=> [PWN-7099] - 2 PR fixes and amount validation logic

p2p_wallet/Scenes/Main/Buy/BuyInputOutputView.swift, p2p_wallet/Scenes/Main/Buy/BuyView.swift
https://p2pvalidator.atlassian.net/browse/PWN-7209
-
=> [PWN-7209] Added accessibility Buy

p2p_wallet/Coordinators/AppCoordinator/AppCoordinator.swift, p2p_wallet/Coordinators/TabBar/HomeCoordinator.swift, p2p_wallet/Coordinators/TabBar/TabBarCoordinator.swift, p2p_wallet/Scenes/DebugMenu/ViewModel/DebugMenuViewModel.swift, p2p_wallet/Scenes/Main/Swap/Common/Models/SwapToken.swift, p2p_wallet/Scenes/Main/Swap/State/BusinessLogic/Actions/JupiterSwapBusinessLogic+Initialize.swift, p2p_wallet/Scenes/Main/Swap/State/BusinessLogic/Helpers/JupiterSwapBusinessLogic+AutoChoose.swift, p2p_wallet/Scenes/Main/Swap/State/BusinessLogic/Helpers/JupiterSwapBusinessLogic+Calculate.swift, p2p_wallet/Scenes/Main/Swap/State/BusinessLogic/JupiterSwapBusinessLogic.swift, p2p_wallet/Scenes/Main/Swap/State/JupiterSwapAction.swift, p2p_wallet/Scenes/Main/Swap/Swap/JupiterSwapCoordinator.swift, p2p_wallet/Scenes/Main/Swap/Swap/SwapViewModel.swift, p2p_wallet/Scenes/Main/WalletDetail/WalletDetail.ViewController.swift, p2p_wallet/Scenes/Main/WalletDetail/WalletDetail.ViewModel.swift, p2p_wallet/Services/FeatureFlags/Features.swift
https://p2pvalidator.atlassian.net/browse/PWN-7274
-
=> [PWN-7274] Add JupiterSwap feature flag and navigation logic for it

p2p_wallet/Scenes/Main/Swap/Providers/JupiterTokensRepository.swift, p2p_wallet/Scenes/Main/Swap/State/BusinessLogic/Helpers/JupiterSendTransactionToBlockchain.swift, p2p_wallet/Scenes/Main/Swap/State/BusinessLogic/Helpers/JupiterSwapBusinessLogic+Calculate.swift, p2p_wallet/Scenes/Main/Swap/State/JupiterSwapServices.swift, p2p_wallet/Scenes/Main/Swap/State/JupiterSwapState.swift, p2p_wallet/Scenes/Main/Swap/Swap/NewSwapCoordinator.swift, p2p_wallet/Scenes/Main/Swap/Swap/Subviews/Input/SwapInputViewModel.swift, p2p_wallet/Scenes/Main/Swap/Swap/SwapView.swift, p2p_wallet/Scenes/Main/Swap/Swap/SwapViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-7103
-
=> [PWN-7103], [PWN-7153], [PWN-7107] New swap. Select Token B

p2p_wallet/Scenes/Main/SendToken/Empty/SendEmptyRowView.swift, p2p_wallet/Scenes/Main/SendToken/Empty/SendEmptyView.swift
https://p2pvalidator.atlassian.net/browse/PWN-7266
-
=> [PWN-7266] SendEmptyView accesibility ids

p2p_wallet/Scenes/Main/Swap/Swap/Subviews/Input/SwapInputView.swift, p2p_wallet/Scenes/Main/Swap/Swap/Subviews/Input/SwapInputViewModel.swift, p2p_wallet/Scenes/Main/Swap/Swap/Subviews/SwapSwitchButton.swift, p2p_wallet/Scenes/Main/Swap/Swap/SwapView.swift, p2p_wallet/SwiftUI/ErrorView/BaseErrorView.swift
=> [PWN-6960] Add accessibilityIdentifiers to SwapView

p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/SeedPhraseRestore/RestoreSeedPhraseDelegatedCoordinator.swift
https://p2pvalidator.atlassian.net/browse/PWN-7162
-
=> [PWN-7162] feat: fix keyboard when moving from RestoreSeed

p2p_wallet/Scenes/Main/Swap/State/BusinessLogic/Actions/JupiterSwapBusinessLogic+Initialize.swift, p2p_wallet/Scenes/Main/Swap/State/BusinessLogic/Actions/JupiterSwapBusinessLogic+UserWalletsUpdated.swift, p2p_wallet/Scenes/Main/Swap/State/BusinessLogic/Helpers/JupiterSwapBusinessLogic+AutoChoose.swift, p2p_wallet/Scenes/Main/Swap/State/BusinessLogic/Helpers/JupiterSwapBusinessLogic+Calculate.swift, p2p_wallet/Scenes/Main/Swap/State/JupiterSwapServices.swift, p2p_wallet/Scenes/Main/Swap/State/JupiterSwapState.swift, p2p_wallet/Scenes/Main/Swap/Swap/Subviews/Input/SwapInputViewModel.swift, p2p_wallet/Scenes/Main/Swap/Swap/SwapViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-7141
-
=> [PWN-7141] Handle min SOL amount on Swap flow

p2p_wallet/Scenes/Main/Sell/SellViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-7429
-
=> [PWN-7429] Fix sell validation text

p2p_wallet/Scenes/Main/Swap/State/BusinessLogic/Actions/JupiterSwapBusinessLogic+Initialize.swift, p2p_wallet/Scenes/Main/Swap/State/BusinessLogic/JupiterSwapBusinessLogic.swift, p2p_wallet/Scenes/Main/Swap/State/JupiterSwapAction.swift, p2p_wallet/Scenes/Main/Swap/Swap/SwapViewModel.swift, p2p_wallet/Services/Defaults.swift
https://p2pvalidator.atlassian.net/browse/PWN-7262
-
=> [PWN-7262] Save selected from and to tokens

p2p_wallet/Resources/Assets.xcassets/info-straight.imageset/Contents.json, p2p_wallet/Resources/Base.lproj/Localizable.strings, p2p_wallet/Resources/en.lproj/Localizable.strings, p2p_wallet/Resources/fr.lproj/Localizable.strings, p2p_wallet/Resources/ru.lproj/Localizable.strings, p2p_wallet/Resources/vi.lproj/Localizable.strings, p2p_wallet/Scenes/Main/Swap/SwapSettings/View/SwapSettingsView.swift, p2p_wallet/Scenes/Main/Swap/SwapSettings/ViewModel/SwapSettingsViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-7104
-
=> [PWN-7104] feat: add rows

p2p_wallet/Resources/Base.lproj/Localizable.strings, p2p_wallet/Resources/en.lproj/Localizable.strings, p2p_wallet/Resources/fr.lproj/Localizable.strings, p2p_wallet/Resources/ru.lproj/Localizable.strings, p2p_wallet/Resources/vi.lproj/Localizable.strings, p2p_wallet/Scenes/Main/Swap/Swap/JupiterSwapCoordinator.swift, p2p_wallet/Scenes/Main/Swap/Swap/SwapViewModel.swift, p2p_wallet/Scenes/Main/Swap/SwapSettings/Coordinator/SwapSettingsCoordinator.swift, p2p_wallet/Scenes/Main/TransactionDetailView/Model/RendableDetailTransaction+PendingTransaction.swift, p2p_wallet/Scenes/Main/TransactionDetailView/Subview/TransactionDetailStatusView.swift, p2p_wallet/Scenes/Main/TransactionDetailView/TransactionDetailView.swift, p2p_wallet/Scenes/Main/TransactionDetailView/TransactionDetailViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-7109
[PWN-7500] Не отображается ошибка Slippage error при проведении транзакции
- 
[PWN-7500]: https://p2pvalidator.atlassian.net/browse/PWN-7500?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PWN-7109], [PWN-7500] New swap. Информационная штора. Корнер кейс с ошибкой

p2p_wallet/Scenes/Main/TransactionDetailView/Subview/TransactionDetailStatusView.swift, p2p_wallet/Services/TransactionHandler/TransactionHandler+Extensions.swift
https://p2pvalidator.atlassian.net/browse/PWN-7498
…верждения тразакции
-
=> [PWN-7498] Появляется тост о подтверждении транзакции над шторой

p2p_wallet/Scenes/Main/Swap/Providers/JupiterTokensLocalProvider.swift
https://p2pvalidator.atlassian.net/browse/PWN-7502
-
=> [PWN-7502] Fix wrong date condition for JupiterTokensCache validation

p2p_wallet/Scenes/Main/Swap/State/BusinessLogic/JupiterSwapBusinessLogic.swift, p2p_wallet/Scenes/Main/Swap/Swap/Subviews/Input/SwapInputViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-7508
-
=> [PWN-7508] Update amount of from token if it has been changed

p2p_wallet/Coordinators/SolendDepositsCoordinator.swift, p2p_wallet/Coordinators/TabBar/HomeCoordinator.swift, p2p_wallet/Coordinators/TabBar/SolendCoordinator.swift, p2p_wallet/Coordinators/TabBar/TabBarCoordinator.swift, p2p_wallet/Scenes/Main/Swap/Swap/JupiterSwapCoordinator.swift, p2p_wallet/Scenes/Main/Swap/Swap/Subviews/Input/SwapInputViewModel.swift, p2p_wallet/Scenes/Main/Swap/Swap/SwapViewModel.swift, p2p_wallet/Scenes/Main/Swap/SwapSettings/Coordinator/SwapSettingsCoordinator.swift, p2p_wallet/Scenes/Main/Swap/SwapSettings/ViewModel/SwapSettingsViewModel.swift, p2p_wallet/Scenes/Main/TransactionDetailView/Model/RendableDetailTransaction+HistoryTransaction.swift, p2p_wallet/Scenes/Main/TransactionDetailView/Model/RendableDetailTransaction+Mock.swift, p2p_wallet/Scenes/Main/TransactionDetailView/Model/RendableDetailTransaction+ParsedTransaction.swift, p2p_wallet/Scenes/Main/TransactionDetailView/Model/RendableDetailTransaction+PendingTransaction.swift, p2p_wallet/Scenes/Main/TransactionDetailView/Model/RendableTransactionDetail.swift, p2p_wallet/Scenes/Main/TransactionDetailView/Subview/TransactionDetailStatusView.swift, p2p_wallet/Scenes/Main/TransactionDetailView/TransactionDetailViewModel.swift, p2p_wallet/Scenes/Main/WalletDetail/New/DetailAccountCoordinator.swift, p2p_wallet/Scenes/Main/WalletDetail/Old/WalletDetail.ViewController.swift, p2p_wallet/Services/AnalyticsManager/Events/KeyAppAnalyticsEvent.swift
=> [PWN-7224] New swap analytics

p2p_wallet/Scenes/Main/Swap/State/JupiterSwapState.swift
=> feat: show exchange rate from coingecko when input is empty

Podfile.lock
https://p2pvalidator.atlassian.net/browse/PWN-7499
-
=> [PWN-7499] [PWN-7499, PWN-7498]

p2p_wallet/Scenes/TabBar/TabBarController.swift
https://p2pvalidator.atlassian.net/browse/PWN-7286
-
=> [PWN-7286] Bottomsheet fix

p2p_wallet/Coordinators/SendEmptyCoordinator.swift, p2p_wallet/Coordinators/SolendTopUpForContinueCoordinator.swift, p2p_wallet/Scenes/Main/Receive/ReceiveCoordinator.swift, p2p_wallet/Scenes/Main/Receive/ReceiveView.swift, p2p_wallet/Scenes/Main/Receive/ReceiveViewModel.swift, p2p_wallet/Scenes/Main/SupportedTokens/SupportedTokensCoordinator.swift
=> center icon

p2p_wallet/Scenes/Main/Swap/SwapSettings/View/SwapSettingsView.swift, p2p_wallet/SwiftUI/List/ListBackgroundModifier.swift
https://p2pvalidator.atlassian.net/browse/PWN-7509
-
=> [PWN-7509] ListBackgroundModifier for Swap settings list

p2p_wallet/Services/Storage/UserWalletManager.swift
https://p2pvalidator.atlassian.net/browse/PWN-7539
-
=> [PWN-7539] Reset remembered token addresses after logout

p2p_wallet/Scenes/Main/Send/RecipentSearch/RecipientSearchViewModel.swift, p2p_wallet/Services/FeatureFlags/DefaultFlags.swift, p2p_wallet/Services/FeatureFlags/Features.swift
https://p2pvalidator.atlassian.net/browse/PWN-7641
-
=> [PWN-7641] feat: feature toggler

p2p_wallet/Scenes/Main/TransactionDetailView/TransactionDetailViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-7109
-
=> [PWN-7109] New swap. Информационная штора. Корнер кейс с ошибкой

Podfile.lock, p2p_wallet/Scenes/Main/Swap/State/BusinessLogic/Helpers/JupiterSendTransactionToBlockchain.swift, p2p_wallet/Scenes/Main/Swap/Swap/SwapViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-7664
-
=> [PWN-7664] Feature/pwn 7664 whirpool invalid timestamp

Podfile.lock, p2p_wallet/Scenes/Main/Swap/State/BusinessLogic/Helpers/JupiterSendTransactionToBlockchain.swift, p2p_wallet/Scenes/Main/Swap/Swap/SwapViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-7650
-
=> [PWN-7650] feat: catch blockhash not found error and re-create transaction

p2p_wallet/Extensions/Array+Extensions.swift, p2p_wallet/Scenes/Main/SupportedTokens/SupportedTokensViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-7570
-
=> [PWN-7570] Token sort

Podfile, Podfile.lock, p2p_wallet/Scenes/Main/Swap/State/BusinessLogic/Helpers/JupiterSendTransactionToBlockchain.swift, p2p_wallet/Scenes/Main/Swap/Swap/SwapViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-7650
-
=> [PWN-7650] feat: retry 3 times

p2p_wallet/Scenes/Main/History/New/HistoryViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-7503
-
=> [PWN-7503] Commented pending transactions

p2p_wallet/Coordinators/TabBar/TabBarCoordinator.swift, p2p_wallet/Scenes/Main/Swap/Swap/JupiterSwapCoordinator.swift, p2p_wallet/Scenes/Main/Swap/Swap/SwapView.swift, p2p_wallet/Scenes/Main/Swap/Swap/SwapViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-7497
-
=> [PWN-7497] Dismiss swap screen if it is opened via action panel

p2p_wallet/Scenes/Main/History/New/HistoryViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-7391
-
=> [PWN-7391] fetch and reload sell transactions

p2p_wallet/Coordinators/SendEmptyCoordinator.swift, p2p_wallet/Extensions/SwiftUI/DelayedGesture.swift, p2p_wallet/Extensions/SwiftUI/ScrollOnlyOnOverflow.swift, p2p_wallet/Scenes/Main/Receive/ReceiveView.swift, p2p_wallet/Scenes/Main/Receive/ReceiveViewModel.swift, p2p_wallet/Scenes/Main/Receive/View/ListDividerReceiveView.swift, p2p_wallet/Scenes/Main/Receive/View/ListReceiveItemView.swift, p2p_wallet/Scenes/Main/SupportedTokens/Model/SupportedTokenItem.swift, p2p_wallet/Scenes/Main/SupportedTokens/SupportedTokenNetworksView.swift, p2p_wallet/Scenes/Main/SupportedTokens/SupportedTokensView.swift, p2p_wallet/Scenes/Main/SupportedTokens/SupportedTokensViewModel.swift, p2p_wallet/Scenes/Main/WalletDetail/New/DetailAccountCoordinator.swift
https://p2pvalidator.atlassian.net/browse/PWN-7357
-
=> [PWN-7357] Fixes/pwn 7357

p2p_wallet/AppDelegate.swift, p2p_wallet/Coordinators/SendEmptyCoordinator.swift, p2p_wallet/Coordinators/TabBar/HomeCoordinator.swift, p2p_wallet/Coordinators/TabBar/TabBarCoordinator.swift, p2p_wallet/Extensions/SwiftUI/DelayedGesture.swift, p2p_wallet/Extensions/SwiftUI/ScrollOnlyOnOverflow.swift, p2p_wallet/Scenes/DebugMenu/ViewModel/DebugMenuViewModel.swift, p2p_wallet/Scenes/Main/NewHome/Subview/AccountList/HomeAccountsViewModel.swift, p2p_wallet/Scenes/Main/Receive/ReceiveView.swift, p2p_wallet/Scenes/Main/Receive/ReceiveViewModel.swift, p2p_wallet/Scenes/Main/Receive/View/ListDividerReceiveView.swift, p2p_wallet/Scenes/Main/Receive/View/ListReceiveItemView.swift, p2p_wallet/Scenes/Main/SupportedTokens/Model/SupportedTokenItem.swift, p2p_wallet/Scenes/Main/SupportedTokens/SupportedTokenNetworksView.swift, p2p_wallet/Scenes/Main/SupportedTokens/SupportedTokensView.swift, p2p_wallet/Scenes/Main/SupportedTokens/SupportedTokensViewModel.swift, p2p_wallet/Scenes/Main/WalletDetail/New/DetailAccountCoordinator.swift, p2p_wallet/Services/FeatureFlags/Features.swift, p2p_wallet/Services/NotificationsService/NotificationService.swift, p2p_wallet/Services/NotificationsService/Repository/Dto/Request/DeleteDeviceTokenDto.swift, p2p_wallet/Services/NotificationsService/Repository/Dto/Request/DeviceTokenDto.swift, p2p_wallet/Services/Storage/UserWalletManager.swift
https://p2pvalidator.atlassian.net/browse/PWN-7536
-
=> [PWN-7536] Feature/pwn 7536

p2p_wallet/Resources/Base.lproj/Localizable.strings, p2p_wallet/Resources/en.lproj/Localizable.strings, p2p_wallet/Resources/fr.lproj/Localizable.strings, p2p_wallet/Resources/ru.lproj/Localizable.strings, p2p_wallet/Resources/vi.lproj/Localizable.strings, p2p_wallet/Scenes/Main/Swap/State/JupiterSwapState.swift, p2p_wallet/Scenes/Main/Swap/Swap/SwapViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-7727
- We don't show small amount error. Backend does not return it
https://discord.com/channels/767761912167006292/1050431430871748689/1085907114389688351
=> [PWN-7727] Fix route is not found action button fix

p2p_wallet/Scenes/Main/Common/ChooseItem/ChooseItemService.swift, p2p_wallet/Scenes/Main/Common/ChooseItem/ChooseItemView.swift, p2p_wallet/Scenes/Main/Common/ChooseItem/ChooseItemViewModel.swift, p2p_wallet/Scenes/Main/Send/ChooseSendItem/Services/ChooseSendFeeTokenService.swift, p2p_wallet/Scenes/Main/Send/ChooseSendItem/Services/ChooseSendTokenService.swift, p2p_wallet/Scenes/Main/Swap/ChooseSwapItem/Service/ChooseSwapTokenService.swift, p2p_wallet/SwiftUI/List/WrappedList.swift
https://p2pvalidator.atlassian.net/browse/PWN-7473
-
=> [PWN-7473] New sort for filtered swap tokens

p2p_wallet/Scenes/Main/Common/ChooseItem/ChooseItemViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-7739
-
=> [PWN-7739] Fix wrong state for ChooseItem screen

p2p_wallet/Scenes/TabBar/TabBarController.swift, p2p_wallet/Services/AuthenticationHandler.swift
https://p2pvalidator.atlassian.net/browse/PWN-7758
-
=> [PWN-7758] feat: remove login authentication on DEBUG

p2p_wallet/AppCoordinator/SmartCoordiantor.swift, p2p_wallet/Coordinators/TabBar/TabBarCoordinator.swift, p2p_wallet/Scenes/Main/Swap/State/JupiterSwapStateMachine.swift, p2p_wallet/Scenes/Main/Swap/Swap/JupiterSwapCoordinator.swift, p2p_wallet/Scenes/Main/Swap/Swap/Subviews/Input/SwapInputViewModel.swift, p2p_wallet/Scenes/Main/Swap/Swap/SwapViewModel.swift, p2p_wallet/Scenes/Main/Swap/SwapSettings/Coordinator/SwapSettingsCoordinator.swift, p2p_wallet/Scenes/Main/Swap/SwapSettings/SlipageSettings/SlippageSettingsViewModel.swift, p2p_wallet/Scenes/Main/Swap/SwapSettings/ViewModel/SwapSettingsViewModel.swift, p2p_wallet/Scenes/Main/TransactionDetailView/TransactionDetailCoordinator.swift, p2p_wallet/Scenes/TabBar/TabBarController.swift, p2p_wallet/Services/AnalyticsManager/Events/KeyAppAnalyticsEvent+Extensions.swift, p2p_wallet/Services/AnalyticsManager/Events/KeyAppAnalyticsEvent.swift, p2p_wallet/Services/TransactionHandler/TransactionAnalytics.swift
https://p2pvalidator.atlassian.net/browse/PWN-7723
-
=> [PWN-7723] Fix jupiter swap analytics

p2p_wallet/Scenes/Main/Send/Input/SendInputView.swift, p2p_wallet/Scenes/Main/Send/RecipentSearch/RecipientSearchView.swift, p2p_wallet/Scenes/Main/Send/RecipentSearch/RecipientSearchViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-7642
-
=> [PWN-7642] При вводе имени/адреса реципиента блок "отправка по ссылке" не пропадает

p2p_wallet/Scenes/Main/Wormhole/Send/WormholeSendInputView.swift, p2p_wallet/Scenes/Main/Wormhole/Send/WormholeSendInputViewModel.swift
=> [PWN-7466] Bind SliderActionButton view and data to Wormhole

p2p_wallet/Scenes/Main/Wormhole/Send/WormholeSendInputCoordinator.swift, p2p_wallet/Scenes/Main/Wormhole/Send/WormholeSendInputView.swift
=> [PWN-7466] Token pressed action

p2p_wallet/Scenes/Main/Swap/Swap/Subviews/Input/SwapInputView.swift, p2p_wallet/Scenes/Main/Swap/Swap/Subviews/Input/SwapInputViewModel.swift, p2p_wallet/SwiftUI/TextField/AmountTextField.swift
https://p2pvalidator.atlassian.net/browse/PWN-7511
-
=> [PWN-7511] Правка сброса инпута в textField

p2p_wallet/Resources/AppDelegate/AppDelegate+Injection.swift, p2p_wallet/Scenes/Main/NewHome/Home/ViewModel/HomeViewModel.swift, p2p_wallet/UIKit/SwiftUI/Cells/TokenCellView.swift, p2p_wallet/UIKit/ViewModels/WalletsViewModel/WalletsViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-7805
-
=> [PWN-7805] Fix broken price request to reload it if it failed

p2p_wallet/UIKit/ViewModels/WalletsViewModel/WalletsViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-7805
-
=> [PWN-7805] Apply filter to coingeckoId

p2p_wallet/Resources/Base.lproj/Localizable.strings, p2p_wallet/Resources/en.lproj/Localizable.strings, p2p_wallet/Resources/fr.lproj/Localizable.strings, p2p_wallet/Resources/ru.lproj/Localizable.strings, p2p_wallet/Resources/vi.lproj/Localizable.strings, p2p_wallet/Scenes/Main/History/New/HistoryView.swift, p2p_wallet/Scenes/Main/History/New/HistoryViewModel.swift, p2p_wallet/Scenes/Main/History/New/SentViaLink/SentViaLinkTransactionDetailView.swift, p2p_wallet/Scenes/Main/Send/Input/SendInputView.swift, p2p_wallet/Scenes/Main/Send/Input/SendInputViewModel.swift, p2p_wallet/Scenes/Main/Send/SendViaLink/SendCreateLinkCoordinator.swift, p2p_wallet/Scenes/Main/Send/SendViaLink/SendLinkCreatedView.swift, p2p_wallet/Scenes/Main/Send/SendViaLink/SendLinkCreatedViewModel.swift, p2p_wallet/Scenes/Main/Send/SendСoordinator.swift, p2p_wallet/Services/Defaults.swift
=> PWN-7722, PWN-7701, PWN-7848, PWN-7838, PWN-7854

Packages/KeyAppKit/Sources/KeyAppKitCore/Blockchain/AnyToken.swift, Packages/KeyAppKit/Sources/KeyAppKitCore/Blockchain/CryptoAmount.swift, Packages/KeyAppKit/Sources/KeyAppKitCore/Blockchain/CryptoFormatter.swift, Packages/KeyAppKit/Sources/KeyAppKitCore/Blockchain/CurrencyAmount.swift, Packages/KeyAppKit/Sources/KeyAppKitCore/Blockchain/CurrencyFormatter.swift, Packages/KeyAppKit/Sources/KeyAppKitCore/Blockchain/TokenPrice.swift, Packages/KeyAppKit/Sources/Send/Wormhole/WormholeSendInputStateMachine.swift, p2p_wallet/Resources/AppDelegate/AppDelegate+Injection.swift, p2p_wallet/Scenes/Main/Send/Input/SendInputView.swift, p2p_wallet/Scenes/Main/Send/Input/Subviews/AmountView/SendInputAmountWrapperView.swift, p2p_wallet/Scenes/Main/Wormhole/Send/WormholeSendInputAdapter.swift, p2p_wallet/Scenes/Main/Wormhole/Send/WormholeSendInputView.swift, p2p_wallet/Scenes/Main/Wormhole/Send/WormholeSendInputViewModel.swift, p2p_wallet/SwiftUI/SendSubviews/SendInputAmountView.swift, p2p_wallet/SwiftUI/SendSubviews/SendInputTokenView.swift
https://p2pvalidator.atlassian.net/browse/PWN-7872
-
=> [PWN-7872] Switch button logic in WormholeSendInput screen

p2p_wallet/Services/PriceAPIs/PricesService.swift, p2p_wallet/UIKit/ViewModels/WalletsViewModel/WalletsViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-7877
-
=> [PWN-7877] feat: isPricesAvailable

p2p_wallet/Scenes/Main/Swap/Swap/SwapViewModel.swift, p2p_wallet/Services/TransactionHandler/TransactionHandler+Extensions.swift
https://p2pvalidator.atlassian.net/browse/PWN-7849
-
=> [PWN-7849] Feature/pwn 7849

p2p_wallet/Scenes/Main/Send/Input/Subviews/AmountView/SendInputAmountView.swift, p2p_wallet/Scenes/Main/Send/Input/Subviews/AmountView/SendInputAmountViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-7875
-
=> [PWN-7875] Fix hidden button switch tap when it is unavailable

p2p_wallet/Scenes/Main/Send/Input/Subviews/AmountView/SendInputAmountView.swift, p2p_wallet/Scenes/Main/Send/Input/Subviews/AmountView/SendInputAmountViewModel.swift, p2p_wallet/Scenes/Main/Swap/Swap/Subviews/Input/SwapInputView.swift, p2p_wallet/Services/TransactionHandler/TransactionHandler+Extensions.swift, p2p_wallet/SwiftUI/TextField/AmountTextField.swift
=> feat: moveCursorToTrailingWhenDidBeginEditing

Podfile.lock
https://p2pvalidator.atlassian.net/browse/PWN-7917
-
=> [PWN-7917] feat: update response for sign_relay_transaction

p2p_wallet/AppDelegate.swift, p2p_wallet/Scenes/Main/Send/SendViaLink/ReceiveFundsViaLink/View/LinkWasClaimedView.swift, p2p_wallet/Scenes/Main/Send/SendViaLink/ReceiveFundsViaLink/View/ReceiveFundsViaLinkView.swift, p2p_wallet/Scenes/Main/Send/SendViaLink/ReceiveFundsViaLink/ViewModel/ReceiveFundsViaLinkViewModel.swift, p2p_wallet/Services/GlobalAppState.swift
https://p2pvalidator.atlassian.net/browse/PWN-7659
-
=> [PWN-7659] Bug fixes

Packages/KeyAppKit/Sources/Wormhole/EthereumTransaction+Extensions.swift, Packages/KeyAppKit/Sources/Wormhole/WormholeService.swift, p2p_wallet/Resources/AppDelegate/AppDelegate+Injection.swift
https://p2pvalidator.atlassian.net/browse/PWN-7611
-
=> [PWN-7611] New format added

p2p_wallet/Scenes/Main/History/New/SentViaLink/SentViaLinkTransactionDetailView.swift, p2p_wallet/Scenes/Main/Send/RecipentSearch/RecipientSearchView.swift, p2p_wallet/Scenes/Main/Send/RecipentSearch/Subviews/RecipientCell.swift
https://p2pvalidator.atlassian.net/browse/PWN-7857
-
=> [PWN-7857] fix: multilines

p2p_wallet/Scenes/Main/Send/Input/SendInputViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-7882
-
=> [PWN-7882] fix: optional feeWallet

p2p_wallet/Resources/Base.lproj/Localizable.strings, p2p_wallet/Resources/en.lproj/Localizable.strings, p2p_wallet/Scenes/Main/Send/SendViaLink/ReceiveFundsViaLink/Coordinator/ReceiveFundsViaLinkCoordinator.swift, p2p_wallet/Scenes/Main/Send/SendViaLink/ReceiveFundsViaLink/View/ReceiveFundsViaLinkView.swift, p2p_wallet/Scenes/Main/Send/SendViaLink/ReceiveFundsViaLink/ViewModel/ReceiveFundsViaLinkViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-7939
-
=> [PWN-7939] Убрать дату на экране клейма ссылки

p2p_wallet/Scenes/Main/WalletDetail/New/DetailAccountView.swift
https://p2pvalidator.atlassian.net/browse/PWN-7865
-
=> [PWN-7865] UI fix

.github/workflows/add-devices.yml, .github/workflows/release.yml, fastlane/Fastfile, fastlane/README.md
https://p2pvalidator.atlassian.net/browse/PWN-7997
-
=> [PWN-7997] Feature/pwn 7997 ci

p2p_wallet/Services/SendViaLinkStorage/SendViaLinkTransactionInfo.swift
https://p2pvalidator.atlassian.net/browse/PWN-7955
-
=> [PWN-7955] Feature/pwn 7955

p2p_wallet/RxSwift_Deprecated/PendingTransaction.swift
https://p2pvalidator.atlassian.net/browse/PWN-7930
-
=> [PWN-7930] feat: change pubkey

p2p_wallet/Scenes/Main/ReceiveFundsViaLink/Coordinator/ReceiveFundsViaLinkCoordinator.swift, p2p_wallet/UIKit/Transitions/BottomSheet/PanelTransition.swift, p2p_wallet/UIKit/Transitions/BottomSheet/PresentationController.swift
https://p2pvalidator.atlassian.net/browse/PWN-7841
-
=> [PWN-7841] Крэш мп при открытом итоговом экране отправки по ссылке

p2p_wallet/Scenes/Main/Swap/State/BusinessLogic/Actions/JupiterSwapBusinessLogic+UserWalletsUpdated.swift
https://p2pvalidator.atlassian.net/browse/PWN-7866
-
=> [PWN-7866] Update from and to tokens only if they are from user wallets.

p2p_wallet/Scenes/Main/NewHome/Home/ViewModel/HomeViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-7868
-
=> [PWN-7868] feat: copy name to clipboard if possible

p2p_wallet/Scenes/Main/Swap/Swap/JupiterSwapCoordinator.swift
https://p2pvalidator.atlassian.net/browse/PWN-7803
-
=> [PWN-7803] feat: re open keyboard after settings

p2p_wallet/Coordinators/TabBar/TabBarCoordinator.swift, p2p_wallet/Extensions/UIApplication+Extensions.swift, p2p_wallet/Scenes/TabBar/TabBarViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-7996
-
=> [PWN-7996] Не открывается ссылка при любой открытой шторке

p2p_wallet/Scenes/Main/TransactionDetailView/Model/RendableDetailTransaction+PendingTransaction.swift
https://p2pvalidator.atlassian.net/browse/PWN-7947
-
=> [PWN-7947] Обработка pending receive статуса

p2p_wallet/Scenes/Main/Send/RecipentSearch/RecipientSearchView.swift
https://p2pvalidator.atlassian.net/browse/PWN-7857
-
=> [PWN-7857] fix: long text

p2p_wallet/Scenes/Main/Common/ChooseItem/ChooseItemService.swift, p2p_wallet/Scenes/Main/Common/ChooseItem/ChooseItemViewModel.swift, p2p_wallet/Scenes/Main/Send/ChooseSendItem/Services/ChooseSendFeeTokenService.swift, p2p_wallet/Scenes/Main/Send/ChooseSendItem/Services/ChooseSendTokenService.swift, p2p_wallet/Scenes/Main/Swap/ChooseSwapItem/Service/ChooseSwapTokenService.swift, p2p_wallet/Scenes/Main/Wormhole/ChooseWormholeSend/ChooseWormholeTokenService.swift
https://p2pvalidator.atlassian.net/browse/PWN-7798
-
=> [PWN-7798] Support AnyPublishers data update on ChooseItem Screen

p2p_wallet/Scenes/Main/Send/Input/SendInputView.swift
https://p2pvalidator.atlassian.net/browse/PWN-7783
-
=> [PWN-7783] fix: floating sendButton

p2p_wallet/Scenes/Main/History/New/HistoryViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-7830
-
=> [PWN-7830] Load history from the init

p2p_wallet/Scenes/Main/Send/ChooseSendItem/Extensions/Array+Wallet.swift, p2p_wallet/Scenes/Main/Send/ChooseSendItem/Services/ChooseSendFeeTokenService.swift, p2p_wallet/Scenes/Main/Send/ChooseSendItem/Services/ChooseSendTokenService.swift, p2p_wallet/Scenes/Main/Wormhole/ChooseWormholeSend/ChooseWormholeTokenService.swift
https://p2pvalidator.atlassian.net/browse/PWN-8105
-
=> [PWN-8105] [PWN-8106] Apply sort and filter for wormhole send tokens

p2p_wallet/Extensions/Double+Extensions.swift
https://p2pvalidator.atlassian.net/browse/PWN-8120
-
=> [PWN-8120] Fix zero amount fiat string formation

p2p_wallet/Scenes/Main/Common/ChooseItem/ChooseItemView.swift, p2p_wallet/Scenes/Main/Send/Input/Details/FeePrompt/SendInputFeePromptView.swift, p2p_wallet/UIKit/SwiftUI/Cells/TokenCellView.swift
https://p2pvalidator.atlassian.net/browse/PWN-7705
-
=> [PWN-7705] [PWN-7494] accessibility ids

p2p_wallet/Scenes/Main/NewSettings/Subscenes/PincodeChange/PincodeChangeStartView.swift, p2p_wallet/Scenes/Main/Send/Input/Details/FeePrompt/SendInputFeePromptView.swift
https://p2pvalidator.atlassian.net/browse/PWN-7494
-
=> [PWN-7494][PWN-7495] accessibility identifiers

Podfile, Podfile.lock, p2p_wallet/SwiftUI/Lottie/LottieView.swift, project.yml
https://p2pvalidator.atlassian.net/browse/PWN-7466
- Migrate some pods to spm
=> [PWN-7466] Feature/pwn 7466 migrate some pod

p2p_wallet/Scenes/Main/NewHome/HomeViewModel.swift, p2p_wallet/Scenes/Main/NewHome/Subview/AccountList/HomeAccountsViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-7466
-
=> [PWN-7466] feat: refresh with taskgroup

Packages/KeyAppKit/Sources/KeyAppKitCore/Blockchain/CryptoFormatter.swift
https://p2pvalidator.atlassian.net/browse/PWN-8000
-
=> [PWN-8000] rounding down

p2p_wallet/Scenes/Main/ReceiveFundsViaLink/ClaimSentViaLinkTransaction.swift
=> feat: retrieve fee payer pubkey

p2p_wallet/Extensions/Error+Sentry.swift, p2p_wallet/Services/TransactionHandler/TransactionHandler+Extensions.swift
https://p2pvalidator.atlassian.net/browse/PWN-8181
-
=> [PWN-8181] feat: add error log to sentry

p2p_wallet/Scenes/Main/Send/Input/SendInputView.swift
=> Removed an extra send button

p2p_wallet/Extensions/Double+Extensions.swift, p2p_wallet/Scenes/Main/Send/Input/SendInputView.swift, p2p_wallet/Scenes/Main/Send/Input/SendInputViewModel.swift, p2p_wallet/Scenes/Main/Send/Input/Subviews/AmountView/SendInputAmountView.swift, p2p_wallet/Scenes/Main/Send/Input/Subviews/AmountView/SendInputAmountViewModel.swift, p2p_wallet/Scenes/Main/Send/RecipentSearch/RecipientSearchView.swift, p2p_wallet/Scenes/Main/Swap/State/BusinessLogic/Helpers/JupiterSwapBusinessLogic+UpdatePrices.swift, p2p_wallet/Services/PriceAPIs/PricesService.swift
https://p2pvalidator.atlassian.net/browse/PWN-8006
-
=> [PWN-8006] Put USDT and USDC amount as fiat amount if they are closely equal

p2p_wallet/Resources/Base.lproj/Localizable.strings, p2p_wallet/Resources/en.lproj/Localizable.strings, p2p_wallet/Resources/fr.lproj/Localizable.strings, p2p_wallet/Resources/ru.lproj/Localizable.strings, p2p_wallet/Resources/vi.lproj/Localizable.strings, p2p_wallet/Scenes/CreateOrRestoreWallet/Common/Pincode/Pincode/PincodeViewController.swift, p2p_wallet/Scenes/Main/NewSettings/Subscenes/PincodeChange/PincodeVerifyView.swift
https://p2pvalidator.atlassian.net/browse/PWN-8169
-
=> [PWN-8169] Changed text for forgot pin

p2p_wallet/Scenes/Main/Send/SendViaLink/SendLinkCreatedView.swift
https://p2pvalidator.atlassian.net/browse/PWN-8215
-
=> [PWN-8215] Appended accessibility ids to SendLinkCreatedView

p2p_wallet/Scenes/Main/Wormhole/Send/Subview/WormholeSendFeesCoordinator.swift, p2p_wallet/Scenes/Main/Wormhole/Send/Subview/WormholeSendFeesView.swift, p2p_wallet/Scenes/Main/Wormhole/Send/Subview/WormholeSendFeesViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-8132
-
=> [PWN-8132] Hightlighted subtitle

p2p_wallet/Scenes/Main/Swap/ChooseSwapItem/ChooseSwapTokenCoordinator.swift
https://p2pvalidator.atlassian.net/browse/PWN-8232
-
=> [PWN-8232] Handle self deallocation in ChooseItemView content

.github/workflows/build-test.yml, .github/workflows/release.yml
=> feat: remove grant access to KeyAppUI

p2p_wallet/Coordinators/TabBar/TabBarCoordinator.swift
https://p2pvalidator.atlassian.net/browse/PWN-8240
Fiat amount might be 0, but we should be able to send tokens
=> [PWN-8240] Send flow fix

p2p_wallet/Scenes/Main/SupportedTokens/SupportedTokensView.swift, p2p_wallet/Scenes/Main/SupportedTokens/SupportedTokensViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-8252
-
=> [PWN-8252] [PWN-8253] Fix search field on SupportedTokensView

p2p_wallet/Scenes/Main/WalletDetail/New/AccountDetailsCoordinator.swift
https://p2pvalidator.atlassian.net/browse/PWN-8261
-
=> [PWN-8261] feat(wormhole): fix receive screen

p2p_wallet/Resources/AppDelegate/AppDelegate+Injection.swift
https://p2pvalidator.atlassian.net/browse/PWN-8262
-
=> [PWN-8262] feat(wormhole): fix address pasdding

.github/workflows/add-devices.yml, .github/workflows/build-test.yml, .github/workflows/daily-build-test.yml, .github/workflows/pull_request.yml, .github/workflows/release.yml
https://p2pvalidator.atlassian.net/browse/PWN-8324
-
=> [PWN-8324] feat(ci): deprecate submodules

Packages/KeyAppKit/Sources/KeyAppKitCore/Blockchain/CurrencyFormatter.swift
https://p2pvalidator.atlassian.net/browse/PWN-8274
-
=> [PWN-8274] Display no digits after dot if value is zero

p2p_wallet/Scenes/Main/Buy/BuyView.swift, p2p_wallet/Scenes/Main/Buy/BuyViewModel.swift, p2p_wallet/Scenes/SelectCountry/View/SelectCountryView.swift, p2p_wallet/Scenes/SelectCountry/ViewModel/SelectCountryViewModel.swift, p2p_wallet/Services/AnalyticsManager/Events/KeyAppAnalyticsEvent.swift, p2p_wallet/SwiftUI/SearchBar/SearchBar.swift, p2p_wallet/SwiftUI/Wrappers/WrapperForSearchingView.swift
https://p2pvalidator.atlassian.net/browse/PWN-8142
-
=> [PWN-8142] Country selection analytic

Packages/KeyAppKit/Sources/KeyAppBusiness/Solana/Aggregator/SolanaAccountAggregator.swift, Packages/KeyAppKit/Sources/KeyAppBusiness/Solana/Socket/RealtimeSolanaAccountService.swift, Packages/KeyAppKit/Sources/KeyAppBusiness/Solana/Socket/SolanaNotification.swift, Packages/KeyAppKit/Sources/KeyAppBusiness/Solana/Socket/SolanaWebSocketMethod.swift, Packages/KeyAppKit/Sources/KeyAppBusiness/Solana/SolanaAccountsService.swift, Packages/KeyAppKit/Sources/KeyAppBusiness/Solana/SolanaRealtimeAccount.swift, Packages/KeyAppKit/Sources/KeyAppKitCore/Async/Value/AsyncValue.swift, p2p_wallet/Scenes/DebugMenu/View/DebugMenuView.swift, p2p_wallet/Scenes/DebugMenu/ViewModel/DebugMenuViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-8108
-
=> [PWN-8108] Clean code and add current socket status info to DebugMenu

p2p_wallet/Scenes/Main/Wormhole/Send/WormholeSendInputView.swift, p2p_wallet/Scenes/Main/Wormhole/Send/WormholeSendInputViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-8396
-
=> [PWN-8396] Hide max button if it shouldn't be available

Podfile.lock, p2p_wallet/Info.plist, p2p_wallet/Resources/AppDelegate/AppDelegate+Injection.swift, p2p_wallet/Scenes/Main/NewSettings/Settings/ViewModel/SettingsViewModel.swift, p2p_wallet/Scenes/Main/Swap/Common/Models/JupiterSwapTransaction.swift, p2p_wallet/Scenes/Main/Swap/State/BusinessLogic/Helpers/JupiterSwapBusinessLogic+Logger.swift, p2p_wallet/Scenes/Main/Swap/Swap/SwapViewModel.swift, p2p_wallet/Services/AppInfo.swift, p2p_wallet/Services/SwapErrorLogger/SwapErrorDetail.swift, p2p_wallet/Services/SwapErrorLogger/SwapErrorLogger.swift, p2p_wallet/Services/SwapErrorLogger/SwapErrorLoggerError.swift
https://p2pvalidator.atlassian.net/browse/PWN-8416
-
=> [PWN-8416] Feature/pwn 8416 swap error logger

p2p_wallet/Scenes/Main/Send/Input/SendInputViewModel.swift, p2p_wallet/Scenes/Main/Swap/Swap/JupiterSwapCoordinator.swift, p2p_wallet/Scenes/Main/Swap/Swap/SwapViewModel.swift, p2p_wallet/Scenes/Main/Swap/SwapSettings/Coordinator/SwapSettingsCoordinator.swift, p2p_wallet/Scenes/Main/Swap/SwapSettings/ViewModel/SwapSettingsViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-8314
-
=> [PWN-8314] Fixed incorrect rounding in slippage

p2p_wallet/Scenes/Main/Swap/Swap/SwapViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-8326
-
=> [PWN-8326] Fix wrong formation of whole numbers

p2p_wallet/Scenes/Main/Swap/Swap/SwapViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-8264
-
=> [PWN-8264] Remove reschedule update on every state change

p2p_wallet/Scenes/Main/Swap/Swap/JupiterSwapCoordinator.swift
https://p2pvalidator.atlassian.net/browse/PWN-8265
-
=> [PWN-8265] Do not display largeTitle on Swap screens

p2p_wallet/Extensions/SolanaSwift.APIClientError+Extensions.swift, p2p_wallet/Scenes/Main/Send/Input/SendInputViewModel.swift, p2p_wallet/Scenes/Main/Send/Models/SendAlertLoggerMessage.swift, p2p_wallet/Scenes/Main/Send/Models/SendTransaction.swift, p2p_wallet/Scenes/Main/Send/SendViaLink/SendViaLinkAlertLoggerMessage.swift, p2p_wallet/Scenes/Main/Send/TransactionStatus/SendTransactionStatusView.swift, p2p_wallet/Scenes/Main/Swap/Common/Models/JupiterSwapTransaction.swift
=> Logger alert send send via link

p2p_wallet/Resources/Base.lproj/Localizable.strings, p2p_wallet/Resources/en.lproj/Localizable.strings, p2p_wallet/Resources/fr.lproj/Localizable.strings, p2p_wallet/Resources/ru.lproj/Localizable.strings, p2p_wallet/Resources/vi.lproj/Localizable.strings, p2p_wallet/Scenes/Main/Send/TransactionStatus/SendTransactionStatusViewModel.swift, p2p_wallet/Scenes/Main/TransactionDetailView/Model/RendableDetailTransaction+UserAction.swift
https://p2pvalidator.atlassian.net/browse/PWN-8403
-
=> [PWN-8403] Replace "5-20 seconds" with "few seconds" in Send bottomsheet

p2p_wallet/Scenes/Main/Swap/State/BusinessLogic/Actions/JupiterSwapBusinessLogic+Initialize.swift, p2p_wallet/Scenes/Main/Swap/State/BusinessLogic/Helpers/JupiterSwapBusinessLogic+AutoChoose.swift
https://p2pvalidator.atlassian.net/browse/PWN-7539
- autoChooseToToken logic is only for prechoseFromToken. It does not return the right choice if both tokens are not chosen
=> [PWN-7539] AutoChoose to token correctly

p2p_wallet/Scenes/Main/Swap/Swap/SwapViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-8531
-
=> [PWN-8531] Log analytic event for swap approve button

p2p_wallet/Scenes/DebugMenu/ViewModel/DebugMenuViewModel.swift, p2p_wallet/Scenes/Main/Swap/State/BusinessLogic/JupiterSwapBusinessLogic.swift, p2p_wallet/Scenes/Main/Swap/State/JupiterSwapState.swift, p2p_wallet/Scenes/Main/Swap/State/JupiterSwapStateMachine.swift, p2p_wallet/Scenes/Main/Swap/Swap/Subviews/Input/SwapInputViewModel.swift, p2p_wallet/Scenes/Main/Swap/Swap/SwapViewModel.swift, p2p_wallet/Services/AnalyticsManager/Events/KeyAppAnalyticsEvent+Extensions.swift, p2p_wallet/Services/AnalyticsManager/Events/KeyAppAnalyticsEvent.swift, p2p_wallet/Services/FeatureFlags/Features.swift
https://p2pvalidator.atlassian.net/browse/PWN-8492
-
=> [PWN-8492] Add transaction simulation for each best route

p2p_wallet/Resources/Base.lproj/Localizable.strings, p2p_wallet/Resources/en.lproj/Localizable.strings, p2p_wallet/Resources/fr.lproj/Localizable.strings, p2p_wallet/Resources/ru.lproj/Localizable.strings, p2p_wallet/Resources/vi.lproj/Localizable.strings, p2p_wallet/Scenes/Main/NewHome/HomeViewModel.swift, p2p_wallet/Scenes/Main/NewSettings/NewUsernameViewController.swift
https://p2pvalidator.atlassian.net/browse/PWN-8599
-
=> [PWN-8599] Feature/pwn 8599

Packages/KeyAppKit/Sources/Send/SendViaLink/SendViaLinkDataService.swift, p2p_wallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, p2p_wallet/Scenes/Main/ReceiveFundsViaLink/ClaimSentViaLinkTransaction.swift
https://p2pvalidator.atlassian.net/browse/PWN-8611
-
=> [PWN-8611] feat: change commitment of getClaimableTokenInfo to confirmed

p2p_wallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, project.yml
https://p2pvalidator.atlassian.net/browse/PWN-8586
- https://github.com/marmelroy/PhoneNumberKit/issues/641
=> [PWN-8586] Update PhoneNumberKit dependency

p2p_wallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, p2p_wallet/Services/Logger/LogManager.swift
=> logger fix

p2p_wallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, p2p_wallet/Resources/Base.lproj/Localizable.strings, p2p_wallet/Resources/en.lproj/Localizable.strings, p2p_wallet/Resources/fr.lproj/Localizable.strings, p2p_wallet/Resources/ru.lproj/Localizable.strings, p2p_wallet/Resources/vi.lproj/Localizable.strings, p2p_wallet/Scenes/Main/Receive/Model/InstructionsReceiveCellItem.swift, p2p_wallet/Scenes/Main/Receive/ReceiveViewModel.swift, p2p_wallet/Scenes/Main/Receive/View/InstructionsReceiveView.swift
https://p2pvalidator.atlassian.net/browse/PWN-8631
-
=> [PWN-8631] Feature/pwn 8631

p2p_wallet/Scenes/Main/Wormhole/Claim/Fee/WormholeClaimFeeView.swift
https://p2pvalidator.atlassian.net/browse/PWN-8588
-
=> [PWN-8588] total amount fix

Packages/KeyAppKit/Sources/KeyAppKitCore/Async/Value/AsyncValue.swift
https://p2pvalidator.atlassian.net/browse/PWN-8665
-
=> [PWN-8665] AsyncValue .ready status on error

Packages/KeyAppUI/Sources/KeyAppUI/Button/TextButton/New/NewTextButton.swift, Packages/KeyAppUI/Sources/KeyAppUI/Button/TextButton/New/NewTextButtonAppearance.swift, Packages/KeyAppUI/Sources/KeyAppUI/Button/TextButton/TextButtonStyles.swift, Packages/KeyAppUI/Sources/KeyAppUI/CircularProgressIndicator/NewCircularProgressIndicator.swift, p2p_wallet/SwiftUI/CircularProgressIndicatorView.swift, p2p_wallet/SwiftUI/TextButtonView.swift
https://p2pvalidator.atlassian.net/browse/PWN-8268
-
=> [PWN-8268] Create NewTextButton on SwiftUI

Packages/KeyAppKit/Sources/BankTransfer/Models/RegistrationData.swift, Packages/KeyAppKit/Sources/BankTransfer/Service/BankTransferService.swift, Packages/KeyAppKit/Sources/BankTransfer/Service/StrigaBankTransferService.swift, Packages/KeyAppKit/Sources/BankTransfer/StrigaProvider/IStrigaProvider.swift, Packages/KeyAppKit/Sources/BankTransfer/StrigaProvider/Models/UserDetailsResponse.swift, Packages/KeyAppKit/Sources/BankTransfer/StrigaProvider/StrigaEndpoint.swift, Packages/KeyAppKit/Sources/BankTransfer/StrigaProvider/StrigaProvider.swift, Packages/KeyAppKit/Tests/UnitTests/BankTransferTests/BankTransferServiceTests.swift, Packages/KeyAppKit/Tests/UnitTests/BankTransferTests/Mocks/StrigaProviderMock.swift, Packages/KeyAppKit/Tests/UnitTests/BankTransferTests/StrigaProviderTests.swift
https://p2pvalidator.atlassian.net/browse/PWN-8442
-
=> [PWN-8442] Get user details method

p2p_wallet/Scenes/Main/BankTransfer/StrigaRegistration/FirstStep/StrigaRegistrationFirstStepCoordinator.swift
=> [PWN-8446] Pass correct parent VC to choose country from first reg step

p2p_wallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, p2p_wallet/Scenes/Main/BankTransfer/StrigaRegistration/FirstStep/StrigaRegistrationFirstStepView.swift, p2p_wallet/Scenes/Main/BankTransfer/StrigaRegistration/Subviews/StrigaRegistrationDateTextField.swift, p2p_wallet/Scenes/Main/BankTransfer/StrigaRegistration/Subviews/StrigaRegistrationTextField.swift
=> [PWN-8446] Small ui fixes

p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/EnterPhoneNumberViewModel.swift
=> Remove deprecated code

Packages/KeyAppKit/Sources/BankTransfer/Service/BankTransferService.swift, Packages/KeyAppKit/Sources/BankTransfer/Service/BankTransferServiceImpl.swift, p2p_wallet/Coordinators/TabBar/TabBarCoordinator.swift, p2p_wallet/Scenes/Main/BankTransfer/BankTransferInfoCoordinator.swift, p2p_wallet/Scenes/Main/BankTransfer/BankTransferInfoViewModel.swift, p2p_wallet/Scenes/Main/Topup/Actions/TopupActionsViewModel.swift, p2p_wallet/Scenes/Main/Topup/Actions/TopupCoordinator.swift
=> Loading + navigation changes

Packages/KeyAppKit/Sources/BankTransfer/Mock/MockStrigaLocalProvider.swift, Packages/KeyAppKit/Sources/BankTransfer/Mock/MockStrigaRemoteProvider.swift, Packages/KeyAppKit/Sources/BankTransfer/Striga/Repository/DataProviders/StrigaLocalProvider.swift, p2p_wallet/Resources/AppDelegate/AppDelegate+Injection.swift
=> fix: mocking

Packages/KeyAppKit/Sources/Onboarding/APIGateway/APIGatewayClient.swift, Packages/KeyAppKit/Sources/Onboarding/APIGateway/APIGatewayClientImpl.swift, Packages/KeyAppKit/Sources/Onboarding/APIGateway/APIGatewayClientMockImpl.swift, Packages/KeyAppKit/Sources/Onboarding/APIGateway/APIGatewayClientModel.swift, Packages/KeyAppKit/Sources/Onboarding/APIGateway/Signature.swift, Packages/KeyAppKit/Sources/Onboarding/Common/Models/WalletMetaData.swift, Packages/KeyAppKit/Sources/Onboarding/CreateWalletFlow/CreateWalletState/BindingPhoneNumberState.swift, Packages/KeyAppKit/Sources/Onboarding/RestoreWalletFlow/RestoreCustom/RestoreCustomState.swift, Packages/KeyAppKit/Tests/OnboardingTests/WalletMetaDataTests.swift, p2p_wallet/Coordinators/AppCoordinator/AppCoordinator.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/CreateWalletViewModel.swift, p2p_wallet/Scenes/Main/NewSettings/Subscenes/RecoveryKit/RecoveryKitView.swift, p2p_wallet/Scenes/Main/NewSettings/Subscenes/RecoveryKit/RecoveryKitViewModel.swift, p2p_wallet/Services/Storage/WalletMetadataProvider.swift, p2p_wallet/Services/Storage/WalletMetadataService.swift
https://p2pvalidator.atlassian.net/browse/PWN-8645
-
=> [PWN-8645] Feature/pwn 8645

Packages/KeyAppKit/Sources/BankTransfer/Mock/MockStrigaLocalProvider.swift, Packages/KeyAppKit/Sources/BankTransfer/Service/BankTransferService.swift, Packages/KeyAppKit/Sources/BankTransfer/Service/BankTransferServiceImpl.swift, p2p_wallet/Resources/Base.lproj/Localizable.strings, p2p_wallet/Resources/en.lproj/Localizable.strings, p2p_wallet/Resources/fr.lproj/Localizable.strings, p2p_wallet/Resources/ru.lproj/Localizable.strings, p2p_wallet/Resources/vi.lproj/Localizable.strings, p2p_wallet/Scenes/Main/BankTransfer/StrigaRegistration/FirstStep/StrigaRegistrationFirstStepView.swift, p2p_wallet/Scenes/Main/BankTransfer/StrigaRegistration/FirstStep/StrigaRegistrationFirstStepViewModel.swift, p2p_wallet/Scenes/Main/BankTransfer/StrigaRegistration/SecondStep/StrigaRegistrationSecondStepCoordinator.swift, p2p_wallet/Scenes/Main/BankTransfer/StrigaRegistration/SecondStep/StrigaRegistrationSecondStepView.swift, p2p_wallet/Scenes/Main/BankTransfer/StrigaRegistration/SecondStep/StrigaRegistrationSecondStepViewModel.swift, p2p_wallet/Scenes/Main/BankTransfer/StrigaRegistration/Subviews/StrigaRegistrationPhoneTextField.swift, p2p_wallet/Scenes/Main/Common/ChooseItem/ChooseItemCoordinator.swift, p2p_wallet/Scenes/Main/Topup/Actions/TopupActionsViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-8446
- Second screen validation
- Fix for closing choose item screen
- Phone text field
=> [PWN-8446] [PWN-8649] Validation for second screen and call method

p2p_wallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, p2p_wallet/Scenes/Main/BankTransfer/CountryChoose/ChooseCountryService.swift, p2p_wallet/Scenes/Main/BankTransfer/Info/BankTransferInfoCoordinator.swift, p2p_wallet/Scenes/Main/Common/ChooseItem/ChooseItemCoordinator.swift, p2p_wallet/Scenes/Main/Topup/Actions/TopupActionsViewModel.swift
=> PWN-8783 PWN-8782 PWN-8781

Packages/KeyAppUI/Sources/KeyAppUI/Button/SliderButton/SliderButton.swift, p2p_wallet/Scenes/Main/Send/Input/SendInputView.swift
https://p2pvalidator.atlassian.net/browse/PWN-8745
-
=> [PWN-8745] Fixed not updated text in slider

p2p_wallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, p2p_wallet/Scenes/Main/History/New/SentViaLink/SentViaLinkTransactionDetailView.swift
https://p2pvalidator.atlassian.net/browse/PWN-8622
-
=> [PWN-8622] Appended accessibility for sentViaLink BottomSheet

p2p_wallet/Resources/Base.lproj/Localizable.strings, p2p_wallet/Resources/en.lproj/Localizable.strings, p2p_wallet/Resources/fr.lproj/Localizable.strings, p2p_wallet/Resources/ru.lproj/Localizable.strings, p2p_wallet/Resources/vi.lproj/Localizable.strings, p2p_wallet/Scenes/Actions/ActionsViewModel.swift, p2p_wallet/Scenes/Main/NewHome/Subview/AccountList/HomeAccountsViewModel.swift, p2p_wallet/Scenes/Main/NewHome/Subview/Empty/HomeEmptyView.swift, p2p_wallet/Scenes/Main/NewHome/Subview/Empty/HomeEmptyViewModel.swift, p2p_wallet/Scenes/Main/Topup/Actions/TopupActionsViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-8772
-
=> [PWN-8772] Navigation fix

p2p_wallet/Coordinators/AppCoordinator/AppCoordinator.swift, p2p_wallet/Scenes/Main/NewSettings/Subscenes/RecoveryKit/RecoveryKitView.swift, p2p_wallet/Scenes/Main/NewSettings/Subscenes/RecoveryKit/RecoveryKitViewModel.swift, p2p_wallet/Services/Storage/WalletMetadataService.swift
https://p2pvalidator.atlassian.net/browse/PWN-8645
-
=> [PWN-8645] fix: logics

p2p_wallet/Scenes/Main/BankTransfer/otp/StrigaOTPCoordinator.swift, p2p_wallet/Services/Defaults.swift, p2p_wallet/Services/Storage/UserWalletManager.swift
https://p2pvalidator.atlassian.net/browse/PWN-8809
-
=> [PWN-8809] Fix/pwn 8809

p2p_wallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/CreateWalletCoordinator.swift, p2p_wallet/Services/Auth/SocialService/AppleSocialService.swift, p2p_wallet/Services/Auth/SocialService/SocialServiceError.swift
https://p2pvalidator.atlassian.net/browse/PWN-8722
-
=> [PWN-8722] Suppress alert message on auth cancel

Packages/KeyAppKit/Sources/BankTransfer/Service/BankTransferServiceImpl.swift, p2p_wallet/Scenes/Actions/ActionsViewModel.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/EnterSMSCode/EnterSMSCodeViewModel.swift, p2p_wallet/Scenes/Main/BankTransfer/BankTransferCoordinator.swift, p2p_wallet/Scenes/Main/BankTransfer/Info/BankTransferInfoCoordinator.swift, p2p_wallet/Scenes/Main/BankTransfer/otp/StrigaOTPCompletedView.swift, p2p_wallet/Scenes/Main/BankTransfer/otp/StrigaOTPCoordinator.swift, p2p_wallet/Scenes/Main/BankTransfer/otp/StrigaOTPSuccessCoordinator.swift, p2p_wallet/Scenes/Main/Topup/Actions/TopupActionsViewModel.swift, p2p_wallet/Scenes/Main/Topup/Actions/TopupCoordinator.swift
https://p2pvalidator.atlassian.net/browse/PWN-8788
-
=> [PWN-8788] Fix/pwn 8788

Packages/KeyAppKit/Sources/CountriesAPI/Models.swift, Packages/KeyAppKit/Sources/CountriesAPI/Resources/countries.json, Packages/KeyAppKit/Tests/UnitTests/BankTransferTests/StrigaEndpointTests.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/ChoosePhoneCode/ChoosePhoneCodeViewModel.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/EnterPhoneNumberViewModel.swift, p2p_wallet/Scenes/Main/BankTransfer/StrigaRegistration/FirstStep/StrigaRegistrationFirstStepView.swift, p2p_wallet/Scenes/Main/BankTransfer/StrigaRegistration/SecondStep/StrigaRegistrationSecondStepViewModel.swift
=> feat: update iso31661-alpha3 code for countries

Packages/KeyAppKit/Sources/BankTransfer/Mock/MockStrigaLocalProvider.swift, Packages/KeyAppKit/Sources/BankTransfer/Mock/MockStrigaRemoteProvider.swift, Packages/KeyAppKit/Sources/BankTransfer/Striga/Models/StrigaCreateUserRequest.swift, Packages/KeyAppKit/Sources/BankTransfer/Striga/Models/StrigaUserDetailsResponse.swift, p2p_wallet/Scenes/Main/BankTransfer/StrigaRegistration/FirstStep/StrigaRegistrationFirstStepViewModel.swift, p2p_wallet/Scenes/Main/BankTransfer/StrigaRegistration/SecondStep/StrigaRegistrationSecondStepViewModel.swift
=> [PWN-8165] Fix create user request params passing

p2p_wallet/Scenes/Main/BankTransfer/otp/StrigaOTPCoordinator.swift
=> Check counter before send initial sms

p2p_wallet/Scenes/Main/BankTransfer/otp/StrigaOTPCoordinator.swift
=> Simplified return

p2p_wallet/Scenes/Main/BankTransfer/Info/BankTransferInfoViewModel.swift, p2p_wallet/Services/Defaults.swift, p2p_wallet/Services/Storage/UserWalletManager.swift
https://p2pvalidator.atlassian.net/browse/PWN-8850
-
=> [PWN-8850] save selected country

Packages/KeyAppKit/Sources/BankTransfer/Models/BankTransferRegistrationData.swift, Packages/KeyAppKit/Sources/BankTransfer/Models/UserData.swift, Packages/KeyAppKit/Sources/BankTransfer/Service/BankTransferServiceImpl.swift, Packages/KeyAppKit/Sources/BankTransfer/Striga/Models/StrigaUserDetailsResponse.swift, p2p_wallet/Scenes/Main/BankTransfer/BankTransferCoordinator.swift
=> fix: mobile number

Packages/KeyAppKit/Sources/BankTransfer/Striga/Repository/DataProviders/StrigaLocalProvider.swift, p2p_wallet/Resources/AppDelegate/AppDelegate+Injection.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/Common/Pincode/Pincode/PincodeViewModel.swift, p2p_wallet/Scenes/Main/NewSettings/Settings/ViewModel/SettingsViewModel.swift, p2p_wallet/Scenes/Main/NewSettings/Subscenes/PincodeChange/ForgetPinView.swift, p2p_wallet/Services/Auth/Logout/LogoutService.swift
https://p2pvalidator.atlassian.net/browse/PWN-8848
To be honest, I do not remember @sidorov-panda ' offer about cache so I created LogoutService to make it fast
=> [PWN-8848] LogoutService

p2p_wallet/Scenes/Main/BankTransfer/StrigaRegistration/SecondStep/StrigaRegistrationSecondStepViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-8873
-
=> [PWN-8873] Pre-fill address country with country chosen in onboarding

p2p_wallet/Scenes/Main/TransactionDetailView/Model/RendableDetailTransaction+HistoryTransaction.swift
https://p2pvalidator.atlassian.net/browse/PWN-8662
-
=> [PWN-8662] feat: transaction detail

p2p_wallet/Services/CountriesAPI+DefaultRegion.swift
=> Remove deprecated code for country detection

p2p_wallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, p2p_wallet/Scenes/Main/NewHome/HomeView.swift, p2p_wallet/Scenes/Main/NewHome/Subview/AccountList/HomeAccountsView.swift, p2p_wallet/Scenes/Main/NewHome/Subview/Empty/HomeEmptyView.swift, p2p_wallet/SwiftUI/ActionsPanel/ActionsPanelView.swift
https://p2pvalidator.atlassian.net/browse/PWN-8700
-
=> [PWN-8700] Feature/pwn 8700

p2p_wallet/Scenes/Main/BankTransfer/StrigaRegistration/Subviews/StrigaRegistrationPhoneTextField.swift, p2p_wallet/Scenes/Main/BankTransfer/otp/StrigaOTPCoordinator.swift
=> PWN-8864 PWN-8876

Packages/KeyAppKit/Sources/BankTransfer/Models/BankTransferError.swift, Packages/KeyAppKit/Sources/BankTransfer/Striga/Repository/DataProviders/StrigaRemoteProviderImpl.swift, p2p_wallet/Resources/Base.lproj/Localizable.strings, p2p_wallet/Resources/en.lproj/Localizable.strings, p2p_wallet/Resources/fr.lproj/Localizable.strings, p2p_wallet/Resources/ru.lproj/Localizable.strings, p2p_wallet/Resources/vi.lproj/Localizable.strings, p2p_wallet/Scenes/Main/BankTransfer/otp/Error/StrigaOTPHardErrorView.swift, p2p_wallet/Scenes/Main/BankTransfer/otp/StrigaOTPCoordinator.swift, p2p_wallet/SwiftUI/HardErrorView.swift
https://p2pvalidator.atlassian.net/browse/PWN-8750
-
=> [PWN-8750] Error handling

p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/ChoosePhoneCode/ChoosePhoneCodeView.swift, p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/ChoosePhoneCode/ChoosePhoneCodeViewModel.swift, p2p_wallet/Scenes/Main/Common/ChooseItem/ChooseItemView.swift, p2p_wallet/Scenes/Main/Common/ChooseItem/ChooseItemViewModel.swift, p2p_wallet/SwiftUI/FocusedTexts/SearchField.swift
=> [NO-TASK] Use only FocusState

Packages/KeyAppKit/Sources/Onboarding/Common/Models/WalletMetaData.swift
https://p2pvalidator.atlassian.net/browse/PWN-8967
- Change timestamp format to integer
=> [PWN-8967] Feature/pwn 8967 timestamp interger

Packages/KeyAppKit/Sources/BankTransfer/Repository/BankTransferUserDataRepository.swift, Packages/KeyAppKit/Sources/BankTransfer/Service/BankTransferServiceImpl.swift, Packages/KeyAppKit/Sources/BankTransfer/Striga/Repository/StrigaBankTransferUserDataRepository.swift
https://p2pvalidator.atlassian.net/browse/PWN-8968
-
=> [PWN-8968] Show phoneNumber for first time if user is already registered

p2p_wallet/Scenes/Main/BankTransfer/otp/StrigaOTPCoordinator.swift
=> Fixed error handling

p2p_wallet/Scenes/Main/BankTransfer/KYC/KYCCoordinator.swift
https://p2pvalidator.atlassian.net/browse/PWN-8961
-
=> [PWN-8961] Dismiss KYC Coordinator when documents are pending

Packages/KeyAppKit/Sources/BankTransfer/Striga/Repository/DataProviders/StrigaRemoteProviderImpl.swift
- I think we should remove all fields we do not use for now until it is necessary for any logic
=> [PWN-8165] Remove not necessary fields

Packages/KeyAppKit/Sources/BankTransfer/Striga/Mock/MockStrigaRemoteProvider.swift, Packages/KeyAppKit/Sources/BankTransfer/Striga/Models/StrigaEndpoint.swift, Packages/KeyAppKit/Sources/BankTransfer/Striga/Models/StrigaTransactionConfirmOTPResponse.swift, Packages/KeyAppKit/Sources/BankTransfer/Striga/Models/StrigaTransactionResendOTPResponse.swift, Packages/KeyAppKit/Sources/BankTransfer/Striga/Models/StrigaWalletSendResponse.swift, Packages/KeyAppKit/Sources/BankTransfer/Striga/Repository/DataProviders/StrigaRemoteProvider.swift, Packages/KeyAppKit/Sources/BankTransfer/Striga/Repository/DataProviders/StrigaRemoteProviderImpl.swift, Packages/KeyAppKit/Tests/UnitTests/BankTransferTests/StrigaEndpointTests.swift, Packages/KeyAppKit/Tests/UnitTests/BankTransferTests/StrigaRemoteProviderTests.swift
https://p2pvalidator.atlassian.net/browse/PWN-8894
-
=> [PWN-8894] [PWN-8896] [PWN-8975] Striga onchain withdrawal method added

p2p_wallet/Services/GlobalAppState.swift
https://p2pvalidator.atlassian.net/browse/PWN-9017
- Alena asked for this
=> [PWN-9017] Make dev striga endpoint default to test env

p2p_wallet/Scenes/Main/BankTransfer/otp/StrigaOTPCoordinator.swift
https://p2pvalidator.atlassian.net/browse/PWN-9038
-
=> [PWN-9038] feat: disable first time otp

p2p_wallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, p2p_wallet/Resources/Base.lproj/Localizable.strings, p2p_wallet/Resources/en.lproj/Localizable.strings, p2p_wallet/Resources/fr.lproj/Localizable.strings, p2p_wallet/Resources/ru.lproj/Localizable.strings, p2p_wallet/Resources/vi.lproj/Localizable.strings, p2p_wallet/Scenes/Main/NewSettings/Settings/View/SettingsView.swift, p2p_wallet/Scenes/Main/NewSettings/Subscenes/RecoveryKit/RecoveryKitCoordinator.swift, p2p_wallet/Scenes/Main/NewSettings/Subscenes/RecoveryKit/RecoveryKitView.swift
https://p2pvalidator.atlassian.net/browse/PWN-8846
-
=> [PWN-8846] feat: edit texts

p2p_wallet/Scenes/Main/Send/RecipentSearch/Subviews/RecipientSearchField.swift
https://p2pvalidator.atlassian.net/browse/PWN-8732
-
=> [PWN-8732] QR code button touch area increased

Packages/KeyAppKit/Sources/History/HistoryServiceTransactionModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-8606
-
=> [PWN-8606] Transaction date parsing fix

p2p_wallet/Scenes/Main/History/New/SentViaLink/SentViaLinkHistoryCoordinator.swift, p2p_wallet/Scenes/Main/History/New/SentViaLink/SentViaLinkHistoryTransactionView.swift, p2p_wallet/Scenes/Main/History/New/SentViaLink/SentViaLinkHistoryView.swift
https://p2pvalidator.atlassian.net/browse/PWN-8705
-
=> [PWN-8705] feat: ui in SendViaLinkHistoryView

p2p_wallet/Extensions/RemoteConfig+Extensions.swift
=> feat: remove header

Packages/KeyAppKit/Sources/BankTransfer/Models/UserAccounts.swift, Packages/KeyAppKit/Sources/BankTransfer/Repository/BankTransferUserDataRepository.swift, Packages/KeyAppKit/Sources/BankTransfer/Service/BankTransferService.swift, Packages/KeyAppKit/Sources/BankTransfer/Service/BankTransferServiceImpl.swift, Packages/KeyAppKit/Sources/BankTransfer/Striga/Mock/MockStrigaRemoteProvider.swift, Packages/KeyAppKit/Sources/BankTransfer/Striga/Models/StrigaEnrichedAccountResponse.swift, Packages/KeyAppKit/Sources/BankTransfer/Striga/Models/StrigaGetAllWalletsResponse.swift, Packages/KeyAppKit/Sources/BankTransfer/Striga/Repository/DataProviders/StrigaRemoteProvider.swift, Packages/KeyAppKit/Sources/BankTransfer/Striga/Repository/DataProviders/StrigaRemoteProviderImpl.swift, Packages/KeyAppKit/Sources/BankTransfer/Striga/Repository/StrigaBankTransferUserDataRepository.swift, p2p_wallet/Scenes/Main/BankTransfer/IBANDetails/IBANDetailsViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-8741
-
=> [PWN-8741] Fix enrichAccount response models. Get user account indices

Packages/KeyAppKit/Sources/BankTransfer/Models/UserAccounts.swift, Packages/KeyAppKit/Sources/BankTransfer/Models/UserCommonInfo.swift, Packages/KeyAppKit/Sources/BankTransfer/Models/UserData.swift, Packages/KeyAppKit/Sources/BankTransfer/Models/UserWallet.swift, Packages/KeyAppKit/Sources/BankTransfer/Repository/BankTransferUserDataRepository.swift, Packages/KeyAppKit/Sources/BankTransfer/Repository/DataProviders/CommonInfoLocalProvider.swift, Packages/KeyAppKit/Sources/BankTransfer/Service/BankTransferService.swift, Packages/KeyAppKit/Sources/BankTransfer/Service/BankTransferServiceImpl.swift, Packages/KeyAppKit/Sources/BankTransfer/Striga/Mock/MockStrigaLocalProvider.swift, Packages/KeyAppKit/Sources/BankTransfer/Striga/Repository/DataProviders/StrigaLocalProvider.swift, Packages/KeyAppKit/Sources/BankTransfer/Striga/Repository/StrigaBankTransferUserDataRepository.swift, Packages/KeyAppKit/Tests/UnitTests/BankTransferTests/StrigaRemoteProviderTests.swift, p2p_wallet/Injection/Resolver+registerAllServices.swift, p2p_wallet/Scenes/Main/BankTransfer/BankTransferCoordinator.swift, p2p_wallet/Scenes/Main/BankTransfer/IBANDetails/IBANDetailsCoordinator.swift, p2p_wallet/Scenes/Main/BankTransfer/IBANDetails/IBANDetailsView.swift, p2p_wallet/Scenes/Main/BankTransfer/IBANDetails/IBANDetailsViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-8902
-
=> [PWN-8902] Local state

p2p_wallet/Scenes/Main/BankTransfer/StrigaRegistration/FirstStep/StrigaRegistrationFirstStepView.swift, p2p_wallet/Scenes/Main/BankTransfer/StrigaRegistration/FirstStep/StrigaRegistrationFirstStepViewModel.swift, p2p_wallet/Scenes/Main/BankTransfer/StrigaRegistration/Models/StrigaRegistrationField.swift, p2p_wallet/Scenes/Main/BankTransfer/StrigaRegistration/SecondStep/StrigaRegistrationSecondStepView.swift, p2p_wallet/Scenes/Main/BankTransfer/StrigaRegistration/SecondStep/StrigaRegistrationSecondStepViewModel.swift, p2p_wallet/Scenes/Main/BankTransfer/StrigaRegistration/Subviews/StrigaRegistrationDateTextField.swift, p2p_wallet/Scenes/Main/BankTransfer/StrigaRegistration/Subviews/StrigaRegistrationPhoneTextField.swift, p2p_wallet/Scenes/Main/BankTransfer/StrigaRegistration/Subviews/StrigaRegistrationSectionView.swift, p2p_wallet/Scenes/Main/BankTransfer/StrigaRegistration/Subviews/StrigaRegistrationTextField.swift
https://p2pvalidator.atlassian.net/browse/PWN-8949
- I do not like that I had to multiply focus logic three times : on StrigaRegistrationDateTextField, StrigaRegistrationPhoneTextField and StrigaRegistrationTextField but I don't have a clue how to make it easier. Do you have any thoughts?
=> [PWN-8949] Update textfields focus states. Handle next and done buttons

p2p_wallet/Scenes/Main/BankTransfer/BankTransferCoordinator.swift, p2p_wallet/Scenes/Main/BankTransfer/Claim/BankTransferClaimCoordinator.swift, p2p_wallet/Scenes/Main/BankTransfer/otp/StrigaOTPCoordinator.swift
https://p2pvalidator.atlassian.net/browse/PWN-8909
-
=> [PWN-8909] Feature/pwn 8909

Packages/KeyAppKit/Sources/KeyAppKitCore/Blockchain/CurrencyFormatter.swift, p2p_wallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, p2p_wallet/Scenes/Main/Wormhole/Send/WormholeSendInputViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-8310
-
=> [PWN-8310] Formatter fix

Packages/KeyAppKit/Sources/BankTransfer/Striga/Repository/DataProviders/StrigaRemoteProviderImpl.swift
https://p2pvalidator.atlassian.net/browse/PWN-8970
-
=> [PWN-8970] Handle Resend SMS error

p2p_wallet/Scenes/Main/Swap/State/BusinessLogic/Helpers/JupiterSwapBusinessLogic+Calculate.swift, p2p_wallet/Scenes/Main/Swap/State/BusinessLogic/JupiterSwapBusinessLogic.swift, p2p_wallet/Scenes/Main/Swap/State/JupiterSwapState.swift
https://p2pvalidator.atlassian.net/browse/PWN-9118
-
=> [PWN-9118] feat: re-calculate the amountTo after removing failed routes

Packages/KeyAppKit/Sources/Jupiter/Models/Route.swift
https://p2pvalidator.atlassian.net/browse/PWN-9133
-
=> [PWN-9133] feat: Route Codable

Packages/KeyAppKit/Sources/BankTransfer/Repository/BankTransferUserDataRepository.swift, Packages/KeyAppKit/Sources/BankTransfer/Service/BankTransferServiceImpl.swift, Packages/KeyAppKit/Sources/BankTransfer/Striga/Repository/StrigaBankTransferUserDataRepository.swift
https://p2pvalidator.atlassian.net/browse/PWN-9120
-
=> [PWN-9120] Put correct phone number if there is none on first entry to striga

p2p_wallet/Common/Services/Defaults.swift, p2p_wallet/Common/Services/Storage/UserWalletManager.swift, p2p_wallet/Scenes/Main/BankTransfer/StrigaRegistration/SecondStep/StrigaRegistrationSecondStepViewModel.swift, p2p_wallet/Scenes/Main/BankTransfer/otp/StrigaOTPCoordinator.swift
https://p2pvalidator.atlassian.net/browse/PWN-9049
-
=> [PWN-9049] Handle timer from the first time if it was zero. Make it nil as default

Packages/KeyAppKit/Sources/BankTransfer/Models/UserData.swift, Packages/KeyAppKit/Sources/BankTransfer/Repository/BankTransferUserDataRepository.swift, Packages/KeyAppKit/Sources/BankTransfer/Service/BankTransferServiceImpl.swift, Packages/KeyAppKit/Sources/BankTransfer/Striga/Repository/StrigaBankTransferUserDataRepository.swift, Packages/KeyAppUI/Sources/KeyAppUI/Button/TextButton/New/NewTextButton.swift, Packages/KeyAppUI/Sources/KeyAppUI/Button/TextButton/TextButtonStyles.swift, Packages/KeyAppUI/Sources/KeyAppUI/CircularProgressIndicator/NewCircularProgressIndicator.swift, p2p_wallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, p2p_wallet/Scenes/Main/BankTransfer/BankTransferCoordinator.swift, p2p_wallet/Scenes/Main/BankTransfer/IBANDetails/IBANDetailsCoordinator.swift, p2p_wallet/Scenes/Main/BankTransfer/IBANDetails/IBANDetailsViewModel.swift, p2p_wallet/Scenes/Main/NewHome/Model/HomeBannerParameters.swift, p2p_wallet/Scenes/Main/NewHome/Subview/AccountList/HomeAccountsViewModel.swift, p2p_wallet/Scenes/Main/NewHome/Subview/Banners/HomeBannerView.swift, p2p_wallet/Scenes/Main/NewHome/Subview/Banners/HomeSmallBannerView.swift, p2p_wallet/Scenes/Main/NewHome/Subview/Empty/HomeEmptyViewModel.swift, p2p_wallet/Scenes/Main/Topup/Actions/TopupActionsViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-8741
-
=> [PWN-8741] Handle loading and error states on home banners

p2p_wallet/Scenes/Main/NewHome/HomeViewModel.swift
=> Fixed loading

Packages/KeyAppKit/Package.swift
=> [PWN-8165] Fix missed package

p2p_wallet/Scenes/Main/BankTransfer/StrigaRegistration/FirstStep/StrigaRegistrationFirstStepViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-8863
-
=> [PWN-8863] Do not select place of birth from info bottom sheet

Packages/KeyAppKit/Sources/BankTransfer/Striga/Models/StrigaWalletSendResponse.swift, Packages/KeyAppKit/Sources/BankTransfer/UserAction/StrigaBankTransferUserActionConsumer.swift, p2p_wallet/Scenes/Main/NewHome/HomeCoordinator.swift, p2p_wallet/Scenes/Main/NewHome/Subview/AccountList/HomeAccountsViewModel.swift
=> UserAction fixes

p2p_wallet/Scenes/Main/BankTransfer/otp/StrigaOTPCoordinator.swift, p2p_wallet/Scenes/Web3Auth/Onboarding/CreateWallet/Steps/EnterPhoneNumber/EnterSMSCode/EnterSMSCodeViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-9049
-
=> [PWN-9049] Handle resend request only once

Packages/KeyAppKit/Sources/BankTransfer/Striga/Mock/MockStrigaLocalProvider.swift, Packages/KeyAppKit/Sources/BankTransfer/Striga/Mock/MockStrigaRemoteProvider.swift, Packages/KeyAppKit/Sources/BankTransfer/Striga/Models/StrigaEndpoint.swift, Packages/KeyAppKit/Sources/BankTransfer/Striga/Models/StrigaWalletSendResponse.swift, Packages/KeyAppKit/Sources/BankTransfer/Striga/Models/StrigaWhitelistAddressResponse.swift, Packages/KeyAppKit/Sources/BankTransfer/Striga/Repository/DataProviders/StrigaLocalProvider.swift, Packages/KeyAppKit/Sources/BankTransfer/Striga/Repository/DataProviders/StrigaRemoteProvider.swift, Packages/KeyAppKit/Sources/BankTransfer/Striga/Repository/DataProviders/StrigaRemoteProviderImpl.swift, Packages/KeyAppKit/Sources/BankTransfer/Striga/Repository/StrigaBankTransferUserDataRepository.swift, Packages/KeyAppKit/Sources/BankTransfer/UserAction/StrigaBankTransferUserActionConsumer.swift, p2p_wallet/Injection/Resolver+registerAllServices.swift, p2p_wallet/Scenes/Main/NewHome/HomeViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-9111
-
=> [PWN-9111] Whitelist

p2p_wallet/Scenes/Main/NewHome/HomeViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-8906
-
=> [PWN-8906] Update fix

p2p_wallet/Common/Services/Defaults.swift, p2p_wallet/Common/Services/Storage/UserWalletManager.swift, p2p_wallet/Scenes/Main/NewHome/Model/HomeBannerParameters.swift, p2p_wallet/Scenes/Main/NewHome/Model/HomeBannerVisibility.swift, p2p_wallet/Scenes/Main/NewHome/Subview/AccountList/HomeAccountsView.swift, p2p_wallet/Scenes/Main/NewHome/Subview/AccountList/HomeAccountsViewModel.swift, p2p_wallet/Scenes/Main/NewHome/Subview/Banners/HomeBannerView.swift, p2p_wallet/Scenes/Main/NewHome/Subview/Empty/HomeEmptyViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-9167
-
=> [PWN-9167] Close small home banner on first tap and remember this state

p2p_wallet/Scenes/Main/BankTransfer/Info/BankTransferInfoCoordinator.swift, p2p_wallet/Scenes/Main/BankTransfer/Info/BankTransferInfoViewModel.swift, p2p_wallet/Scenes/Main/BankTransfer/StrigaRegistration/FirstStep/StrigaRegistrationFirstStepCoordinator.swift, p2p_wallet/Scenes/Main/BankTransfer/StrigaRegistration/FirstStep/StrigaRegistrationFirstStepView.swift, p2p_wallet/Scenes/Main/BankTransfer/StrigaRegistration/FirstStep/StrigaRegistrationFirstStepViewModel.swift, p2p_wallet/Scenes/Main/BankTransfer/StrigaRegistration/SecondStep/StrigaRegistrationSecondStepViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-8912
-
=> [PWN-8912] Change setup of address country on second striga registration

Packages/KeyAppKit/Sources/BankTransfer/Striga/Repository/StrigaBankTransferUserDataRepository.swift
https://p2pvalidator.atlassian.net/browse/PWN-9219
-
=> [PWN-9219] availableBalance fix

p2p_wallet/Common/Extensions/NSError+Extensions.swift, p2p_wallet/Scenes/Main/BankTransfer/StrigaRegistration/SecondStep/StrigaRegistrationSecondStepViewModel.swift, p2p_wallet/Scenes/Web3Auth/Onboarding/CreateWallet/Steps/EnterPhoneNumber/EnterSMSCode/EnterSMSCodeViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-9032
-
=> [PWN-9032] Handle internet connection error on 2 striga screens

p2p_wallet/Scenes/Main/BankTransfer/otp/StrigaOTPCoordinator.swift
https://p2pvalidator.atlassian.net/browse/PWN-9032
-
=> [PWN-9032] Display no connection error on start of striga otp

p2p_wallet/Scenes/Main/History/New/Model/RendableListTransactionItem+PendingTransaction.swift
https://p2pvalidator.atlassian.net/browse/PWN-8910
-
=> [PWN-8910] Feature/pwn 8910

p2p_wallet/Scenes/Main/NewHome/Subview/AccountList/HomeAccountsViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-9167
-
=> [PWN-9167] Do not close banner on special kyc statuses

Packages/KeyAppKit/Sources/BankTransfer/Service/BankTransferServiceImpl.swift
https://p2pvalidator.atlassian.net/browse/PWN-9235
-
=> [PWN-9235] Use current value and error while work with fetching state

fastlane/Fastfile
https://p2pvalidator.atlassian.net/browse/PWN-9198
-
=> [PWN-9198] feat: re-enable sentry_upload_dsym

p2p_wallet/Common/Services/NotificationsService/NotificationService.swift
https://p2pvalidator.atlassian.net/browse/PWN-8805
-
=> [PWN-8805] fix: SnackBar

p2p_wallet/Scenes/Main/NewHome/Subview/AccountList/HomeAccountsViewModel.swift, p2p_wallet/Scenes/Main/NewHome/Subview/Empty/HomeEmptyViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-9213
-
=> [PWN-9213] Send tap subject check after reload of bank transfer

Packages/KeyAppKit/Sources/BankTransfer/Models/UserWallet.swift, Packages/KeyAppKit/Sources/BankTransfer/Striga/Mock/MockStrigaRemoteProvider.swift, Packages/KeyAppKit/Sources/BankTransfer/Striga/Models/StrigaEndpoint.swift, Packages/KeyAppKit/Sources/BankTransfer/Striga/Models/StrigaWhitelistAddressResponse.swift, Packages/KeyAppKit/Sources/BankTransfer/Striga/Repository/DataProviders/StrigaLocalProvider.swift, Packages/KeyAppKit/Sources/BankTransfer/Striga/Repository/DataProviders/StrigaRemoteProvider.swift, Packages/KeyAppKit/Sources/BankTransfer/Striga/Repository/DataProviders/StrigaRemoteProviderImpl.swift, Packages/KeyAppKit/Sources/BankTransfer/Striga/Repository/StrigaBankTransferUserDataRepository.swift, p2p_wallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, p2p_wallet/Scenes/Main/BankTransfer/Claim/BankTransferClaimCoordinator.swift, p2p_wallet/Scenes/Main/NewHome/HomeViewModel.swift, p2p_wallet/Scenes/Main/NewHome/Service/HomeAccountsSynchronisationService.swift, p2p_wallet/Scenes/Main/NewHome/Subview/AccountList/HomeAccountsViewModel.swift, p2p_wallet/Scenes/Main/NewHome/Subview/AccountList/Model/BankTransferRenderableAccount.swift, p2p_wallet/Scenes/Main/NewHome/Subview/Empty/HomeEmptyViewModel.swift
=> Flow fixes

Packages/KeyAppKit/Sources/BankTransfer/Repository/BankTransferUserDataRepository.swift
=> Remove unnecessary methods

Packages/KeyAppKit/Sources/KeyAppStateMachine/Dispatcher.swift, Packages/KeyAppKit/Sources/KeyAppStateMachine/StateMachine.swift, Packages/KeyAppKit/Tests/UnitTests/KeyAppStateMachineTests/RecruitmentStateMachine/RecruitmentDispatcher.swift
- I have checked tests, they don't fail
=> Add optional intermediate states to StateMachine

.github/workflows/key-app-kit-unit-test.yml
=> Add bankTransferTests on pr checks

Packages/KeyAppKit/Sources/BankTransfer/Service/BankTransferServiceImpl.swift, Packages/KeyAppKit/Sources/BankTransfer/Striga/Repository/DataProviders/StrigaLocalProvider.swift, Packages/KeyAppKit/Sources/BankTransfer/Striga/Repository/StrigaBankTransferUserDataRepository.swift, Packages/KeyAppKit/Tests/UnitTests/BankTransferTests/StrigaEndpointTests.swift
=> request optimizations

Packages/KeyAppKit/Sources/Send/Input/Services/SwapServiceWrapper.swift
https://p2pvalidator.atlassian.net/browse/PWN-9234
-
=> [PWN-9234] Feature/pwn 9234 fix

Packages/KeyAppKit/Sources/BankTransfer/Striga/Models/StrigaExchangeRatesResponse.swift, p2p_wallet/Common/Models/WalletActionType.swift, p2p_wallet/Resources/Base.lproj/Localizable.strings, p2p_wallet/Resources/en.lproj/Localizable.strings, p2p_wallet/Resources/fr.lproj/Localizable.strings, p2p_wallet/Resources/ru.lproj/Localizable.strings, p2p_wallet/Resources/vi.lproj/Localizable.strings, p2p_wallet/Scenes/Main/BankTransfer/BankTransferCoordinator.swift, p2p_wallet/Scenes/Main/BankTransfer/Info/BankTransferInfoCoordinator.swift, p2p_wallet/Scenes/Main/BankTransfer/StrigaRegistration/FirstStep/StrigaRegistrationFirstStepCoordinator.swift, p2p_wallet/Scenes/Main/BankTransfer/WithdrawCalculator/Models/WithdrawCalculatorAction.swift, p2p_wallet/Scenes/Main/BankTransfer/WithdrawCalculator/Subviews/WithdrawCalculatorSwapIcon.swift, p2p_wallet/Scenes/Main/BankTransfer/WithdrawCalculator/WithdrawCalculatorCoordinator.swift, p2p_wallet/Scenes/Main/BankTransfer/WithdrawCalculator/WithdrawCalculatorView.swift, p2p_wallet/Scenes/Main/BankTransfer/WithdrawCalculator/WithdrawCalculatorViewModel.swift, p2p_wallet/Scenes/Main/BankTransfer/otp/StrigaOTPCoordinator.swift, p2p_wallet/Scenes/Main/NewHome/HomeCoordinator.swift, p2p_wallet/Scenes/Main/NewHome/Subview/AccountList/HomeAccountsViewModel.swift, p2p_wallet/Scenes/Main/Swap/Swap/Subviews/Input/SwapInputView.swift, p2p_wallet/Scenes/Main/Swap/Swap/Subviews/Input/SwapInputViewModel.swift, p2p_wallet/UI/SwiftUI/FocusedTexts/BigInputView.swift, p2p_wallet/UI/SwiftUI/TextField/AmountTextField.swift
https://p2pvalidator.atlassian.net/browse/PWN-9256
-
=> [PWN-9256] View, calculation and rates logic

Packages/KeyAppKit/Sources/BankTransfer/Service/BankTransferService.swift, Packages/KeyAppKit/Sources/BankTransfer/Service/BankTransferServiceImpl.swift, Packages/KeyAppKit/Sources/BankTransfer/Striga/Models/StrigaWithdrawalInfo.swift, Packages/KeyAppKit/Sources/BankTransfer/Striga/Repository/DataProviders/StrigaLocalProvider.swift, Packages/KeyAppKit/Sources/BankTransfer/Striga/Repository/StrigaBankTransferUserDataRepository.swift
https://p2pvalidator.atlassian.net/browse/PWN-9260
-
=> [PWN-9260] Code cleanup

p2p_wallet/Scenes/Main/BankTransfer/WithdrawCalculator/WithdrawCalculatorCoordinator.swift, p2p_wallet/Scenes/Main/BankTransfer/WithdrawCalculator/WithdrawCalculatorViewModel.swift
=> Open withdrawal with mock data

Packages/KeyAppKit/Sources/TransactionParser/Model/Info/StrigaWithdrawInfo.swift, p2p_wallet/Common/Models/PendingTransaction.swift, p2p_wallet/Scenes/Main/BankTransfer/Claim/BankTransferClaimCoordinator.swift, p2p_wallet/Scenes/Main/BankTransfer/Claim/StrigaClaimTransaction.swift, p2p_wallet/Scenes/Main/BankTransfer/Withdraw/WithdrawCoordinator.swift, p2p_wallet/Scenes/Main/BankTransfer/WithdrawCalculator/WithdrawCalculatorCoordinator.swift, p2p_wallet/Scenes/Main/TransactionDetailView/Model/RendableDetailTransaction+PendingTransaction.swift, p2p_wallet/Scenes/Main/TransactionDetailView/TransactionDetailViewModel.swift
=> DEMO build

p2p_wallet/Scenes/Main/BankTransfer/WithdrawCalculator/WithdrawCalculatorViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-9256
-
=> [PWN-9256] Update only toAmount if rates are changed

p2p_wallet/Scenes/Main/BankTransfer/WithdrawCalculator/WithdrawCalculatorViewModel.swift
=> Fix min amount from 1 to 10 EUR

p2p_wallet/Scenes/Main/BankTransfer/WithdrawCalculator/WithdrawCalculatorViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-9330
-
=> [PWN-9330] Handle empty response

p2p_wallet/AppDelegate/AppDelegateProxyService/AppflyerAppDelegateService.swift, p2p_wallet/Common/Extensions/AnalyticsManager/AnalyticsManager+ErrorHandling.swift, p2p_wallet/Common/Extensions/Error+Extensions.swift, p2p_wallet/Common/Services/AnalyticsManager/Events/KeyAppAnalyticsEvent.swift, p2p_wallet/Common/Services/CreateName/CreateNameService.swift, p2p_wallet/Common/Services/Logger/DefaultLogManager+ErrorObserver.swift, p2p_wallet/Common/Services/Logger/LogManager.swift, p2p_wallet/Common/Services/TransactionHandler/TransactionHandler+Extensions.swift, p2p_wallet/Scenes/Main/ReceiveFundsViaLink/ClaimSentViaLinkTransaction.swift, p2p_wallet/Scenes/Main/ReceiveFundsViaLink/ViewModel/ReceiveFundsViaLinkViewModel.swift, p2p_wallet/Scenes/Main/Send/Models/SendTransaction.swift, p2p_wallet/Scenes/Main/Send/SendViaLink/SendCreateLinkCoordinator.swift, p2p_wallet/Scenes/Main/Swap/Common/Models/JupiterSwapTransaction.swift, p2p_wallet/Scenes/Main/Swap/State/BusinessLogic/Helpers/JupiterSwapBusinessLogic+Calculate.swift, p2p_wallet/Scenes/Main/Swap/State/BusinessLogic/JupiterSwapBusinessLogic.swift, p2p_wallet/Scenes/Main/Wormhole/Claim/WormholeClaimViewModel.swift, p2p_wallet/Scenes/Web3Auth/Onboarding/CreateWallet/CreateWalletCoordinator.swift, p2p_wallet/Scenes/Web3Auth/Onboarding/CreateWallet/Steps/EnterPhoneNumber/BaseOTPViewModel.swift, p2p_wallet/Scenes/Web3Auth/Onboarding/CreateWallet/Steps/SocialSignIn/SocialSignInTryAgain/SocialSignInTryAgainViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-9278
-
=> [PWN-9278] Feature/pwn 9278 2

p2p_wallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, p2p_wallet/Scenes/Main/NewHome/HomeCoordinator.swift, p2p_wallet/Scenes/Main/NewHome/HomeView.swift, p2p_wallet/Scenes/Main/NewHome/HomeViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-9345
-
=> [PWN-9345] Fix Wallet screen state

p2p_wallet/Scenes/Main/Crypto/Components/Crypto Accounts/CryptoAccountsViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-9378
-
=> [PWN-9378] Observe "hide zero balances" toggle

p2p_wallet/Scenes/Main/Crypto/Components/Crypto Actions Panel/CryptoActionsPanelViewModel.swift, p2p_wallet/Scenes/Main/NewHome/Subview/AccountList/HomeAccountsViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-9375
-
=> [PWN-9375] Remove rounding for balance on Wallet and Crypto screens

p2p_wallet/Scenes/Main/NewHome/Subview/AccountList/HomeAccountsViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-9377
-
=> [PWN-9377] Fix token amount formatting on the Wallet screen

Packages/KeyAppKit/Sources/BankTransfer/Models/UserWallet.swift, Packages/KeyAppKit/Sources/BankTransfer/Striga/Mock/MockStrigaRemoteProvider.swift, Packages/KeyAppKit/Sources/BankTransfer/Striga/Models/StrigaEndpoint.swift, Packages/KeyAppKit/Sources/BankTransfer/Striga/Models/StrigaInitiateSEPAPaymentResponse.swift, Packages/KeyAppKit/Sources/BankTransfer/Striga/Models/StrigaWithdrawalInfo.swift, Packages/KeyAppKit/Sources/BankTransfer/Striga/Repository/DataProviders/StrigaLocalProvider.swift, Packages/KeyAppKit/Sources/BankTransfer/Striga/Repository/DataProviders/StrigaRemoteProvider.swift, Packages/KeyAppKit/Sources/BankTransfer/Striga/Repository/DataProviders/StrigaRemoteProviderImpl.swift, Packages/KeyAppKit/Sources/BankTransfer/Striga/Repository/StrigaBankTransferUserDataRepository.swift, Packages/KeyAppKit/Sources/BankTransfer/UserAction/StrigaBankTransferOutgoingUserActionConsumer.swift, Packages/KeyAppKit/Tests/UnitTests/BankTransferTests/StrigaRemoteProviderTests.swift, p2p_wallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, p2p_wallet/Injection/Resolver+registerAllServices.swift, p2p_wallet/Resources/Base.lproj/Localizable.strings, p2p_wallet/Resources/en.lproj/Localizable.strings, p2p_wallet/Resources/fr.lproj/Localizable.strings, p2p_wallet/Resources/ru.lproj/Localizable.strings, p2p_wallet/Resources/vi.lproj/Localizable.strings, p2p_wallet/Scenes/Main/BankTransfer/Claim/StrigaClaimTransaction.swift, p2p_wallet/Scenes/Main/BankTransfer/IBANDetails/IBANDetailsView.swift, p2p_wallet/Scenes/Main/NewHome/HomeCoordinator.swift, p2p_wallet/Scenes/Main/NewHome/Subview/AccountList/HomeAccountsView.swift, p2p_wallet/Scenes/Main/NewHome/Subview/AccountList/HomeAccountsViewModel.swift, p2p_wallet/Scenes/Main/NewHome/Subview/AccountList/Model/BankTransferRenderableAccount.swift, p2p_wallet/Scenes/Main/NewHome/Subview/AccountList/Subview/HomeBankTransferAccountView.swift
https://p2pvalidator.atlassian.net/browse/PWN-9259
-
=> [PWN-9259] Finish confirm button action handlers

p2p_wallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, p2p_wallet/Common/Extensions/Double+Extensions.swift, p2p_wallet/Scenes/Main/NewHome/Subview/AccountList/HomeAccountsViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-9390
-
=> [PWN-9390] Show custom format when balance < 0.01 on Wallet

p2p_wallet/Common/Extensions/Double+Extensions.swift, p2p_wallet/Scenes/Main/NewHome/Subview/AccountList/HomeAccountsViewModel.swift
Reverts p2p-org/p2p-wallet-ios#1507
=> Revert "[PWN-9390] Show custom format when balance < 0.01 on Wallet"

p2p_wallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, p2p_wallet/Scenes/TabBar/CustomTabBar.swift, p2p_wallet/Scenes/TabBar/TabBarController.swift
https://p2pvalidator.atlassian.net/browse/PWN-9358
-
=> [PWN-9358] Increase tappable area of the Send button

p2p_wallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, p2p_wallet/Scenes/Main/BankTransfer/StrigaRegistration/Subviews/StrigaRegistrationTextField.swift, p2p_wallet/Scenes/Main/BankTransfer/Withdraw/WithdrawView.swift
https://p2pvalidator.atlassian.net/browse/PWN-9364
-
=> [PWN-9364] Textfield fix

p2p_wallet/Scenes/Main/BankTransfer/BankTransferCoordinator.swift, p2p_wallet/Scenes/Main/BankTransfer/Claim/BankTransferClaimCoordinator.swift, p2p_wallet/Scenes/Main/BankTransfer/Withdraw/WithdrawCoordinator.swift, p2p_wallet/Scenes/Main/BankTransfer/Withdraw/WithdrawViewModel.swift, p2p_wallet/Scenes/Main/BankTransfer/WithdrawCalculator/WithdrawCalculatorCoordinator.swift, p2p_wallet/Scenes/Main/BankTransfer/otp/StrigaOTPCoordinator.swift, p2p_wallet/Scenes/Main/NewHome/HomeCoordinator.swift, p2p_wallet/Scenes/Main/NewHome/Subview/AccountList/HomeAccountsViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-9257
-
=> [PWN-9257] New withdraw strategy and api call

p2p_wallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, p2p_wallet/Resources/Base.lproj/Localizable.strings, p2p_wallet/Resources/en.lproj/Localizable.strings, p2p_wallet/Resources/fr.lproj/Localizable.strings, p2p_wallet/Resources/ru.lproj/Localizable.strings, p2p_wallet/Resources/vi.lproj/Localizable.strings, p2p_wallet/Scenes/Actions/ActionsViewActionType.swift
https://p2pvalidator.atlassian.net/browse/PWN-9433
-
=> [PWN-9433] Fix fee label

p2p_wallet/Scenes/Main/BankTransfer/Claim/BankTransferClaimCoordinator.swift
https://p2pvalidator.atlassian.net/browse/PWN-9436
-
=> [PWN-9436] Start timer once transaction is called

Packages/KeyAppKit/Sources/BankTransfer/Striga/Extensions/NSError+Extensions.swift, Packages/KeyAppKit/Sources/BankTransfer/UserAction/StrigaBankTransferOutgoingUserActionConsumer.swift, Packages/KeyAppKit/Sources/BankTransfer/UserAction/StrigaBankTransferUserActionConsumer.swift, Packages/KeyAppKit/Sources/KeyAppBusiness/UserAction/UserActionError.swift, p2p_wallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, p2p_wallet/Scenes/Main/NewHome/Subview/AccountList/HomeAccountsViewModel.swift, p2p_wallet/Scenes/Main/NewHome/Subview/AccountList/Model/BankTransferRenderableAccount.swift, p2p_wallet/UI/SwiftUI/Renderable/FinanceBlockView.swift
https://p2pvalidator.atlassian.net/browse/PWN-9440
-
=> [PWN-9440] Return Network error if request is failed due to connection

Packages/KeyAppKit/Sources/BankTransfer/UserAction/StrigaBankTransferOutgoingUserActionConsumer.swift, p2p_wallet/Common/Extensions/String+Extensions.swift, p2p_wallet/Common/Models/PendingTransaction.swift, p2p_wallet/Common/Services/TransactionHandler/TransactionHandler+Extensions.swift, p2p_wallet/Common/Services/TransactionHandler/TransactionHandler.swift, p2p_wallet/Resources/Base.lproj/Localizable.strings, p2p_wallet/Resources/en.lproj/Localizable.strings, p2p_wallet/Resources/fr.lproj/Localizable.strings, p2p_wallet/Resources/ru.lproj/Localizable.strings, p2p_wallet/Resources/vi.lproj/Localizable.strings, p2p_wallet/Scenes/Main/BankTransfer/Claim/BankTransferClaimCoordinator.swift, p2p_wallet/Scenes/Main/BankTransfer/Claim/StrigaClaimTransaction.swift, p2p_wallet/Scenes/Main/BankTransfer/WithdrawCalculator/WithdrawCalculatorCoordinator.swift, p2p_wallet/Scenes/Main/BankTransfer/WithdrawCalculator/WithdrawCalculatorViewModel.swift, p2p_wallet/Scenes/Main/History/New/Aggregator/HistoryPendingTransactionAggregator.swift, p2p_wallet/Scenes/Main/History/New/Aggregator/HistoryViewModelAggregator.swift, p2p_wallet/Scenes/Main/History/New/Model/RendableListTransactionItem+PendingTransaction.swift, p2p_wallet/Scenes/Main/NewHome/HomeCoordinator.swift, p2p_wallet/Scenes/Main/NewHome/Subview/AccountList/HomeAccountsViewModel.swift, p2p_wallet/Scenes/Main/ReceiveFundsViaLink/ViewModel/ReceiveFundsViaLinkViewModel.swift, p2p_wallet/Scenes/Main/Send/SendViaLink/SendCreateLinkCoordinator.swift, p2p_wallet/Scenes/Main/TransactionDetailView/Model/RendableDetailTransaction+ParsedTransaction.swift, p2p_wallet/Scenes/Main/TransactionDetailView/Model/RendableDetailTransaction+PendingTransaction.swift, p2p_wallet/Scenes/Main/TransactionDetailView/Model/RenderableTransactionDetail.swift, p2p_wallet/Scenes/Main/TransactionDetailView/Subview/TransactionDetailStatusView.swift, p2p_wallet/Scenes/Main/TransactionDetailView/TransactionDetailViewModel.swift
=> Bottomsheet fixes

Packages/KeyAppKit/Sources/Send/Input/SendInputBusinessLogic+ChangeToken.swift, Packages/KeyAppKit/Sources/Send/Input/Services/SendFeeCalculator.swift, p2p_wallet/Scenes/Main/Send/Input/SendInputViewModel.swift, p2p_wallet/Scenes/Main/Send/Models/SendTransaction.swift, p2p_wallet/Scenes/Main/Send/TransactionStatus/SendTransactionStatusView.swift
https://p2pvalidator.atlassian.net/browse/PWN-9438
-
=> [PWN-9438] feat: Send as SendViaLink

Packages/KeyAppKit/Sources/KeyAppBusiness/Solana/SolanaTokenService.swift
https://p2pvalidator.atlassian.net/browse/PWN-9461
-
=> [PWN-9461] feat: fix wrong mint of native solana returned from server

Packages/KeyAppKit/Sources/BankTransfer/Striga/Models/StrigaEndpoint.swift, Packages/KeyAppKit/Tests/UnitTests/BankTransferTests/StrigaEndpointTests.swift
https://p2pvalidator.atlassian.net/browse/PWN-9292
- https://github.com/p2p-org/p2p-wallet-ios-secret/pull/36
=> [PWN-9292] Update all striga endpoints

Packages/KeyAppKit/Sources/BankTransfer/Striga/Models/StrigaEndpoint.swift, Packages/KeyAppKit/Tests/UnitTests/BankTransferTests/StrigaEndpointTests.swift
=> [PWN-8165] Return working striga method

p2p_wallet/Scenes/Main/Swap/Swap/SwapViewModel.swift
https://p2pvalidator.atlassian.net/browse/PWN-9485
-
=> [PWN-9485] Remove extra viewState argument to schedule an update

Packages/KeyAppKit/Sources/KeyAppBusiness/Solana/SolanaAccountsService.swift, p2p_wallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, p2p_wallet/Scenes/Main/Crypto/Components/Crypto Accounts/CryptoAccountCellView.swift, p2p_wallet/Scenes/Main/Crypto/Components/Crypto Accounts/CryptoAccountsView.swift
https://p2pvalidator.atlassian.net/browse/PWN-9490
-
=> [PWN-9490] Fix for updating cell

p2p_wallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, p2p_wallet/Scenes/TabBar/CustomTabBar.swift, p2p_wallet/Scenes/TabBar/TabBarController.swift
https://p2pvalidator.atlassian.net/browse/PWN-9353
-
=> [PWN-9353] Fix UITabBar appearance

Packages/KeyAppKit/Sources/BankTransfer/Striga/Mock/MockStrigaLocalProvider.swift, Packages/KeyAppKit/Sources/BankTransfer/UserAction/StrigaBankTransferUserActionConsumer.swift, p2p_wallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, p2p_wallet/Scenes/Main/BankTransfer/Claim/StrigaClaimTransaction.swift, p2p_wallet/Scenes/Main/BankTransfer/WithdrawCalculator/WithdrawCalculatorCoordinator.swift, p2p_wallet/Scenes/Main/NewHome/HomeViewModel.swift, p2p_wallet/Scenes/Main/NewHome/Subview/AccountList/HomeAccountsView.swift, p2p_wallet/Scenes/Main/NewHome/Subview/AccountList/HomeAccountsViewModel.swift, p2p_wallet/Scenes/Main/NewHome/Subview/AccountList/Subview/HomeBankTransferAccountView.swift, p2p_wallet/Scenes/Main/TransactionDetailView/Model/RendableDetailTransaction+PendingTransaction.swift, p2p_wallet/UI/SwiftUI/Renderable/FinanceBlockView.swift
=> Bottomsheet + cells
